### ISSUE TITLE
Everpad 2.2.0 crashes on startup (Ubuntu 12.10 x64)

### ISSUE THREAD

**Issue by hdave** [nvbn/everpad#131]
Running manually returns:

```
Traceback (most recent call last):
  File "/usr/bin/everpad-lens", line 9, in <module>
    load_entry_point('everpad==2.2dev', 'console_scripts', 'everpad-lens')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 337, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2311, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2022, in load
    raise ImportError("%r has no %r attribute" % (entry,attr))
ImportError: <module 'everpad.specific.unity' from '/usr/lib/pymodules/python2.7/everpad/specific/unity/__init__.pyc'> has no 'main' attribute
```

**Comment by nvbn** [comment]
Package with fixes available in ppa, just upgrade

**Comment by hdave** [comment]
works.
