### ISSUE TITLE
everpad-lens crash on ubuntu 12.04

### ISSUE THREAD

**Issue by dotjorgeu** [nvbn/everpad#132]
Ubuntu 12.04 x86-64 2.2-0~precise.

Unity report the crash on startup. 

```
~$ everpad-lens 
Traceback (most recent call last):
  File "/usr/bin/everpad-lens", line 9, in <module>
    load_entry_point('everpad==2.2dev', 'console_scripts', 'everpad-lens')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 337, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2279, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1994, in load
    raise ImportError("%r has no %r attribute" % (entry,attr))
ImportError: <module 'everpad.specific.unity' from '/usr/lib/pymodules/python2.7/everpad/specific/unity/__init__.pyc'> has no 'main' attribute
```

The tried to replace the current running

```
~$ everpad --replace
Traceback (most recent call last):
  File "/usr/bin/everpad", line 9, in <module>
    load_entry_point('everpad==2.2dev', 'gui_scripts', 'everpad')()
  File "/usr/lib/pymodules/python2.7/everpad/pad/indicator.py", line 260, in main
    app.launcher = get_launcher('application://everpad.desktop', session_bus, '/')
  File "/usr/lib/pymodules/python2.7/everpad/specific/__init__.py", line 14, in get_launcher
    return launcher(*args, **kwargs)
  File "/usr/lib/pymodules/python2.7/everpad/specific/unity/launcher.py", line 9, in __init__
    dbus.service.Object.__init__(self, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/dbus/service.py", line 485, in __init__
    self.add_to_connection(conn, object_path)
  File "/usr/lib/python2.7/dist-packages/dbus/service.py", line 576, in add_to_connection
    self._fallback)
RuntimeError: To make asynchronous calls, receive signals or export objects, D-Bus connections must be attached to a main loop by passing mainloop=... to the constructor or calling dbus.set_default_main_loop(...)
```

**Comment by nvbn** [comment]
Try upgrade to latest version from ppa

**Comment by dotjorgeu** [comment]
Still crashes

```
~$ sudo apt-get upgrade
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages will be upgraded:
  everpad google-chrome-stable
2 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Need to get 36.5 MB of archives.
After this operation, 5,583 kB of additional disk space will be used.
Do you want to continue [Y/n]? 
Get:1 http://dl.google.com/linux/chrome/deb/ stable/main google-chrome-stable amd64 23.0.1271.64-r165188 [36.2 MB]
Get:2 http://ppa.launchpad.net/nvbn-rm/ppa/ubuntu/ precise/main everpad amd64 2.2.1-0~precise [256 kB]
Fetched 36.5 MB in 5min 31s (110 kB/s)                                                                                                                 
(Reading database ... 418045 files and directories currently installed.)
Preparing to replace google-chrome-stable 22.0.1229.94-r161065 (using .../google-chrome-stable_23.0.1271.64-r165188_amd64.deb) ...
Unpacking replacement google-chrome-stable ...
Preparing to replace everpad 2.2-0~precise (using .../everpad_2.2.1-0~precise_amd64.deb) ...
Unpacking replacement everpad ...
Processing triggers for bamfdaemon ...
Rebuilding /usr/share/applications/bamf.index...
Processing triggers for desktop-file-utils ...
Processing triggers for gnome-menus ...
Processing triggers for man-db ...
Processing triggers for python-support ...
Processing triggers for hicolor-icon-theme ...
Setting up google-chrome-stable (23.0.1271.64-r165188) ...
Setting up everpad (2.2.1-0~precise) ...
Processing triggers for python-support ...

~$ everpad --replace
Traceback (most recent call last):
  File "/usr/bin/everpad", line 9, in <module>
    load_entry_point('everpad==2.2.1dev', 'gui_scripts', 'everpad')()
  File "/usr/lib/pymodules/python2.7/everpad/pad/indicator.py", line 260, in main
    app.launcher = get_launcher('application://everpad.desktop', session_bus, '/')
  File "/usr/lib/pymodules/python2.7/everpad/specific/__init__.py", line 14, in get_launcher
    return launcher(*args, **kwargs)
  File "/usr/lib/pymodules/python2.7/everpad/specific/unity/launcher.py", line 9, in __init__
    dbus.service.Object.__init__(self, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/dbus/service.py", line 485, in __init__
    self.add_to_connection(conn, object_path)
  File "/usr/lib/python2.7/dist-packages/dbus/service.py", line 576, in add_to_connection
    self._fallback)
RuntimeError: To make asynchronous calls, receive signals or export objects, D-Bus connections must be attached to a main loop by passing mainloop=... to the constructor or calling dbus.set_default_main_loop(...)
```

**Comment by nvbn** [comment]
Try without --replace

**Comment by dotjorgeu** [comment]
ok it doesn't crash but only starts the panel icon. Gonna logout/login to see if the lens start

**Comment by nvbn** [comment]
Yes, or just restart unity with unity --replace

**Comment by dotjorgeu** [comment]
oh yeah. Working perfectly. Good job as always.
