### ISSUE TITLE
Support for inline HTTP proxies

### ISSUE THREAD

**Issue by ghostkadost** [nvbn/everpad#142]
I am using Evernote in an environment that uses inline HTTP proxy (bluecoat). Such proxies do not have a separate hostname/port. They only need username/password. In a such a network configuration I am unable to authorize Everpad. It does not prompt for username /password and hence the proxy denies the request.

**Comment by pelenthium** [comment]
+1
cementovoz@Latitude-E6420 ~ $ everpad
"sni-qt/12299" WARN  11:26:34.008 void StatusNotifierItemFactory::connectToSnw() Invalid interface to SNW_SERVICE 
Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.7/everpad/pad/management.py", line 175, in change_auth
    'GET')
  File "/usr/lib/python2.7/dist-packages/oauth2/**init**.py", line 682, in request
    connection_type=connection_type)
  File "/usr/lib/python2.7/dist-packages/httplib2/**init**.py", line 1543, in request
    (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
  File "/usr/lib/python2.7/dist-packages/httplib2/__init__.py", line 1293, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "/usr/lib/python2.7/dist-packages/httplib2/__init__.py", line 1267, in _conn_request
    conn.connect()
  File "/usr/lib/python2.7/dist-packages/httplib2/__init__.py", line 1018, in connect
    raise socket.error, msg
socket.error: [Errno 110] Connection timed out
proxies set as export http_proxy="..." and export https_proxy="..."

**Comment by fmoo** [comment]
What's the format of the http_proxy and https_proxy strings?  You don't have to provide the actual username/password values, just looking for what the format is like.

**Comment by pelenthium** [comment]
cementovoz@Latitude-E6420 ~ $ echo $https_proxy
https://www-proxy.99frankoff.ru:80/
this proxy not public, and it certainly works.All my internet work through this proxy.

**Comment by fmoo** [comment]
@cementovoz your issue is different.  You are using https:// to connect to a proxy, not using a transparent proxy like bluecoat afaict.

**Comment by fmoo** [comment]
@cementovoz - just out of curiosity, does it work if you change the scheme on https_proxy= from https:// to http:// ?

**Comment by fmoo** [comment]
Or if possible, test out my develop branch? https://github.com/fmoo/everpad/tree/develop ?  It uses a newer httplib2 api from >=0.7.3
