### ISSUE TITLE
D-Bus coonections main loop

### ISSUE THREAD

**Issue by hdg700** [nvbn/everpad#18]
$ ./everpad
Traceback (most recent call last):
  File "./everpad", line 8, in <module>
    indicator.main()
  File "/usr/lib/python2.7/site-packages/everpad-0.9999dev-py2.7.egg/everpad/pad/indicator.py", line 152, in main
    service = EverpadService(app, session_bus, '/EverpadService')
  File "/usr/lib/python2.7/site-packages/everpad-0.9999dev-py2.7.egg/everpad/pad/indicator.py", line 126, in **init**
    dbus.service.Object.**init**(self, _args, *_kwargs)
  File "/usr/lib/python2.7/site-packages/dbus/service.py", line 485, in **init**
    self.add_to_connection(conn, object_path)
  File "/usr/lib/python2.7/site-packages/dbus/service.py", line 576, in add_to_connection
    self._fallback)
RuntimeError: To make asynchronous calls, receive signals or export objects, D-Bus connections must be attached to a main loop by passing mainloop=... to the constructor or calling dbus.set_default_main_loop(...)

**Comment by nvbn** [comment]
You use version from ppa or git?
And what ubuntu version?

**Comment by hdg700** [comment]
git version.
archlinux :)

**Comment by nvbn** [comment]
Try update to latest version =)
And what python, pyside and pygobject version?

**Comment by hdg700** [comment]
$ yaourt -Q python2
extra/python2 2.7.3-2

$ yaourt -Qs pyside
local/python2-pyside 1.1.1-2

$ yaourt -Qs pygobject
extra/python2-gobject2 2.28.6-6

**Comment by hdg700** [comment]
[01:45] ~/downloads/nvbn-everpad-8ee3782 [hdg700@localhost]
$ everpad
Traceback (most recent call last):
  File "/usr/bin/everpad", line 9, in <module>
    load_entry_point('everpad==1.2dev', 'gui_scripts', 'everpad')()
  File "/usr/lib/python2.7/site-packages/everpad-1.2dev-py2.7.egg/everpad/pad/indicator.py", line 160, in main
    service = EverpadService(app, session_bus, '/EverpadService')
  File "/usr/lib/python2.7/site-packages/everpad-1.2dev-py2.7.egg/everpad/pad/indicator.py", line 134, in **init**
    dbus.service.Object.**init**(self, _args, *_kwargs)
  File "/usr/lib/python2.7/site-packages/dbus/service.py", line 485, in **init**
    self.add_to_connection(conn, object_path)
  File "/usr/lib/python2.7/site-packages/dbus/service.py", line 576, in add_to_connection
    self._fallback)
RuntimeError: To make asynchronous calls, receive signals or export objects, D-Bus connections must be attached to a main loop by passing mainloop=... to the constructor or calling dbus.set_default_main_loop(...)
