### ISSUE TITLE
other linux (fedora) installation problem

### ISSUE THREAD

**Issue by gregor2005** [nvbn/everpad#180]
hi,

today i read an blogentry about your tool, currently i use nevernote (nixnote) to use evernote on my linux machine, but its time to test another implementation.
so i downloaded the whole git repo and tried the way like described in the wiki for other os:https://github.com/nvbn/everpad/wiki/how-to-install
python setup.py give me the following output:
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

error: no commands supplied

which command are needed to build or run everpad on other systems than ubuntu or debian based systems?

greetings from austria
gregor

**Comment by nvbn** [comment]
Try:

<pre>
python setup.py install
</pre>

**Comment by gregor2005** [comment]
thank you i was able to install everpad but know i didn't run i get: 
Traceback (most recent call last):
  File "/usr/bin/everpad", line 9, in <module>
    load_entry_point('everpad==2.3dev', 'gui_scripts', 'everpad')()
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 337, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 2307, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 2017, in load
    entry = **import**(self.module_name, globals(),globals(), ['**name**'])
  File "/usr/lib/python2.7/site-packages/everpad-2.3dev-py2.7.egg/everpad/pad/indicator.py", line 3, in <module>
    from PySide.QtCore import Slot, QTranslator, QLocale, Signal, QSettings, QT_TRANSLATE_NOOP
ImportError: No module named PySide.QtCore

py qt packages are installed, which can be missing?

greetings
gregor

**Comment by nvbn** [comment]
You need to install pyside.

**Comment by gregor2005** [comment]
now i get these message, python-oauth2 and python-requests is installed:

Traceback (most recent call last):
  File "/usr/bin/everpad", line 9, in <module>
    load_entry_point('everpad==2.3dev', 'gui_scripts', 'everpad')()
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 337, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 2307, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 2017, in load
    entry = **import**(self.module_name, globals(),globals(), ['**name**'])
  File "/usr/lib/python2.7/site-packages/everpad-2.3dev-py2.7.egg/everpad/pad/indicator.py", line 9, in <module>
    from everpad.pad.management import Management
  File "/usr/lib/python2.7/site-packages/everpad-2.3dev-py2.7.egg/everpad/pad/management.py", line 25, in <module>
    import oauth2 as oauth
ImportError: No module named oauth2

**Comment by nvbn** [comment]
Try to install oauth2 from pip

**Comment by gregor2005** [comment]
sry for the delay.

## i installed python-oauth2, now i get:

Traceback (most recent call last):
  File "/usr/bin/everpad", line 9, in <module>
    load_entry_point('everpad==2.4dev', 'gui_scripts', 'everpad')()
  File "/usr/lib/python2.7/site-packages/everpad-2.4dev-py2.7.egg/everpad/pad/indicator.py", line 279, in main
    app.provider = get_provider(session_bus)
  File "/usr/lib/python2.7/site-packages/everpad-2.4dev-py2.7.egg/everpad/tools.py", line 37, in wrapper
    return InterfaceWrapper(partial(fnc, _args, *_kwrags))
  File "/usr/lib/python2.7/site-packages/everpad-2.4dev-py2.7.egg/everpad/tools.py", line 14, in **init**
    self.**load()
  File "/usr/lib/python2.7/site-packages/everpad-2.4dev-py2.7.egg/everpad/tools.py", line 17, in __load
    self.__interface = self.__get()
  File "/usr/lib/python2.7/site-packages/everpad-2.4dev-py2.7.egg/everpad/tools.py", line 44, in get_provider
    provider = bus.get_object("com.everpad.Provider", '/EverpadProvider')
  File "/usr/lib/python2.7/site-packages/dbus/bus.py", line 241, in get_object
    follow_name_owner_changes=follow_name_owner_changes)
  File "/usr/lib/python2.7/site-packages/dbus/proxies.py", line 248, in __init**
    self._named_service = conn.activate_name_owner(bus_name)
  File "/usr/lib/python2.7/site-packages/dbus/bus.py", line 180, in activate_name_owner
    self.start_service_by_name(bus_name)
  File "/usr/lib/python2.7/site-packages/dbus/bus.py", line 278, in start_service_by_name
    'su', (bus_name, flags)))
  File "/usr/lib/python2.7/site-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.Spawn.ChildExited: Process /usr/bin/everpad-provider exited with status 1
