### ISSUE TITLE
Not authorizing in Bodhi Linux 2.1.0

### ISSUE THREAD

**Issue by ronaldpottol** [nvbn/everpad#182]
Trying what was sugested for kubuntu, I kill everpad-provider, start it in a terminal, launch everpad, and try to authenticate. That looks like it succeeds, but everpad still wants to be authorized, and this appears in the terminal I launched everpad-provider in:

ERROR:dbus.proxies:Introspect error on :1.17:/org/freedesktop/secrets/aliases/default: dbus.exceptions.DBusException: org.freedesktop.Secret.Error.NoSuchObject: The '/org/freedesktop/secrets/aliases/default' object does not exist
ERROR:dbus.connection:Unable to set arguments ({'org.freedesktop.Secret.Item.Label': 'oauth_token @ everpad', 'org.freedesktop.Secret.Item.Attributes': {'username': 'oauth_token', 'service': 'everpad'}}, dbus.Struct((dbus.ObjectPath('/org/freedesktop/secrets/session/s5'), '', dbus.ByteArray(''), 'text/plain'), signature=None), True) according to signature None: <type 'exceptions.TypeError'>: Expected a string or unicode object
Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.7/everpad/provider/daemon.py", line 59, in on_remove_authenticated
    set_auth_token('')
  File "/usr/lib/pymodules/python2.7/everpad/provider/tools.py", line 28, in set_auth_token
    keyring.set_password('everpad', 'oauth_token', token)
  File "/usr/lib/python2.7/dist-packages/keyring/core.py", line 42, in set_password
    _keyring_backend.set_password(service_name, username, password)
  File "/usr/lib/python2.7/dist-packages/keyring/backend.py", line 234, in set_password
    True)
  File "/usr/lib/python2.7/dist-packages/dbus/proxies.py", line 70, in __call__
    return self._proxy_method(_args, *_keywords)
  File "/usr/lib/python2.7/dist-packages/dbus/proxies.py", line 145, in __call__
    *_keywords)
  File "/usr/lib/python2.7/dist-packages/dbus/connection.py", line 641, in call_blocking
    message.append(signature=signature, *args)
TypeError: Expected a string or unicode object
ERROR:dbus.proxies:Introspect error on :1.17:/org/freedesktop/secrets/aliases/default: dbus.exceptions.DBusException: org.freedesktop.Secret.Error.NoSuchObject: The '/org/freedesktop/secrets/aliases/default' object does not exist
ERROR:dbus.connection:Unable to set arguments ({'org.freedesktop.Secret.Item.Label': 'oauth_token @ everpad', 'org.freedesktop.Secret.Item.Attributes': {'username': 'oauth_token', 'service': 'everpad'}}, dbus.Struct((dbus.ObjectPath('/org/freedesktop/secrets/session/s6'), '', dbus.ByteArray('S=s1:U=7c30:E=142ca5c7235:C=13b72ab4636:P=185:A=nvbn-1422:H=28cbfd62411798e1c41470f291758f15'), 'text/plain'), signature=None), True) according to signature None: <type 'exceptions.TypeError'>: Expected a string or unicode object
Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.7/everpad/provider/daemon.py", line 53, in on_authenticate
    set_auth_token(token)
  File "/usr/lib/pymodules/python2.7/everpad/provider/tools.py", line 28, in set_auth_token
    keyring.set_password('everpad', 'oauth_token', token)
  File "/usr/lib/python2.7/dist-packages/keyring/core.py", line 42, in set_password
    _keyring_backend.set_password(service_name, username, password)
  File "/usr/lib/python2.7/dist-packages/keyring/backend.py", line 234, in set_password
    True)
  File "/usr/lib/python2.7/dist-packages/dbus/proxies.py", line 70, in __call__
    return self._proxy_method(_args, *_keywords)
  File "/usr/lib/python2.7/dist-packages/dbus/proxies.py", line 145, in **call**
    *_keywords)
  File "/usr/lib/python2.7/dist-packages/dbus/connection.py", line 641, in call_blocking
    message.append(signature=signature, *args)
TypeError: Expected a string or unicode object
^C
I have installed it on Ubuntu 21.10 32 bit where it seems to work, this is on 64 bit Bodhi linux, which is an updated LTS Ubuntu (12.04 currently) with Enlightenment 17 as a window manager.

**Comment by ronaldpottol** [comment]
Rebooted yet again, now it seems to be working.
