### ISSUE TITLE
Everpad 2.3 crash in Ubuntu 12.04 64bit

### ISSUE THREAD

**Issue by wickiup** [nvbn/everpad#189]
When click the icon, everpad would crash. The error message is as below:

Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.7/everpad/pad/indicator.py", line 85, in update
    20 - len(pin_notes), Note.ORDER_UPDATED_DESC, 0,
  File "/usr/lib/pymodules/python2.7/everpad/tools.py", line 30, in wrapper
    return getattr(self.**interface, name)(_args, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/dbus/proxies.py", line 70, in __call**
    return self._proxy_method(_args, *_keywords)
  File "/usr/lib/python2.7/dist-packages/dbus/proxies.py", line 145, in __call__
    **keywords)
  File "/usr/lib/python2.7/dist-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Python.TypeError: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/dbus/service.py", line 751, in _message_cb
    _method_reply_return(connection, message, method_name, signature, *retval)
  File "/usr/lib/python2.7/dist-packages/dbus/service.py", line 254, in _method_reply_return
    reply.append(signature=signature, *retval)
TypeError: an integer is required

**Comment by emviveros** [comment]
I have crash report on Ubuntu 12.04.1 x64 too.. Trying to create new note, on Unity upper panel directly, "Create Note", everytime everpad crashes. If I try to create note using the "All Notes" first everything is ok.

**Comment by cas--** [comment]
Are you using the package from PPA or git develop code?

**Comment by emviveros** [comment]
PPA! ppa:nvbn-rm/ppa (precise)

**Comment by wickiup** [comment]
Mine is from PPA

**Comment by CodeMonk** [comment]
Broken for me as well from PPA . . . is git working?

**Comment by CodeMonk** [comment]
I installed from git, and it looks like everpad-lens is hanging . . .

**Comment by mcardillo55** [comment]
I had a similar error from the git code until commit c9ab5c80f78b5ac873fbd180e67ea2072c3b3c78. Now the develop branch and the most up-to-date PPA package both work for me. I'm using Ubuntu 12.10 on x86.

**Comment by CodeMonk** [comment]
x86_64 still hanging.

**Comment by nvbn** [comment]
Do you use any third party repositories?

**Comment by e2jk** [comment]
Is this still an active issue with version 2.5 in the PPA?

**Comment by Melissa-Kay** [comment]
Just installed via PPA... 12.04.04 64 bit. Same crash error when launching the icon
