### ISSUE TITLE
Не работает в ubuntu 12.04

### ISSUE THREAD

**Issue by paulelms** [nvbn/everpad#2]
Traceback (most recent call last):
  File "/usr/bin/everpad", line 9, in <module>
    load_entry_point('everpad==0.4.1dev', 'gui_scripts', 'everpad')()
  File "/usr/lib/pymodules/python2.7/everpad/pad.py", line 342, in main
    app = App(sys.argv)
  File "/usr/lib/pymodules/python2.7/everpad/pad.py", line 198, in **init**
    self.provider_obj = dbus.SessionBus().get_object("com.everpad.Provider", '/EverpadProvider')
  File "/usr/lib/python2.7/dist-packages/dbus/bus.py", line 241, in get_object
    follow_name_owner_changes=follow_name_owner_changes)
  File "/usr/lib/python2.7/dist-packages/dbus/proxies.py", line 248, in **init**
    self._named_service = conn.activate_name_owner(bus_name)
  File "/usr/lib/python2.7/dist-packages/dbus/bus.py", line 180, in activate_name_owner
    self.start_service_by_name(bus_name)
  File "/usr/lib/python2.7/dist-packages/dbus/bus.py", line 278, in start_service_by_name
    'su', (bus_name, flags)))
  File "/usr/lib/python2.7/dist-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.Spawn.ChildExited: Process /usr/bin/everpad-provider exited with status 1
QThread: Destroyed while thread is still running

P.S. Спасибо, очень нужная программа.

**Comment by nvbn** [comment]
i386 или amd64?
Версия из ppa?

**Comment by paulelms** [comment]
из ppa, i386, 12.04 свеже-установленная

**Comment by unreturned** [comment]
Та же проблема, ppa, i386

**Comment by nvbn** [comment]
Ждём https://bugs.launchpad.net/ubuntu/+source/openssl/+bug/965371 , в дебиане уже поправили)

**Comment by Diomas** [comment]
У меня та же ошибка на убунте 11.10 amd64. Ставил из ppa

**Comment by nvbn** [comment]
Сейчас должно работать, пакет в ppa залит)

**Comment by ynps** [comment]
Не работает.

Traceback (most recent call last):
  File "/usr/bin/everpad", line 9, in <module>
    load_entry_point('everpad==0.9999dev', 'gui_scripts', 'everpad')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 337, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2279, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1989, in load
    entry = **import**(self.module_name, globals(),globals(), ['**name**'])
  File "/usr/lib/pymodules/python2.7/everpad/pad/indicator.py", line 16, in <module>
    import oauth2 as oauth
ImportError: No module named oauth2

**Comment by nvbn** [comment]
Добавил в зависимости к пакету, попробуйте обновить.

**Comment by ynps** [comment]
Теперь запустилось,но при попытке создать заметку ошибка.

OperationalError: (OperationalError) database is locked u'INSERT INTO notes (guid, title, content, created, updated, notebook_id, action) VALUES (?, ?, ?, ?, ?, ?, ?)' (None, dbus.String(u'New note'), dbus.String(u'New note content'), dbus.Int32(0), dbus.Int32(0), 4, 1)

**Comment by ynps** [comment]
Перезапустил программу, загрузились заметки. Новые тоже создаются. А как линза работает? Заметок там не видно, поиск тоже не работает.

**Comment by nvbn** [comment]
А если убить линзу и запустить заново, она как-нибудь ругается?
killall everpad-lens; everpad-lens
По идее должна просто искать заметки =)

**Comment by ynps** [comment]
Я так понял, что она и не запущена была.
При запуске получается это 

Traceback (most recent call last):
  File "/usr/bin/everpad-lens", line 9, in <module>
    load_entry_point('everpad==0.9999dev', 'console_scripts', 'everpad-lens')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 337, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2279, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1989, in load
    entry = **import**(self.module_name, globals(),globals(), ['**name**'])
  File "/usr/lib/pymodules/python2.7/everpad/lens.py", line 3, in <module>
    from singlet.lens import SingleScopeLens, IconViewCategory, ListViewCategory
ImportError: No module named singlet.lens

**Comment by nvbn** [comment]
А, не хватает python-unity-singlet. Нужно будет добавить в зависимости.

**Comment by ynps** [comment]
Теперь работает все. Спасибо!

**Comment by stillru** [comment]
Ubuntu x64 12.04 LTS, ppa
Не запускается.
<code>still@mobilepoint:~$ everpad
Traceback (most recent call last):
  File "/usr/bin/everpad", line 9, in <module>
    load_entry_point('everpad==1.5dev', 'gui_scripts', 'everpad')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 337, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2279, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1989, in load
    entry = **import**(self.module_name, globals(),globals(), ['**name**'])
  File "/usr/lib/pymodules/python2.7/everpad/pad/indicator.py", line 7, in <module>
    from everpad.pad.editor import Editor
  File "/usr/lib/pymodules/python2.7/everpad/pad/editor.py", line 19, in <module>
    import magic
ImportError: No module named magic
</code>

**Comment by stillru** [comment]
Доставил python-magic - он стал запускаться.
Но стоит вызвать меню настройки - выбрасывает из сессии

**Comment by nvbn** [comment]
в смысле выбрасывает?

**Comment by stillru** [comment]
В прямом. Завершает сеанс и показывает окно приветствия lightgdm

**Comment by stillru** [comment]
0_o незнаю что это было, но вроде запустилась...

**Comment by nvbn** [comment]
Это точно косяк ubuntu, приложение такое сделать не может)

**Comment by ksi** [comment]
Не ставится Version: 1.7-0~precise:

The following packages have unmet dependencies:
 everpad : Depends: python-unity-singlet but it is not going to be installed

А не ставится потому что: 

Unpacking python-unity-singlet (from .../python-unity-singlet_0.2.2-0ubuntu1_all.deb) ...
dpkg: error processing /var/cache/apt/archives/python-unity-singlet_0.2.2-0ubuntu1_all.deb (--unpack):
 trying to overwrite '/usr/share/pyshared/singlet/lens/category.py', which is also in package unity-singlet 0.2.1

**Comment by nvbn** [comment]
В репозитории нет пакета unity-singlet, тут вы что-то намудрили =)

**Comment by ksi** [comment]
Точно. Это у меня другая линза гадит. Но everpad-вская тоже не запускается: 
$ everpad-lens 
/usr/lib/python2.7/dist-packages/gobject/constants.py:24: Warning: g_boxed_type_register_static: assertion `g_type_from_name (name) == 0' failed
  import gobject._gobject
Failed to own name net.launchpad.Unity.Lens.EverpadLens. Bailing out.

**Comment by nvbn** [comment]
Это с python-unity-singlet или установленным до этого пакетом?

**Comment by ksi** [comment]
С python-unity-singlet.

**Comment by nvbn** [comment]
Странно, но можно попробовать apt-get purge everpad; apt-get install everpad и ребутнуться
