### ISSUE TITLE
GNOME Session Fallback Fails to Launch

### ISSUE THREAD

**Issue by fleamour** [nvbn/everpad#203]
Will support be back-ported?

**Comment by nvbn** [comment]
Can you post result of running `everpad` in termminal here?

**Comment by fleamour** [comment]
Traceback (most recent call last):
  File "/usr/bin/everpad", line 9, in <module>
    load_entry_point('everpad==2.3dev', 'gui_scripts', 'everpad')()
  File "/usr/lib/pymodules/python2.7/everpad/pad/indicator.py", line 299, in main
    pad = get_pad()
  File "/usr/lib/pymodules/python2.7/everpad/tools.py", line 36, in wrapper
    return InterfaceWrapper(partial(fnc, _args, *_kwrags))
  File "/usr/lib/pymodules/python2.7/everpad/tools.py", line 13, in **init**
    self.**load()
  File "/usr/lib/pymodules/python2.7/everpad/tools.py", line 16, in __load
    self.__interface = self.__get()
  File "/usr/lib/pymodules/python2.7/everpad/tools.py", line 50, in get_pad
    pad = bus.get_object("com.everpad.App", "/EverpadService")
  File "/usr/lib/python2.7/dist-packages/dbus/bus.py", line 241, in get_object
    follow_name_owner_changes=follow_name_owner_changes)
  File "/usr/lib/python2.7/dist-packages/dbus/proxies.py", line 248, in __init**
    self._named_service = conn.activate_name_owner(bus_name)
  File "/usr/lib/python2.7/dist-packages/dbus/bus.py", line 180, in activate_name_owner
    self.start_service_by_name(bus_name)
  File "/usr/lib/python2.7/dist-packages/dbus/bus.py", line 278, in start_service_by_name
    'su', (bus_name, flags)))
  File "/usr/lib/python2.7/dist-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NoReply: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.

**Comment by nvbn** [comment]
Hm, it work's for me in ubuntu 12.10 with gnome-shell-falback package.
Waht distributive and version you use?
Try to run:

``` bash
killall everpad-provider
killall everpad
everpad
```

and post output here.

**Comment by fleamour** [comment]
Yes working fine now, my bad.  Shoulda tries a fresh boot.

**Comment by fleamour** [comment]
I installed GNOME fallback then logged out of Unity & logged back in to fallback, I should of rebooted to avoid buggy behaviour.
