### ISSUE TITLE
A Question : How to uninstall it?

### ISSUE THREAD

**Issue by yuikns** [nvbn/everpad#207]
my OS is fedora 17 , and installed like this : 
sudo python setup.py install
after kill all ,
1. 
[yu@yu everpad]$ everpad-provider 
Traceback (most recent call last):
  File "/usr/bin/everpad-provider", line 9, in <module>
    load_entry_point('everpad==2.3dev', 'console_scripts', 'everpad-provider')()
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 337, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 2307, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 2017, in load
    entry = **import**(self.module_name, globals(),globals(), ['**name**'])
  File "/usr/lib/python2.7/site-packages/everpad-2.3dev-py2.7.egg/everpad/provider/daemon.py", line 4, in <module>
    from everpad.provider.sync import SyncThread
  File "/usr/lib/python2.7/site-packages/everpad-2.3dev-py2.7.egg/everpad/provider/sync.py", line 38, in <module>
    import regex
ImportError: No module named regex

2.
[yu@yu everpad]$ everpad
Traceback (most recent call last):
  File "/usr/bin/everpad", line 9, in <module>
    load_entry_point('everpad==2.3dev', 'gui_scripts', 'everpad')()
  File "/usr/lib/python2.7/site-packages/everpad-2.3dev-py2.7.egg/everpad/pad/indicator.py", line 279, in main
    app.provider = get_provider(session_bus)
  File "/usr/lib/python2.7/site-packages/everpad-2.3dev-py2.7.egg/everpad/tools.py", line 37, in wrapper
    return InterfaceWrapper(partial(fnc, _args, *_kwrags))
  File "/usr/lib/python2.7/site-packages/everpad-2.3dev-py2.7.egg/everpad/tools.py", line 14, in **init**
    self.**load()
  File "/usr/lib/python2.7/site-packages/everpad-2.3dev-py2.7.egg/everpad/tools.py", line 17, in __load
    self.__interface = self.__get()
  File "/usr/lib/python2.7/site-packages/everpad-2.3dev-py2.7.egg/everpad/tools.py", line 44, in get_provider
    provider = bus.get_object("com.everpad.Provider", '/EverpadProvider')
  File "/usr/lib/python2.7/site-packages/dbus/bus.py", line 244, in get_object
    follow_name_owner_changes=follow_name_owner_changes)
  File "/usr/lib/python2.7/site-packages/dbus/proxies.py", line 241, in __init**
    self._named_service = conn.activate_name_owner(bus_name)
  File "/usr/lib/python2.7/site-packages/dbus/bus.py", line 183, in activate_name_owner
    self.start_service_by_name(bus_name)
  File "/usr/lib/python2.7/site-packages/dbus/bus.py", line 281, in start_service_by_name
    'su', (bus_name, flags)))
  File "/usr/lib/python2.7/site-packages/dbus/connection.py", line 630, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.Spawn.ChildExited: Process /usr/bin/everpad-provider exited with status 1

-- ofcourse , it may because of me that some module hadn't installed ...

and now , I regret that I have to do something else . 
however , how can I uninstall it safely?

**Comment by nvbn** [comment]
For uninstalling you need to remove all files manually.
For fixing this error you need to install `regex` with:

``` bash
pip install regex
```

**Comment by yuikns** [comment]
dear  nvbn 
firstly, I download the source from http://pypi.python.org/pypi/regex
It may impossible for me to find the rpm package to install regex directly.

secondly , I observed the install log ,I may only delect these folders/file as follow

``` code
/usr/lib/python2.7/site-packages/everpad-2.3dev-py2.7.egg/
/usr/bin/everpad
/usr/bin/everpad-lens
/usr/bin/everpad-provider
```

I know , ask for "how to uninstall your software" is kind of impertinence, at least , in our cultural...
Thanks for your patient.
