### ISSUE TITLE
Can't start everpad on Debian Wheezy

### ISSUE THREAD

**Issue by stephanehofman** [nvbn/everpad#211]
Hi, I'm trying to install Everpad on Debian Wheezy with Gnome Shell.
What I have done :
# apt-get install python-pyside.qtcore python-pyside.qtgui python-dbus python-beautifulsoup python-pysqlite2 python-keyring  python-support python-sqlalchemy python-oauth2 python-magic python-pyside.qtwebkit python-html2text  gtk2-engines-pixbuf python-regex

python-gnomekeyring python-setuptools

$git clone https://github.com/nvbn/everpad.git
$cd everpad
# python setup.py install

When I'm lauching everpad :
$everpad
Traceback (most recent call last):
  File "/usr/local/bin/everpad", line 9, in <module>
    load_entry_point('everpad==2.3dev', 'gui_scripts', 'everpad')()
  File "/usr/local/lib/python2.7/dist-packages/everpad-2.3dev-py2.7.egg/everpad/pad/indicator.py", line 279, in main
    app.provider = get_provider(session_bus)
  File "/usr/local/lib/python2.7/dist-packages/everpad-2.3dev-py2.7.egg/everpad/tools.py", line 37, in wrapper
    return InterfaceWrapper(partial(fnc, _args, *_kwrags))
  File "/usr/local/lib/python2.7/dist-packages/everpad-2.3dev-py2.7.egg/everpad/tools.py", line 14, in **init**
    self.**load()
  File "/usr/local/lib/python2.7/dist-packages/everpad-2.3dev-py2.7.egg/everpad/tools.py", line 17, in __load
    self.__interface = self.__get()
  File "/usr/local/lib/python2.7/dist-packages/everpad-2.3dev-py2.7.egg/everpad/tools.py", line 44, in get_provider
    provider = bus.get_object("com.everpad.Provider", '/EverpadProvider')
  File "/usr/lib/python2.7/dist-packages/dbus/bus.py", line 241, in get_object
    follow_name_owner_changes=follow_name_owner_changes)
  File "/usr/lib/python2.7/dist-packages/dbus/proxies.py", line 248, in __init**
    self._named_service = conn.activate_name_owner(bus_name)
  File "/usr/lib/python2.7/dist-packages/dbus/bus.py", line 180, in activate_name_owner
    self.start_service_by_name(bus_name)
  File "/usr/lib/python2.7/dist-packages/dbus/bus.py", line 278, in start_service_by_name
    'su', (bus_name, flags)))
  File "/usr/lib/python2.7/dist-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.Spawn.ExecFailed: Failed to execute program /usr/bin/everpad-provider: Success

Can someone help me please ?
Thanks
@+

**Comment by nvbn** [comment]
Try to run `everpad-provider --verbose` and post output here

**Comment by stephanehofman** [comment]
in a the fisrt terminal, I use  
$everpad-provider --verbose
In the second terminal I use
$everpad

Now I can use everpad and configure it.
I have synchronised it, and I can watch my notes !

In the 1st terminal :
"Notebook XXX's notebook remote
Notebook My Notebook remote
Tag XX1 remote
Tag XX2 remote
Tag XX3 remote
Tag XX4 remote
Note T0 DO remote
/usr/lib/python2.7/dist-packages/sqlalchemy/sql/expression.py:1925: SAWarning: The IN-predicate on "resources.id" was invoked with an empty sequence. This results in a contradiction, which nonetheless can be expensive to evaluate.  Consider alternative strategies for improved performance.
  return self._in_impl(operators.in_op, operators.notin_op, other)
Note X remote
Note Y remote
Note Z remote
maximum recursion depth exceeded
"

So what can I you do now ?
Thanks
@+

**Comment by stephanehofman** [comment]
Just one thing : If I stop the first terminal, I have an error in everpad : "API version missmatch, please restart."
Hope that can help you ....

@+

**Comment by alanz** [comment]
My understanding is that this is the blocker http://techlek.wordpress.com/2012/12/01/stalled-attempt-to-install-everpad-on-debian-wheezy/

**Comment by stephanehofman** [comment]
So if I understand well, I have to wait for a new version of gnome-keyring. Is-it right ?
My version is 3.4.1....

@+

**Comment by alanz** [comment]
I Think so. 3.6.1-1 is currently in Debian experimental.

I wonder if it would be possible to patch 3.4.1

**Comment by stephanehofman** [comment]
So I will wait a new version of the package and try as soon as possible.
Stay tuned

**Comment by Cityscape4** [comment]
I've got Everpad working great on Debian 7 using the Ubuntu packages. See my site http://adamdekroon.com/2013/04/everpad-debian/

**Comment by alanz** [comment]
Works for me, but I had to apt-get install gir1.2-dbusmenu-glib -0.4 too

+1

**Comment by gursimar** [comment]
I followed the links to blogs http://adamdekroon.com/2013/04/everpad-debian/
I can start evernote and have the tray icon.
However I can only open settings. i can authorize but nothing else works??
In the menu of tray icon only two things appear
1. Settings and Management
2. Exit

Is there any hope??

**Comment by mferretti** [comment]
tried to follow the instructions of @Cityscape4  but couldn't get past the apt-get: looks like python-oauth2 is not jessie's repos (https://launchpad.net/debian/jessie/+package/python-oauth2)

**Comment by Cityscape4** [comment]
@mferretti That package is in the repos for Debian Wheezy: https://packages.debian.org/search?keywords=python-oauth2 My instructions were for Wheezy, the current stable version of Debian. Jessie is the "testing"" version and likely incompatible with the instructions at my site. Let me know if you figure anything out though!

**Comment by mferretti** [comment]
@Cityscape4 : sorry, I didn't notice that ... but I had a "aha!" moment and managed to install it.

I had to : 
1- enable unstable repos : deb http://ftp.us.debian.org/debian unstable main contrib non-free
2- install python-oauth2 from unstable : apt-get -t unstable install python-oauth2
3- copy & paste the apt-get install bit from your site
4 -install the following (some from your site, some deps manually resolved) 
sudo dpkg -i sni-qt_0.2.5-0ubuntu3_amd64.deb 
sudo dpkg -i libunity9_5.10.0-0ubuntu1_amd64.deb (this fails for deps)
sudo apt-get install libdee-1.0-4 (missing deps)
sudo apt-get install -f (this fixes everything getting libgee too likely from unstable)
dpkg -i gir1.2-unity-5.0_5.10.0-0ubuntu1_amd64.deb
sudo dpkg -i libunity9_5.10.0-0ubuntu1_amd64.deb 
sudo dpkg -i python-unity-singlet_0.2.2-0ubuntu1_all.deb

at this point I downloaded the latest everpad and installed successsfully
sudo dpkg -i everpad_2.15.8-0~precise_amd64.deb 

I got all the missing packages from the ubuntu site (first gave a try with apt-get install, anything that was not in deb repos I downloaded manually). The way to resolve the download path is : 
http://packages.ubuntu.com/precise/amd64/<package name and version as from error>download

hope this helps someone

**Comment by psykokwak4** [comment]
@mferretti 
tears, million thanks!
