### ISSUE TITLE
Unable to perform first sync

### ISSUE THREAD

**Issue by choyj** [nvbn/everpad#214]
I'm seeing the exact same problem as Issue #151.  I couldn't figure out how to re-open that issue, so I'm writing a new one.

Here at work, we do everything over proxies.  

I killed everything off and tried manually running everpad-provider and I get this:
choyj@z620jack ~$ /usr/bin/python2.7 /usr/bin/everpad-provider
Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.7/everpad/provider/sync.py", line 361, in run
    self.init_network()
  File "/usr/lib/pymodules/python2.7/everpad/provider/sync.py", line 377, in init_network
    self.note_store = get_note_store(self.auth_token)
  File "/usr/lib/pymodules/python2.7/everpad/provider/tools.py", line 51, in get_note_store
    http_proxy=get_proxy_config(urlparse(user_store_uri).scheme))
  File "/usr/lib/pymodules/python2.7/thrift/transport/THttpClient.py", line 72, in **init**
    raise ValueError("Unsupported Proxy Scheme, %s" % http_proxy.scheme)
ValueError: Unsupported Proxy Scheme, https

When I unset https_proxy, and re-run everpad-provider, the error goes away, but I still cannot do a sync.

**Comment by fmoo** [comment]
Does it work if you set your https_proxy=http://web-proxy.xxxx.com:8080

?  Does that break other apps?

**Comment by choyj** [comment]
Nice!  Now I finally know what everpad looks like!

When I open up a new terminal, set https_proxy to http://xxxxx, and run everpad-provider, no error messages.  So then I kick off everpad, and I was able to sync successfully and see my notes.

Does setting the proxy like that break other things?  Not sure, things seem to work ok and most things use the http_proxy.  I tried a wget https://mail.google.com with that setting and it seems to work.  

However, even though it works, it's not something I can change since in Ubuntu 12.10, I can only specify the IP address or DNS name for the proxy (i.e. System Settings -> Network -> Network proxy).  I can't tell the https_proxy to use http instead of https.  Maybe I could do this in /etc/apt/apt.conf, but that would be a kludge.

Thanks for the workaround

**Comment by ghost** [comment]
I had the same issue after upgrading this morning. There's no "About Everpad" that I could find, so I'm not sure what version I was running, or am now. I think there's a command you can run?

What's odd is that I've been using everpad for a few months now, but after the upgrade, my database was empty and it was asking me to "perform first sync". When I chose that, nothing happened.

The fix, for me, was to take my laptop home - where there is no proxy - and perform the sync from there, after turning off my proxy settings (and rebooting because I still had issues even at home, even after turning off the proxy).

It would seem that Everpad doesn't pick up proxy changes for some reason, and while it works through the proxy normally, it can't authorise, or perform the first sync when using a proxy.

**Comment by mferretti** [comment]
Hi
just to confirm (debian jessie): 

env | grep -i proxy
http_proxy=
ftp_proxy=
https_proxy=

everpad-provider --verbose
Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.7/everpad/provider/sync.py", line 454, in run
    self.init_network()
  File "/usr/lib/pymodules/python2.7/everpad/provider/sync.py", line 470, in init_network
    self.note_store = get_note_store(self.auth_token)
  File "/usr/lib/pymodules/python2.7/everpad/provider/tools.py", line 64, in get_note_store
    user_store = get_user_store(auth_token)
  File "/usr/lib/pymodules/python2.7/everpad/provider/tools.py", line 56, in get_user_store
    http_proxy=get_proxy_config(urlparse(user_store_uri).scheme))
  File "/usr/lib/pymodules/python2.7/thrift/transport/THttpClient.py", line 72, in **init**
    raise ValueError("Unsupported Proxy Scheme, %s" % http_proxy.scheme)
ValueError: Unsupported Proxy Scheme, 

I had to unset all of the schemas in order to have the provider start : 
unset https_proxy
unset ftp_proxy
unset http_proxy
everpad-provider --verbose
Notebook Work remote
Notebook Universitá remote
Notebook Personal remote
Tag TODO remote
Tag lavoro remote
Tag IMPORTANT!!! remote
Note todo remote
...

**Comment by PetRose** [comment]
Suggest, since I had somewhat similar, to try starting everpad client:
     everpad --settings
and see if it can bring you further. I had to re-authenticate this, before my everpad-provider were able to start and run.
Cheers
