### ISSUE TITLE
I can't start Everpad - (Api version Mismatch)

### ISSUE THREAD

**Issue by Ardakilic** [nvbn/everpad#215]
Hi,

I have an issue while executing latest (and older versions of) everpad (which was updated today - 2012.01.16). (I'm using ppa sources.) When I execute it it shows on tray, but says "api version mismatch /  restart everpad"

I'm using linux mint 13 (maya) x64 with mate 1.4.2, "gir1.2-notify-0.7" is installed.

This is what I get when I try to execute "everpad" from terminal:

"sni-qt/19998" WARN  12:16:20.001 void StatusNotifierItemFactory::connectToSnw() Invalid interface to SNW_SERVICE 
ERROR:dbus.proxies:Introspect error on :1.4:/EverpadProvider: dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NoReply: Message did not receive a reply (timeout by message bus)

This is what I get when I try to get "everpad-provider" from terminal:

Traceback (most recent call last):
  File "/usr/bin/everpad-provider", line 9, in <module>
    load_entry_point('everpad==2.4dev', 'console_scripts', 'everpad-provider')()
  File "/usr/lib/pymodules/python2.7/everpad/provider/daemon.py", line 93, in main
    app = ProviderApp(args.verbose, sys.argv)
  File "/usr/lib/pymodules/python2.7/everpad/provider/daemon.py", line 33, in **init**
    if get_auth_token():
  File "/usr/lib/pymodules/python2.7/everpad/tools.py", line 57, in get_auth_token
    return keyring.get_password('everpad', 'oauth_token')
  File "/usr/lib/python2.7/dist-packages/keyring/core.py", line 37, in get_password
    return _keyring_backend.get_password(service_name, username)
  File "/usr/lib/python2.7/dist-packages/keyring/backend.py", line 197, in get_password
    _, session = service_iface.OpenSession("plain", "")
  File "/usr/lib/python2.7/dist-packages/dbus/proxies.py", line 145, in __call__
    **keywords)
  File "/usr/lib/python2.7/dist-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.UnknownMethod: Method "OpenSession" with signature "ss" on interface "org.freedesktop.Secret.Service" doesn't exist

This is what I get when I try "everpad-lens" from terminal:

ERROR:dbus.proxies:Introspect error on :1.123:/EverpadProvider: dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NoReply: Message did not receive a reply (timeout by message bus)
ERROR:dbus.proxies:Introspect error on :1.126:/EverpadProvider: dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NoReply: Message did not receive a reply (timeout by message bus)
Traceback (most recent call last):
  File "/usr/bin/everpad-lens", line 9, in <module>
    load_entry_point('everpad==2.4dev', 'console_scripts', 'everpad-lens')()
  File "/usr/lib/pymodules/python2.7/everpad/specific/unity/lens.py", line 152, in main
    run_lens(EverpadLens, sys.argv)
  File "/usr/lib/python2.7/dist-packages/singlet/utils.py", line 45, in run_lens
    lens = lens_class()
  File "/usr/lib/pymodules/python2.7/everpad/specific/unity/lens.py", line 49, in **init**
    self.update_props()
  File "/usr/lib/pymodules/python2.7/everpad/specific/unity/lens.py", line 56, in update_props
    for tag_struct in provider.list_tags():
  File "/usr/lib/pymodules/python2.7/everpad/tools.py", line 31, in wrapper
    return getattr(self.**interface, name)(_args, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/dbus/proxies.py", line 70, in __call**
    return self._proxy_method(_args, *_keywords)
  File "/usr/lib/python2.7/dist-packages/dbus/proxies.py", line 145, in __call__
    **keywords)
  File "/usr/lib/python2.7/dist-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.ServiceUnknown: The name :1.126 was not provided by any .service files

What could be the issue? How can I fix this?

Thanks,

**Comment by nvbn** [comment]
Try to reboot. Error in everpad-provider 2.3.

**Comment by Ardakilic** [comment]
Hi,

After the restart, the issue keeps on happening. It was also same on one older version.

Thanks,

**Comment by nvbn** [comment]
What DE you use?

**Comment by Ardakilic** [comment]
I'm using Mate 1.4.2 as Desktop Environment.

**Comment by blue-bullet** [comment]
I am having the same problem as Ardakilic.  I am using Linux Mint 14 KDE (4.9.4) 64 bit.  Everpad 2.4.

**Comment by dotjorgeu** [comment]
same here Xubuntu 12.04.1 LTS
restarted the whole system several times
still showing the error "api version missmatch, please restart"

A workarround. In a terminal I run  "everpad-provider" then in another terminal session I run "everpad" then it works.
It looks like the main everpad script have problems starting everpad-provider by its own

**Comment by Ardakilic** [comment]
everpad-provider does not start for me, it just dumps an error log at terminal and closes, so dotjorgeu's workaround does not work for me.

This is the report:

Traceback (most recent call last):
  File "/usr/local/bin/everpad-provider", line 9, in <module>
    load_entry_point('everpad==2.3dev', 'console_scripts', 'everpad-provider')()
  File "/usr/local/lib/python2.7/dist-packages/everpad-2.3dev-py2.7.egg/everpad/provider/daemon.py", line 93, in main
    app = ProviderApp(args.verbose, sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/everpad-2.3dev-py2.7.egg/everpad/provider/daemon.py", line 33, in **init**
    if get_auth_token():
  File "/usr/local/lib/python2.7/dist-packages/everpad-2.3dev-py2.7.egg/everpad/tools.py", line 57, in get_auth_token
    return keyring.get_password('everpad', 'oauth_token')
  File "/usr/lib/python2.7/dist-packages/keyring/core.py", line 37, in get_password
    return _keyring_backend.get_password(service_name, username)
  File "/usr/lib/python2.7/dist-packages/keyring/backend.py", line 197, in get_password
    _, session = service_iface.OpenSession("plain", "")
  File "/usr/lib/python2.7/dist-packages/dbus/proxies.py", line 145, in __call__
    **keywords)
  File "/usr/lib/python2.7/dist-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.UnknownMethod: Method "OpenSession" with signature "ss" on interface "org.freedesktop.Secret.Service" doesn't exist

**Comment by nvbn** [comment]
What you see when:

``` bash
everpad --version
everpad-provider -- version
```

?

**Comment by Ardakilic** [comment]
This is the output for both:

Everpad version: 2.4
API version: 2
Schema version: 3

**Comment by nvbn** [comment]
Try to remove everpad package, and all of:

``` bash
find /usr/ -name everpad
```

You have clash of versions.
And install package.

**Comment by Ardakilic** [comment]
There were two folders from git cloning (/usr/local/lib/python2.7/dist-packages/everpad-2.4dev-py2.7.egg/everpad
 and /usr/local/lib/python2.7/dist-packages/everpad-2.3dev-py2.7.egg/everpad), and this one: /usr/local/bin/everpad deleted them all (sudo rm -R /folder), and restarted the machine, installed the everpad again, same issue goes on. --version gives 2.4 for all.

This is very last terminal output of everpad:

"sni-qt/18814" WARN  16:25:08.055 void StatusNotifierItemFactory::connectToSnw() Invalid interface to SNW_SERVICE 
ERROR:dbus.proxies:Introspect error on :1.116:/EverpadProvider: dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NoReply: Message did not receive a reply (timeout by message bus)

and this is the very last output of everpad-provider:

Traceback (most recent call last):
  File "/usr/local/bin/everpad-provider", line 9, in <module>
    load_entry_point('everpad==2.4dev', 'console_scripts', 'everpad-provider')()
  File "/usr/lib/pymodules/python2.7/everpad/provider/daemon.py", line 93, in main
    app = ProviderApp(args.verbose, sys.argv)
  File "/usr/lib/pymodules/python2.7/everpad/provider/daemon.py", line 33, in **init**
    if get_auth_token():
  File "/usr/lib/pymodules/python2.7/everpad/tools.py", line 57, in get_auth_token
    return keyring.get_password('everpad', 'oauth_token')
  File "/usr/lib/python2.7/dist-packages/keyring/core.py", line 37, in get_password
    return _keyring_backend.get_password(service_name, username)
  File "/usr/lib/python2.7/dist-packages/keyring/backend.py", line 197, in get_password
    _, session = service_iface.OpenSession("plain", "")
  File "/usr/lib/python2.7/dist-packages/dbus/proxies.py", line 145, in __call__
    **keywords)
  File "/usr/lib/python2.7/dist-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.UnknownMethod: Method "OpenSession" with signature "ss" on interface "org.freedesktop.Secret.Service" doesn't exist

And this is the very last output of everpad-lens:

ERROR:dbus.proxies:Introspect error on :1.134:/EverpadProvider: dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NoReply: Message did not receive a reply (timeout by message bus)
ERROR:dbus.proxies:Introspect error on :1.137:/EverpadProvider: dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NoReply: Message did not receive a reply (timeout by message bus)
Traceback (most recent call last):
  File "/usr/local/bin/everpad-lens", line 9, in <module>
    load_entry_point('everpad==2.4dev', 'console_scripts', 'everpad-lens')()
  File "/usr/lib/pymodules/python2.7/everpad/specific/unity/lens.py", line 152, in main
    run_lens(EverpadLens, sys.argv)
  File "/usr/lib/python2.7/dist-packages/singlet/utils.py", line 45, in run_lens
    lens = lens_class()
  File "/usr/lib/pymodules/python2.7/everpad/specific/unity/lens.py", line 49, in **init**
    self.update_props()
  File "/usr/lib/pymodules/python2.7/everpad/specific/unity/lens.py", line 56, in update_props
    for tag_struct in provider.list_tags():
  File "/usr/lib/pymodules/python2.7/everpad/tools.py", line 31, in wrapper
    return getattr(self.**interface, name)(_args, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/dbus/proxies.py", line 70, in __call**
    return self._proxy_method(_args, *_keywords)
  File "/usr/lib/python2.7/dist-packages/dbus/proxies.py", line 145, in __call__
    **keywords)
  File "/usr/lib/python2.7/dist-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.ServiceUnknown: The name :1.137 was not provided by any .service files

Thanks for the interest

**Comment by blue-bullet** [comment]
Try to remove everpad package, and all of:

find /usr/ -name everpad
You have clash of versions.
And install package.

I removed everpad via synaptic (complete removal).  Issuing 'find /usr/ -name everpad'  in terminal returned nothing.  Reinstalled everpad 2.4 via synaptic and still get same output as Ardakilic:

Everpad version: 2.4
API version: 2
Schema version: 3

How do I avoid the conflict of versions?

**Comment by kiweegie** [comment]
Same issue here on Mint 14 Cinnamon 64 bit, installed via ppa

Everpad version: 2.4
API version: 2
Schema version: 3

Installed fine and _was_ working but now doesn't show in panel. Running "everpad" command from terminal results in nothing. Running "everpad-provider" from terminal gives:

Traceback (most recent call last):
  File "/usr/bin/everpad-provider", line 9, in <module>
    load_entry_point('everpad==2.4dev', 'console_scripts', 'everpad-provider')()
  File "/usr/lib/pymodules/python2.7/everpad/provider/daemon.py", line 93, in main
    app = ProviderApp(args.verbose, sys.argv)
  File "/usr/lib/pymodules/python2.7/everpad/provider/daemon.py", line 33, in **init**
    if get_auth_token():
  File "/usr/lib/pymodules/python2.7/everpad/tools.py", line 57, in get_auth_token
    return keyring.get_password('everpad', 'oauth_token')
  File "/usr/lib/python2.7/dist-packages/keyring/core.py", line 37, in get_password
    return _keyring_backend.get_password(service_name, username)
  File "/usr/lib/python2.7/dist-packages/keyring/backend.py", line 144, in get_password
    items = gnomekeyring.find_network_password_sync(username, service)
gnomekeyring.IOError

Attempting  dotjorgeu's workaround of launching everpad in 2nd terminal results in

"sni-qt/6589" WARN  23:30:31.958 void StatusNotifierItemFactory::connectToSnw() Invalid interface to SNW_SERVICE 
ERROR:dbus.proxies:Introspect error on :1.6:/EverpadProvider: dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NoReply: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.

**Comment by dnedbaylo** [comment]
When using Mate, make sure you have disabled all gnome related items in Startup Applications. Specifically keyring daemon. Both running gnome-keyring-daemon and mate-keyring-daemon result in conflict. I had the same issue in Mint Maya x64. After I disabled gnome-keyring-daemon startup everything works just fine. See https://bugs.launchpad.net/linuxmint/+bug/1005635

**Comment by jessbk** [comment]
Also can't start everpad-provider.

Mint 14 Mate

$ everpad-provider --version
Everpad version: 2.5
API version: 6
Schema version: 5

$ everpad-provider 
Traceback (most recent call last):
  File "/usr/bin/everpad-provider", line 9, in <module>
    load_entry_point('everpad==2.5dev', 'console_scripts', 'everpad-provider')()
  File "/usr/lib/pymodules/python2.7/everpad/provider/daemon.py", line 95, in main
    app = ProviderApp(args.verbose, sys.argv)
  File "/usr/lib/pymodules/python2.7/everpad/provider/daemon.py", line 34, in **init**
    if get_auth_token():
  File "/usr/lib/pymodules/python2.7/everpad/provider/tools.py", line 35, in get_auth_token
    return get_keyring().get_password('everpad', 'oauth_token')
  File "/usr/lib/python2.7/dist-packages/keyring/core.py", line 37, in get_password
    return _keyring_backend.get_password(service_name, username)
  File "/usr/lib/python2.7/dist-packages/keyring/backend.py", line 197, in get_password
    _, session = service_iface.OpenSession("plain", "")
  File "/usr/lib/python2.7/dist-packages/dbus/proxies.py", line 145, in __call__
    **keywords)
  File "/usr/lib/python2.7/dist-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.UnknownMethod: Method "OpenSession" with signature "ss" on interface "org.freedesktop.Secret.Service" doesn't exist

**Comment by azlk** [comment]
Everpad doesn't start...

Mint 14 Mate 64bit

$ everpad --version
Everpad version: 2.5
API version: 6
Schema version: 5

$ everpad-provider --version
Everpad version: 2.5
API version: 6
Schema version: 5

ERROR:dbus.proxies:Introspect error on /EverpadProvider: dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NoReply: Message did not receive a reply (timeout by message bus) 1

All gnome related items in Startup Applications are disabled.
What I did: reboot, re-logon, removed "everpad package, and all of: find /usr/ -name everpad", reinstalled package (from ppa)

**Comment by imanbee** [comment]
Have the same problem as below. Ubuntu 12.10. I have installed Everpad from scratch.

$ everpad --version
Everpad version: 2.5
API version: 6
Schema version: 5
$ everpad-provider --version
Everpad version: 2.5
API version: 6
Schema version: 5

**Comment by marcoconstancio** [comment]
Recently reinstalled linux mint 14 mate edition, and it has only mate-keyring-daemon and still gave this error, but after installing gnome-keyring-daemon it works.

I have:

$ everpad --version
Everpad version: 2.5
API version: 6
Schema version: 5
$ everpad-provider --version
Everpad version: 2.5
API version: 6
Schema version: 5

and the daemons running with the following parameters:
/usr/bin/gnome-keyring-daemon --daemonize --login
mate-keyring-daemon --start --components=gpg

**Comment by gviertel** [comment]
Same issue here in a Ubuntu 14.04.1 LTS clean installation

uname -a

Linux HAL 3.13.0-32-generic #57-Ubuntu SMP Tue Jul 15 03:51:08 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

root@HAL:~# apt-get install everpad
Reading package lists... Done
Building dependency tree  
Reading state information... Done
The following NEW packages will be installed:
  everpad
0 upgraded, 1 newly installed, 0 to remove and 1 not upgraded.
Need to get 162 kB of archives.
After this operation, 1.887 kB of additional disk space will be used.
Get:1 http://ppa.launchpad.net/nvbn-rm/ppa/ubuntu/ trusty/main everpad amd64 2.15.8-0~trusty [162 kB]
Fetched 162 kB in 1s (134 kB/s)  
Selecting previously unselected package everpad.
(Reading database ... 234552 files and directories currently installed.)
Preparing to unpack .../everpad_2.15.8-0~trusty_amd64.deb ...
Unpacking everpad (2.15.8-0~trusty) ...
Processing triggers for hicolor-icon-theme (0.13-1) ...
Processing triggers for gnome-menus (3.10.1-0ubuntu2) ...
Processing triggers for desktop-file-utils (0.22-1ubuntu1) ...
Processing triggers for bamfdaemon (0.5.1+14.04.20140409-0ubuntu1) ...
Rebuilding /usr/share/applications/bamf-2.index...
Processing triggers for mime-support (3.54ubuntu1) ...
Setting up everpad (2.15.8-0~trusty) ...
Processing triggers for python-support (1.0.15) ...

root@HAL:~# everpad --version
Everpad version: 2.5
API version: 6
Schema version: 5

root@HAL:~# everpad-provider --version
Everpad version: 2.5
API version: 6
Schema version: 5

The first time show this warning

root@HAL:~# everpad
"sni-qt/22274" WARN  04:33:58.999 void StatusNotifierItemFactory::connectToSnw() Invalid interface to SNW_SERVICE 

and ask the password to unlock the keyring but after that is doing nothing 

If the socket is busy i got this message

^C
root@HAL:~# everpad
"sni-qt/22326" WARN  04:35:01.535 void StatusNotifierItemFactory::connectToSnw() Invalid interface to SNW_SERVICE 
Traceback (most recent call last):
  File "/usr/bin/everpad", line 9, in <module>
    load_entry_point('everpad==2.5dev', 'gui_scripts', 'everpad')()
  File "/usr/lib/pymodules/python2.7/everpad/pad/indicator.py", line 294, in main
    session_bus = dbus.SessionBus()
  File "/usr/lib/python2.7/dist-packages/dbus/_dbus.py", line 211, in __new__
    mainloop=mainloop)
  File "/usr/lib/python2.7/dist-packages/dbus/_dbus.py", line 100, in __new__
    bus = BusConnection.**new**(subclass, bus_type, mainloop=mainloop)
  File "/usr/lib/python2.7/dist-packages/dbus/bus.py", line 122, in **new**
    bus = cls._new_for_bus(address_or_type, mainloop=mainloop)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NoServer: Failed to connect to socket /tmp/dbus-9itADtDXAw: Connection refused

**Comment by faiwer** [comment]
Linux Mint, 64bit. Can't start

```
faiwer@faiwer-mint ~ $ everpad-provider 
Traceback (most recent call last):
    File "/usr/bin/everpad-provider", line 9, in <module>
        load_entry_point('everpad==2.5dev', 'console_scripts', 'everpad-provider')()
    File "/usr/lib/pymodules/python2.7/everpad/provider/daemon.py", line 95, in main
        app = ProviderApp(args.verbose, sys.argv)
    File "/usr/lib/pymodules/python2.7/everpad/provider/daemon.py", line 34, in __init__
        if get_auth_token():
    File "/usr/lib/pymodules/python2.7/everpad/provider/tools.py", line 35, in get_auth_token
        return get_keyring().get_password('everpad', 'oauth_token')
    File "/usr/lib/python2.7/dist-packages/keyring/core.py", line 37, in get_password
        return _keyring_backend.get_password(service_name, username)
    File "/usr/lib/python2.7/dist-packages/keyring/backend.py", line 197, in get_password
        _, session = service_iface.OpenSession("plain", "")
    File "/usr/lib/python2.7/dist-packages/dbus/proxies.py", line 145, in __call__
        **keywords)
    File "/usr/lib/python2.7/dist-packages/dbus/connection.py", line 651, in call_blocking
        message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.UnknownMethod: Method "OpenSession" with signature "ss" on interface "org.freedesktop.Secret.Service" doesn't exist
```

**Comment by prathyks** [comment]
Facing same error with Gnome Ubuntu 14.04. Built from source.

**Comment by mustafaascha** [comment]
Also facing the same error, with Gnome and Ubuntu 15.04. Installed using the ppa repo.

**Comment by mflu** [comment]
also facing this issue in Ubuntu 15.10 (built from soruce code)

**Comment by lukruh** [comment]
same issue on arch+ xfce
(gnome-keyring installed)

I found the same "workaround" like dotjorgeu. In a second terminal i can start everpad but just the window appears. I cant log in or do any other interactions with this window. So it's a not working "workaround"

Anybody got a solution right now?
