### ISSUE TITLE
Can't get Everpad to complete first sync

### ISSUE THREAD

**Issue by nicknefarious** [nvbn/everpad#235]
I am using Ubuntu 12.04 64bit and your standard PPA

What I did:- Authorised with Evernote. Started sync. Says first sync is underway but never finishes. A day or two ago it did sync some stuff but I have had it open for hours on end where it was supposed to be syncing and nothing happened. I tried de-authorising then re-authorising, no difference. Here is the verbose output for neverpad-provider. The other two (neverpad and neverpad-lens) said nothing. I also tried re-setting the Proxy Server to "none" in Network -> Network Proxy -> Method and then choosing "Apply System Wide" retried running neverpad-provider with verbose same result. Rebooted and retried neverpad-provider with verbose same result again.

XXXX:~$ everpad-provider --verbose
Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.7/everpad/provider/sync.py", line 365, in run
    self.perform()
  File "/usr/lib/pymodules/python2.7/everpad/provider/sync.py", line 398, in perform
    self.all_notes = list(self._iter_all_notes())
  File "/usr/lib/pymodules/python2.7/everpad/provider/sync.py", line 51, in _iter_all_notes
    ), offset, EDAM_USER_NOTES_MAX)
  File "/usr/lib/pymodules/python2.7/evernote/edam/notestore/NoteStore.py", line 3877, in findNotes
    self.send_findNotes(authenticationToken, filter, offset, maxNotes)
  File "/usr/lib/pymodules/python2.7/evernote/edam/notestore/NoteStore.py", line 3889, in send_findNotes
    self._oprot.trans.flush()
  File "/usr/lib/pymodules/python2.7/thrift/transport/THttpClient.py", line 124, in _f
    result = f(_args, *_kwargs)
  File "/usr/lib/pymodules/python2.7/thrift/transport/THttpClient.py", line 163, in flush
    self.__http.endheaders()
  File "/usr/lib/python2.7/httplib.py", line 954, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 814, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 776, in send
    self.connect()
  File "/usr/lib/pymodules/python2.7/thrift/transport/httpslib.py", line 35, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 571, in create_connection
    raise err
socket.error: [Errno 110] Connection timed out

**Comment by mlapointe** [comment]
I've had a similar problem running 12.10 64-bit. First sync took forever, then it started working great for a few days. Now it is stuck "Sync in Progress" for a single text note.

Will sync fine after `killall everpad-provider` but not after exiting the program and restarting it

**Comment by nicknefarious** [comment]
I have left it on and open over a few nights now but it still hasn't completely synced all my notes. Sometimes the sync stops as if it has legitimately finished but it has still only synced maybe half of my notes, sometimes I poen it and it has less notes than before, sometimes more. It seems to be constantly "Sync in Progress" now. For me it has never worked great at all...
