### ISSUE TITLE
Everpad crashes when trying to delete "alternate versions"

### ISSUE THREAD

**Issue by bullpup** [nvbn/everpad#247]
When I try do delelte an "alternate version" the following error occurs, and everpad hangs:

Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.7/everpad/pad/indicator.py", line 77, in update
    20, Note.ORDER_UPDATED_DESC, 1,
  File "/usr/lib/pymodules/python2.7/everpad/tools.py", line 31, in wrapper
    return getattr(self.**interface, name)(_args, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/dbus/proxies.py", line 70, in __call**
    return self._proxy_method(_args, *_keywords)
  File "/usr/lib/python2.7/dist-packages/dbus/proxies.py", line 145, in __call__
    *_keywords)
  File "/usr/lib/python2.7/dist-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Python.sqlalchemy.exc.InvalidRequestError: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/dbus/service.py", line 707, in _message_cb
    retval = candidate_method(self, *args, *_keywords)
  File "/usr/lib/pymodules/python2.7/everpad/provider/service.py", line 111, in find_notes
    return map(lambda note: btype.Note.from_obj(note).struct, qs.all())
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2115, in all
    return list(self)
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2227, in **iter**
    return self._execute_and_instances(context)
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2240, in _execute_and_instances
    close_with_result=True)
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2231, in _connection_from_session
    **kw)
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 730, in connection
    close_with_result=close_with_result)
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 734, in _connection_for_bind
    return self.transaction._connection_for_bind(engine)
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 250, in _connection_for_bind
    self._assert_is_active()
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 174, in _assert_is_active
    % self._rollback_exception
InvalidRequestError: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: Circular dependency detected. Cycles: set([ProcessState(OneToManyDP(Note.conflict_parent), <Note at 0x321a7d0>, delete=False), SaveUpdateState(<Note at 0x321a7d0>), ProcessState(OneToManyDP(Note.conflict_parent), <Note at 0x321ad10>, delete=False), SaveUpdateState(<Note at 0x321ad10>)]) all edges: set([(SaveUpdateState(<Note at 0x321ad10>), DeleteAll(Mapper|Notebook|notebooks)), (ProcessState(OneToManyDP(Note.conflict_parent), <Note at 0x321ad10>, delete=False), SaveUpdateState(<Note at 0x321ad10>)), (SaveUpdateState(<Note at 0x321ad10>), SaveUpdateState(<Note at 0x321ad10>)), (ProcessState(OneToManyDP(Note.conflict_parent), <Note at 0x321ad10>, delete=False), SaveUpdateState(<Note at 0x321a7d0>)), (ProcessState(OneToManyDP(Note.conflict_parent), <Note at 0x321a7d0>, delete=False), SaveUpdateState(<Note at 0x321ad10>)), (ProcessState(ManyToOneDP(Note.notebook), <Note at 0x321a7d0>, delete=False), SaveUpdateState(<Note at 0x321a7d0>)), (SaveUpdateAll(Mapper|Notebook|notebooks), ProcessState(ManyToOneDP(Note.notebook), <Note at 0x321ad10>, delete=False)), (SaveUpdateAll(Mapper|Notebook|notebooks), ProcessState(ManyToOneDP(Note.notebook), <Note at 0x321a7d0>, delete=False)), (ProcessState(ManyToOneDP(Note.notebook), <Note at 0x321ad10>, delete=False), SaveUpdateState(<Note at 0x321ad10>)), (SaveUpdateState(<Note at 0x321ad10>), SaveUpdateState(<Note at 0x321a7d0>)), (ProcessState(OneToManyDP(Note.conflict_parent), <Note at 0x321a7d0>, delete=False), SaveUpdateState(<Note at 0x321a7d0>)), (SaveUpdateState(<Note at 0x321a7d0>), ProcessState(OneToManyDP(Note.conflict_parent), <Note at 0x321a7d0>, delete=False)), (SaveUpdateState(<Note at 0x321ad10>), ProcessState(OneToManyDP(Note.conflict_parent), <Note at 0x321ad10>, delete=False)), (SaveUpdateState(<Note at 0x321a7d0>), DeleteAll(Mapper|Notebook|notebooks)), (SaveUpdateState(<Note at 0x321a7d0>), SaveUpdateState(<Note at 0x321ad10>)), (SaveUpdateState(<Note at 0x321a7d0>), SaveUpdateState(<Note at 0x321a7d0>))])

**Comment by OriginalPenguin** [comment]
I have this problem too.

**Comment by acmzero** [comment]
What DE are you using? i'm in KDE and have the same problem. now is solved by installing gnome-keyring daemon.
Hope this can help you.

**Comment by OriginalPenguin** [comment]
I'm using KDE as well (on Ubuntu 12.10). So that's probably the issue. 

In the meantime I've switched to running the official Windows 7 Evernote under Linux using wine (which works surprisingly well). Now that I know I need to install gnome-keyring daemon maybe I'll switch back sometime.

**Comment by bullpup** [comment]
I use Linux Mint with Cinnamon. Switched to Nixnote in the meantime.

**Comment by luisdavim** [comment]
Is there a way to delete all the alternative versions? A script maybe? How do alternative versions get created? I got notes with hundreds of alternative versions that I don't want...

**Comment by e2jk** [comment]
@weismannweb provided a way to deleta all alternative versions in [#340](https://github.com/nvbn/everpad/issues/340#issuecomment-24025403).
