### ISSUE TITLE
Everpad not starting on Ubuntu 12.04 amd64, Gnome Shell

### ISSUE THREAD

**Issue by shanttu** [nvbn/everpad#248]
Everpad not starting on boot. After killing and launching from terminal I get the following:

everpad u%
ERROR:dbus.proxies:Introspect error on :1.213:/EverpadService: dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NoReply: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.
ERROR:dbus.proxies:Introspect error on :1.213:/EverpadService: dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NoReply: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.
Traceback (most recent call last):
  File "/usr/bin/everpad", line 9, in <module>
    load_entry_point('everpad==2.4dev', 'gui_scripts', 'everpad')()
  File "/usr/lib/pymodules/python2.7/everpad/pad/indicator.py", line 313, in main
    pad.create_wit_attach(args.attach)
  File "/usr/lib/pymodules/python2.7/everpad/tools.py", line 31, in wrapper
    return getattr(self.**interface, name)(_args, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/dbus/proxies.py", line 70, in __call**
    return self._proxy_method(_args, *_keywords)
  File "/usr/lib/python2.7/dist-packages/dbus/proxies.py", line 145, in __call__
    **keywords)
  File "/usr/lib/python2.7/dist-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NoReply: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.

**Comment by Aporie** [comment]
Hi, 

Similar issue on fedora 18 with gnome shell: 

Traceback (most recent call last):
  File "/usr/bin/everpad", line 9, in <module>
    load_entry_point('everpad==2.4dev', 'gui_scripts', 'everpad')()
  File "/usr/lib/python2.7/site-packages/everpad-2.4dev-py2.7.egg/everpad/pad/indicator.py", line 282, in main
    app.provider = get_provider(session_bus)
  File "/usr/lib/python2.7/site-packages/everpad-2.4dev-py2.7.egg/everpad/tools.py", line 39, in wrapper
    return InterfaceWrapper(partial(fnc, _args, *_kwrags))
  File "/usr/lib/python2.7/site-packages/everpad-2.4dev-py2.7.egg/everpad/tools.py", line 15, in **init**
    self.**load()
  File "/usr/lib/python2.7/site-packages/everpad-2.4dev-py2.7.egg/everpad/tools.py", line 18, in __load
    self.__interface = self.__get()
  File "/usr/lib/python2.7/site-packages/everpad-2.4dev-py2.7.egg/everpad/tools.py", line 47, in get_provider
    provider = bus.get_object("com.everpad.Provider", '/EverpadProvider')
  File "/usr/lib/python2.7/site-packages/dbus/bus.py", line 241, in get_object
    follow_name_owner_changes=follow_name_owner_changes)
  File "/usr/lib/python2.7/site-packages/dbus/proxies.py", line 248, in __init**
    self._named_service = conn.activate_name_owner(bus_name)
  File "/usr/lib/python2.7/site-packages/dbus/bus.py", line 180, in activate_name_owner
    self.start_service_by_name(bus_name)
  File "/usr/lib/python2.7/site-packages/dbus/bus.py", line 278, in start_service_by_name
    'su', (bus_name, flags)))
  File "/usr/lib/python2.7/site-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.ServiceUnknown: The name com.everpad.Provider was not provided by any .service files

**Comment by shanttu** [comment]
I'm happy with dirty scripting on boot. Start, wait, kill and restart.

**Comment by Aporie** [comment]
And so what ? Does it works ?

**Comment by biji** [comment]
edit your command of startup application to this: bash -c "sleep 30; everpad"

**Comment by Aporie** [comment]
[Aporie@Aporie-laptop everpad]$ bash -c "sleep 30; everpad"
Traceback (most recent call last):
  File "/usr/bin/everpad", line 9, in <module>
    load_entry_point('everpad==2.4dev', 'gui_scripts', 'everpad')()
  File "/usr/lib/python2.7/site-packages/everpad-2.4dev-py2.7.egg/everpad/pad/indicator.py", line 282, in main
    app.provider = get_provider(session_bus)
  File "/usr/lib/python2.7/site-packages/everpad-2.4dev-py2.7.egg/everpad/tools.py", line 39, in wrapper
    return InterfaceWrapper(partial(fnc, _args, *_kwrags))
  File "/usr/lib/python2.7/site-packages/everpad-2.4dev-py2.7.egg/everpad/tools.py", line 15, in **init**
    self.**load()
  File "/usr/lib/python2.7/site-packages/everpad-2.4dev-py2.7.egg/everpad/tools.py", line 18, in __load
    self.__interface = self.__get()
  File "/usr/lib/python2.7/site-packages/everpad-2.4dev-py2.7.egg/everpad/tools.py", line 47, in get_provider
    provider = bus.get_object("com.everpad.Provider", '/EverpadProvider')
  File "/usr/lib/python2.7/site-packages/dbus/bus.py", line 241, in get_object
    follow_name_owner_changes=follow_name_owner_changes)
  File "/usr/lib/python2.7/site-packages/dbus/proxies.py", line 248, in __init**
    self._named_service = conn.activate_name_owner(bus_name)
  File "/usr/lib/python2.7/site-packages/dbus/bus.py", line 180, in activate_name_owner
    self.start_service_by_name(bus_name)
  File "/usr/lib/python2.7/site-packages/dbus/bus.py", line 278, in start_service_by_name
    'su', (bus_name, flags)))
  File "/usr/lib/python2.7/site-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.ServiceUnknown: The name com.everpad.Provider was not provided by any .service files

Seems to be the same ...
