### ISSUE TITLE
Note list appears blank

### ISSUE THREAD

**Issue by ghing** [nvbn/everpad#249]
When I start the application, the Everpad icon appears in the tray in the upper-right-hand corner of my screen, but clicking on it shows a completely empty list.  There are no entries, either for notes or for program options).

When I run the application in the shell, this error message appears:

```
Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.7/everpad/pad/indicator.py", line 82, in update
    20 - len(pin_notes), Note.ORDER_UPDATED_DESC, 0,
  File "/usr/lib/pymodules/python2.7/everpad/tools.py", line 31, in wrapper
    return getattr(self.__interface, name)(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/dbus/proxies.py", line 70, in __call__
    return self._proxy_method(*args, **keywords)
  File "/usr/lib/python2.7/dist-packages/dbus/proxies.py", line 145, in __call__
    **keywords)
  File "/usr/lib/python2.7/dist-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Python.TypeError: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/dbus/service.py", line 751, in _message_cb
    _method_reply_return(connection, message, method_name, signature, *retval)
  File "/usr/lib/python2.7/dist-packages/dbus/service.py", line 254, in _method_reply_return
    reply.append(signature=signature, *retval)
TypeError: an integer is required
```

**Comment by boeboe** [comment]
It seems that many people have 'TypeError: an integer is required' 
Maybe you should try to fix this bug...

ERROR:dbus.connection:Unable to set arguments ((dbus.Int32(5), u'AllJoyn', u'New note content', dbus.Int64(1369433120193L), dbus.Int64(1369433120193L), None, dbus.Array([u''], signature=dbus.Signature('s')), dbus.String(u''), False, dbus.Int32(0), dbus.Array([], signature=dbus.Signature('i')), dbus.Int64(0L), dbus.String(u'')),) according to signature u'(issxxiassbiaixs)': <type 'exceptions.TypeError'>: an integer is required
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/everpad-2.5dev-py2.7.egg/everpad/pad/editor/**init**.py", line 181, in save
    self.app.provider.update_note(self.note.struct)
  File "/usr/local/lib/python2.7/dist-packages/everpad-2.5dev-py2.7.egg/everpad/tools.py", line 29, in wrapper
    return fnc(_args, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/dbus/proxies.py", line 145, in **call**
    *_keywords)
  File "/usr/lib/python2.7/dist-packages/dbus/connection.py", line 641, in call_blocking
    message.append(signature=signature, *args)
TypeError: an integer is required
ERROR:dbus.connection:Unable to set arguments ((dbus.Int32(6), u'AllJoyn', u'New note content', dbus.Int64(1369433137449L), dbus.Int64(1369433137449L), None, dbus.Array([u''], signature=dbus.Signature('s')), dbus.String(u''), False, dbus.Int32(0), dbus.Array([], signature=dbus.Signature('i')), dbus.Int64(0L), dbus.String(u'')),) according to signature u'(issxxiassbiaixs)': <type 'exceptions.TypeError'>: an integer is required
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/everpad-2.5dev-py2.7.egg/everpad/pad/editor/**init**.py", line 181, in save
    self.app.provider.update_note(self.note.struct)
  File "/usr/local/lib/python2.7/dist-packages/everpad-2.5dev-py2.7.egg/everpad/tools.py", line 29, in wrapper
    return fnc(_args, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/dbus/proxies.py", line 145, in **call**
    *_keywords)
  File "/usr/lib/python2.7/dist-packages/dbus/connection.py", line 641, in call_blocking
    message.append(signature=signature, *args)
TypeError: an integer is required
