### ISSUE TITLE
Ubuntu 12.10 64 bit fails to launch

### ISSUE THREAD

**Issue by jwogrady** [nvbn/everpad#250]
Can't get the application to launch in Ubuntu 12.10 64 bit.  Clicking the icon in Unity does not appear to do anything.  Launching from the command line produces the following errors with traceback.

john@john-Ideapad-Z460:~$ everpad OPEN
Traceback (most recent call last):
  File "/usr/bin/everpad", line 9, in <module>
    load_entry_point('everpad==2.4dev', 'gui_scripts', 'everpad')()
  File "/usr/lib/pymodules/python2.7/everpad/pad/indicator.py", line 313, in main
    pad.create_wit_attach(args.attach)
  File "/usr/lib/pymodules/python2.7/everpad/tools.py", line 31, in wrapper
    return getattr(self.**interface, name)(_args, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/dbus/proxies.py", line 70, in __call**
    return self._proxy_method(_args, *_keywords)
  File "/usr/lib/python2.7/dist-packages/dbus/proxies.py", line 145, in __call__
    *_keywords)
  File "/usr/lib/python2.7/dist-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Python.sqlalchemy.orm.exc.NoResultFound: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/dbus/service.py", line 707, in _message_cb
    retval = candidate_method(self, *args, *_keywords)
  File "/usr/lib/pymodules/python2.7/everpad/provider/service.py", line 263, in create_note
    dbus_note.give_to_obj(note)
  File "/usr/lib/pymodules/python2.7/everpad/basetypes.py", line 53, in give_to_obj
    setattr(obj, field[0] + '_dbus', val)
  File "/usr/lib/pymodules/python2.7/everpad/provider/models.py", line 89, in notebook_dbus
    Notebook.default == True,
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2190, in one
    raise orm_exc.NoResultFound("No row was found for one()")
NoResultFound: No row was found for one()

john@john-Ideapad-Z460:~$

**Comment by jwogrady** [comment]
Is anyone running successfully on Ubuntu 12.10 64, or is it just me?

**Comment by rezashamdani** [comment]
mine not work also :(

**Comment by wagafo** [comment]
I have the same problem, and "everpad OPEN" from the command line gives the same error as reported by jwogrady

**Comment by nvbn** [comment]
Are you use third-party ppa?

**Comment by wagafo** [comment]
Yes, I'm using 

 ppa:nvbn-rm/ppa

**Comment by jwogrady** [comment]
Me too.

John

Sent from my iPhone

On Feb 25, 2013, at 9:52 PM, wagafo notifications@github.com wrote:

Yes, I'm using

ppa:nvbn-rm/ppa

—
Reply to this email directly or view it on
GitHubhttps://github.com/nvbn/everpad/issues/250#issuecomment-14046304.

**Comment by wagafo** [comment]
I'm behind a proxy, but I have all the right parameters in the network system settings and the proxy is working well with other applications.

**Comment by nvbn** [comment]
Why you enter "everpad OPEN"?
For starting everpad from terminal you need:

```
everpad
```
