### ISSUE TITLE
Alternative versions of note with unicode title -> crash with TypeError

### ISSUE THREAD

**Issue by slawekmikula** [nvbn/everpad#254]
Version: ubuntu:ppa 2.4.0~quantal

I've created notes with title with polish accented characters eg. "Nadrzędna notatka". When saving a note somehow was created alternative version of the note. I was installing everpad, evernote on android phone, and evernote app on windows machine and syncing many times. Nonetheless now there is an error with alternative versions of the note. I've changed the primary note title to text without accented characters, but when saving notes, syncing i've got crash with the following error. 
 The cause is connected with the incorrect parsing of the accented title of the note. I've removed the formatting text in the code and the error does not show anymore.

Traceback:
--- CUT ---
Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.7/everpad/pad/editor/**init**.py", line 74, in init_alternatives
    ), conflicts,
TypeError: not all arguments converted during string formatting
Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.7/everpad/pad/editor/**init**.py", line 74, in init_alternatives
    ), conflicts,
TypeError: not all arguments converted during string formatting

**Comment by slawekmikula** [comment]
sorry to ask, but closed because of what ? Is it resolved ? It not exists ? Insufficient data in bug report ?
