### ISSUE TITLE
Kubuntu quantal 64bit nothing happens

### ISSUE THREAD

**Issue by MAWSpitau** [nvbn/everpad#258]
Starting everpad brings me:

----- schnipp ------
everpad                                                                                                                                                                                       ~
Fontconfig warning: "/etc/fonts/conf.d/50-user.conf", line 9: reading configurations from ~/.fonts.conf is deprecated.
Qt: Session management error: Could not open network socket
"sni-qt/29090" WARN  08:53:35.134 void StatusNotifierItemFactory::connectToSnw() Invalid interface to SNW_SERVICE 
Traceback (most recent call last):
  File "/usr/bin/everpad", line 9, in <module>
    load_entry_point('everpad==2.4dev', 'gui_scripts', 'everpad')()
  File "/usr/lib/pymodules/python2.7/everpad/pad/indicator.py", line 278, in main
    session_bus = dbus.SessionBus()
  File "/usr/lib/python2.7/dist-packages/dbus/_dbus.py", line 211, in __new__
    mainloop=mainloop)
  File "/usr/lib/python2.7/dist-packages/dbus/_dbus.py", line 100, in __new__
    bus = BusConnection.**new**(subclass, bus_type, mainloop=mainloop)
  File "/usr/lib/python2.7/dist-packages/dbus/bus.py", line 122, in **new**
    bus = cls._new_for_bus(address_or_type, mainloop=mainloop)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NoServer: Failed to connect to socket /tmp/dbus-KqGJFTEyzy: Verbindungsaufbau abgelehnt
----- schnapp ------ 

evernoteprovider --verbose
----- schnipp ------
everpad-provider --verbose                                                                                                                                                                    ~
Fontconfig warning: "/etc/fonts/conf.d/50-user.conf", line 9: reading configurations from ~/.fonts.conf is deprecated.
Qt: Session management error: Could not open network socket
Traceback (most recent call last):
  File "/usr/bin/everpad-provider", line 9, in <module>
    load_entry_point('everpad==2.4dev', 'console_scripts', 'everpad-provider')()
  File "/usr/lib/pymodules/python2.7/everpad/provider/daemon.py", line 93, in main
    app = ProviderApp(args.verbose, sys.argv)
  File "/usr/lib/pymodules/python2.7/everpad/provider/daemon.py", line 23, in **init**
    session_bus = dbus.SessionBus()
  File "/usr/lib/python2.7/dist-packages/dbus/_dbus.py", line 211, in __new__
    mainloop=mainloop)
  File "/usr/lib/python2.7/dist-packages/dbus/_dbus.py", line 100, in __new__
    bus = BusConnection.**new**(subclass, bus_type, mainloop=mainloop)
  File "/usr/lib/python2.7/dist-packages/dbus/bus.py", line 122, in **new**
    bus = cls._new_for_bus(address_or_type, mainloop=mainloop)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NoServer: Failed to connect to socket /tmp/dbus-KqGJFTEyzy: Verbindungsaufbau abgelehnt
----- schnapp ------ 

The gui in the taskbar just gives me "settings and management" and "Exit".
I tried to authorize several times. Deleted all files in ~ according to everpad. Purged and reinstalled from ppa several times. 

Everpad ist not working. That is sad :(

What can I do?

**Comment by nvbn** [comment]
What version of qt and pyside you have installed?
Are you use any third-party repositories?

**Comment by MAWSpitau** [comment]
Hello,

for respositories take a look at the screenshot.

QT4 is installed

And I have no idea how to get the version of pyside.

Marcel

Sent with Cloudy for
Gmailhttps://chrome.google.com/webstore/detail/cloudy-for-gmail/fcfnjfpcmnoabmbhponbioedjceaddaa?utm_source=gmail&utm_medium=email&utm_campaign=gmail_signature

2013/2/20 Vladimir Iakovlev notifications@github.com

> What version of qt and pyside you have installed?
> Are you use any third-party repositories?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/nvbn/everpad/issues/258#issuecomment-13812907.

## 

http://blog.spitau.de
Lehrer, Querdenker und Medienjunkie

about.me/spitaumarcel

**Comment by rosshadden** [comment]
In Python somewhere (like the REPL or a script), you can do this to get the version:

``` python
import PySide, PySide.QtCore
PySide.__version__           # PySide version
PySide.QtCore.__version__    # Qt version
```
