### ISSUE TITLE
Ubuntu 12.10 Everpad bug

### ISSUE THREAD

**Issue by laxman20** [nvbn/everpad#260]
I can't see any options in the applet in the top right corner, and when I run everpad through the terminal, I get this error:

Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.7/everpad/pad/indicator.py", line 82, in update
    20 - len(pin_notes), Note.ORDER_UPDATED_DESC, 0,
  File "/usr/lib/pymodules/python2.7/everpad/tools.py", line 31, in wrapper
    return getattr(self.**interface, name)(_args, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/dbus/proxies.py", line 70, in __call**
    return self._proxy_method(_args, *_keywords)
  File "/usr/lib/python2.7/dist-packages/dbus/proxies.py", line 145, in __call__
    **keywords)
  File "/usr/lib/python2.7/dist-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Python.TypeError: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/dbus/service.py", line 751, in _message_cb
    _method_reply_return(connection, message, method_name, signature, *retval)
  File "/usr/lib/python2.7/dist-packages/dbus/service.py", line 254, in _method_reply_return
    reply.append(signature=signature, *retval)
TypeError: an integer is required

**Comment by nvbn** [comment]
Are you use latest version of everpad?

**Comment by laxman20** [comment]
Yes. I used the PPA. 
—

**Comment by nvbn** [comment]
Try to update now, it looks like fixed.

**Comment by hua3505** [comment]
I get the latest version,and I have the same problem.
