### ISSUE TITLE
Can't authorize everpad in LXDE (Lubuntu 12.10): evernote.edam.error.ttypes.EDAMUserException: EDAMUserException(errorCode=5, parameter='authenticationToken')

### ISSUE THREAD

**Issue by hotice** [nvbn/everpad#264]
Everpad starts in Lubuntu 12.10 (LXDE), but I can't get the authorization to work: after authorizing Everpad with Evernote, it still says it's not authorized.

Here's the "everpad-provider --verbose" output:

everpad-provider --verbose
Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.7/everpad/provider/sync.py", line 454, in run
    self.init_network()
  File "/usr/lib/pymodules/python2.7/everpad/provider/sync.py", line 470, in init_network
    self.note_store = get_note_store(self.auth_token)
  File "/usr/lib/pymodules/python2.7/everpad/provider/tools.py", line 65, in get_note_store
    note_store_url = user_store.getNoteStoreUrl(auth_token)
  File "/usr/lib/pymodules/python2.7/evernote/edam/userstore/UserStore.py", line 614, in getNoteStoreUrl
    return self.recv_getNoteStoreUrl()
  File "/usr/lib/pymodules/python2.7/evernote/edam/userstore/UserStore.py", line 637, in recv_getNoteStoreUrl
    raise result.userException
evernote.edam.error.ttypes.EDAMUserException: EDAMUserException(errorCode=5, parameter='authenticationToken')

The authorization works in Ubuntu 12.04, 12.10 and 13.04 with Unity.

**Comment by pehlm** [comment]
Exactly the same here with lubuntu-desktop, Ubuntu 12.04. Would be nice having Everpad working in LXDE/Lubuntu too. Working as it should in Xubuntu. Not tried in Unity.

**Comment by ronaldpottol** [comment]
I have the exact same issue, I'm using an Enlightenment/Ubuntu 12.04LTS  (Bodhi Linux).

here is some version information:

# 1 20130308.09:56:43 r0n@r0n-ThinkPad-X61s:~

cat /etc/issue
Ubuntu 12.04.2 LTS \n \l

# 0 20130308.09:56:50 r0n@r0n-ThinkPad-X61s:~

uname -a
Linux r0n-ThinkPad-X61s 3.7.0-7-generic #15 SMP Thu Dec 27 21:47:00 CST 2012 x86_64 x86_64 x86_64 GNU/Linux

# 0 20130308.09:56:56 r0n@r0n-ThinkPad-X61s:~

everpad -v
Everpad version: 2.5
API version: 6
Schema version: 5

# 0 20130308.09:57:03 r0n@r0n-ThinkPad-X61s:~

everpad-provider -v
Everpad version: 2.5
API version: 6
Schema version: 5

# 0 20130308.09:57:10 r0n@r0n-ThinkPad-X61s:~

**Comment by sschuldenzucker** [comment]
Same thing for me, lubuntu with xmonad.
