### ISSUE TITLE
Everpad won't start.

### ISSUE THREAD

**Issue by atcasanova** [nvbn/everpad#269]
$ cat /etc/issue
Debian GNU/Linux 7.0 \n \l

$ uname -a
Linux xxx 3.2.0-4-686-pae #1 SMP Debian 3.2.35-2 i686 GNU/Linux

$ everpad -v
Everpad version: 2.5
API version: 6
Schema version: 5

$ everpad-provider -v
Everpad version: 2.5
API version: 6
Schema version: 5

$ everpad
Traceback (most recent call last):
  File "/usr/local/bin/everpad", line 9, in <module>
    load_entry_point('everpad==2.5dev', 'gui_scripts', 'everpad')()
  File "/usr/local/lib/python2.7/dist-packages/everpad-2.5dev-py2.7.egg/everpad/pad/indicator.py", line 288, in main
    app.provider = get_provider(session_bus)
  File "/usr/local/lib/python2.7/dist-packages/everpad-2.5dev-py2.7.egg/everpad/tools.py", line 39, in wrapper
    return InterfaceWrapper(partial(fnc, _args, *_kwrags))
  File "/usr/local/lib/python2.7/dist-packages/everpad-2.5dev-py2.7.egg/everpad/tools.py", line 15, in **init**
    self.**load()
  File "/usr/local/lib/python2.7/dist-packages/everpad-2.5dev-py2.7.egg/everpad/tools.py", line 18, in __load
    self.__interface = self.__get()
  File "/usr/local/lib/python2.7/dist-packages/everpad-2.5dev-py2.7.egg/everpad/tools.py", line 47, in get_provider
    provider = bus.get_object("com.everpad.Provider", '/EverpadProvider')
  File "/usr/lib/python2.7/dist-packages/dbus/bus.py", line 241, in get_object
    follow_name_owner_changes=follow_name_owner_changes)
  File "/usr/lib/python2.7/dist-packages/dbus/proxies.py", line 248, in __init**
    self._named_service = conn.activate_name_owner(bus_name)
  File "/usr/lib/python2.7/dist-packages/dbus/bus.py", line 180, in activate_name_owner
    self.start_service_by_name(bus_name)
  File "/usr/lib/python2.7/dist-packages/dbus/bus.py", line 278, in start_service_by_name
    'su', (bus_name, flags)))
  File "/usr/lib/python2.7/dist-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.ServiceUnknown: The name com.everpad.Provider was not provided by any .service files

$ everpad-provider 
QWidget: Cannot create a QWidget when no GUI is being used
Aborted

**Comment by ghost** [comment]
+1 on that (Kali linux is Debian 7 so same applies) 

This is a double of this btw -> 

https://github.com/nvbn/everpad/issues/211
