### ISSUE TITLE
Everpad 2.5 does not start on Ubuntu 12.04

### ISSUE THREAD

**Issue by krnekhelesh** [nvbn/everpad#273]
Both everpad and everpad-lens does not start. On running it from the terminal, I get the following error message,

Traceback (most recent call last):
  File "/usr/local/bin/everpad", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2711, in <module>
    parse_requirements(**requires**), Environment()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 584, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: everpad==2.4dev

**Comment by rahmilale** [comment]
Everpad 2.5 on Ubuntu 12.04.
After installing Everpad I have authorised and also adjusted the settings. However today I can see the system tray icon but when I click on it nothing appears, thus cannot access settings or my notes via the icon. 
I can run it though if I call it via gnome-do, and can browse my notes however I cannot create a new note.
Any help?

Here is the error message I get when I click on the system tray icon:
Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.7/everpad/pad/indicator.py", line 81, in update
    20 - len(pin_notes), Note.ORDER_UPDATED_DESC, 0,
  File "/usr/lib/pymodules/python2.7/everpad/tools.py", line 32, in wrapper
    return getattr(self.**interface, name)(_args, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/dbus/proxies.py", line 70, in __call**
    return self._proxy_method(_args, *_keywords)
  File "/usr/lib/python2.7/dist-packages/dbus/proxies.py", line 145, in __call__
    **keywords)
  File "/usr/lib/python2.7/dist-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Python.TypeError: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/dbus/service.py", line 751, in _message_cb
    _method_reply_return(connection, message, method_name, signature, *retval)
  File "/usr/lib/python2.7/dist-packages/dbus/service.py", line 254, in _method_reply_return
    reply.append(signature=signature, *retval)
TypeError: an integer is required

**Comment by fuku-bukuro** [comment]
Same problem here. Ubuntu 12.04.02 LTE amd64 running gnome-fallback. Same thing if i'm logging in in unity.
I managed to get it working a couple of days ago; did an authorization, put some notes, then the next day, the app appeares in the indicator-applet but if i click on it no menu appears. If I open the app I can see my notes but I cannot create a new note.

:~$ everpad
Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.7/everpad/pad/indicator.py", line 81, in update
    20 - len(pin_notes), Note.ORDER_UPDATED_DESC, 0,
  File "/usr/lib/pymodules/python2.7/everpad/tools.py", line 32, in wrapper
    return getattr(self.**interface, name)(_args, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/dbus/proxies.py", line 70, in __call**
    return self._proxy_method(_args, *_keywords)
  File "/usr/lib/python2.7/dist-packages/dbus/proxies.py", line 145, in __call__
    **keywords)
  File "/usr/lib/python2.7/dist-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Python.TypeError: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/dbus/service.py", line 751, in _message_cb
    _method_reply_return(connection, message, method_name, signature, *retval)
  File "/usr/lib/python2.7/dist-packages/dbus/service.py", line 254, in _method_reply_return
    reply.append(signature=signature, *retval)
TypeError: an integer is required
