### ISSUE TITLE
Crash when try create new note

### ISSUE THREAD

**Issue by otis22** [nvbn/everpad#278]
bug reprocude not always. Ubuntu 12.04 LTS

**Comment by nvbn** [comment]
Can you post everpad output?
You can get it with https://github.com/nvbn/everpad/wiki/Receiving-debug-information

**Comment by kladskull** [comment]
Getting the same issue on ubuntu 12.04 Desktop, here is the dump:

Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.7/everpad/pad/list.py", line 313, in new_note
    self.app.indicator.create(notebook_id=notebook_id)
  File "/usr/lib/pymodules/python2.7/everpad/pad/indicator.py", line 157, in create
    self.app.provider.create_note(note_struct),
  File "/usr/lib/pymodules/python2.7/everpad/tools.py", line 32, in wrapper
    return getattr(self.**interface, name)(_args, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/dbus/proxies.py", line 70, in __call**
    return self._proxy_method(_args, *_keywords)
  File "/usr/lib/python2.7/dist-packages/dbus/proxies.py", line 145, in __call__
    *_keywords)
  File "/usr/lib/python2.7/dist-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Python.AttributeError: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/dbus/service.py", line 707, in _message_cb
    retval = candidate_method(self, *args, *_keywords)
  File "/usr/lib/pymodules/python2.7/everpad/provider/service.py", line 268, in create_note
    dbus_note.give_to_obj(note)
  File "/usr/lib/pymodules/python2.7/everpad/basetypes.py", line 55, in give_to_obj
    setattr(obj, field[0], val)
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/attributes.py", line 155, in **set**
    instance_dict(instance), value, None)
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/attributes.py", line 697, in set
    value = self.fire_replace_event(state, dict_, value, old, initiator)
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/attributes.py", line 717, in fire_replace_event
    value = fn(state, value, previous, initiator or self)
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/attributes.py", line 992, in emit_backref_from_scalar_set_event
    child_state, child_dict = instance_state(child),\
AttributeError: 'dbus.Int32' object has no attribute '_sa_instance_state'
