### ISSUE TITLE
Evernote security update break Everpad

### ISSUE THREAD

**Issue by berzjackson** [nvbn/everpad#279]
There are some recent security updates for Evernote. Currently they are enforcing a service-wide password reset. 
http://evernote.com/corp/news/password_reset.php

Everpad will thus report something like "incorrect password" and refuse to run no matter what. Here are the Traceback information:

 Traceback (most recent call last):
  File "/home/ber/Project/everpad-git/everpad/provider/sync.py", line 454, in run
    self.init_network()
  File "/home/ber/Project/everpad-git/everpad/provider/sync.py", line 470, in init_network
    self.note_store = get_note_store(self.auth_token)
  File "/home/ber/Project/everpad-git/everpad/provider/tools.py", line 65, in get_note_store
    note_store_url = user_store.getNoteStoreUrl(auth_token)
  File "/home/ber/Project/everpad-git/evernote/edam/userstore/UserStore.py", line 614, in getNoteStoreUrl
    return self.recv_getNoteStoreUrl()
  File "/home/ber/Project/everpad-git/evernote/edam/userstore/UserStore.py", line 637, in recv_getNoteStoreUrl
    raise result.userException
evernote.edam.error.ttypes.EDAMUserException: EDAMUserException(errorCode=9, parameter='password')

It also came to me that what if I change the password in the service side. Will Everpad get stuck for the same reason? If so, the current authorization mechanism certainly needs some fix.

**Comment by berzjackson** [comment]
Alright. I switch to the PPA version and everything is fine. Then this has nothing to do with the password reset? I don't quite understand what's going on here. I'll close this for the moment.

**Comment by darkk** [comment]
I got same error & traceback with 0.5.6-0 from PPA. I assume, Evernote revoked access granted to the application during password reset.
Also, access is granted for one year by default, so one may see alike traceback in a year or so. :)
