### ISSUE TITLE
2.5.5 on xubuntu 12.04

### ISSUE THREAD

**Issue by pehlm** [nvbn/everpad#281]
Worked as of 2.5.3. Updating to 2.5.5 give this output:

Traceback (most recent call last):
  File "/usr/bin/everpad", line 9, in <module>
    load_entry_point('everpad==2.5dev', 'gui_scripts', 'everpad')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 337, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2279, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1989, in load
    entry = **import**(self.module_name, globals(),globals(), ['**name**'])
  File "/usr/lib/pymodules/python2.7/everpad/pad/indicator.py", line 8, in <module>
    from everpad.pad.editor import Editor
  File "/usr/lib/pymodules/python2.7/everpad/pad/editor/**init**.py", line 9, in <module>
    from everpad.pad.editor.content import ContentEdit
  File "/usr/lib/pymodules/python2.7/everpad/pad/editor/content.py", line 132, in <module>
    class ContentEdit(QObject):
  File "/usr/lib/pymodules/python2.7/everpad/pad/editor/content.py", line 139, in ContentEdit
    _html = open(_editor_path).read()
IOError: [Errno 2] No such file or directory: '/usr/lib/pymodules/python2.7/share/everpad/editor.html'

**Comment by nvbn** [comment]
You need to update, i broke package again =)

**Comment by pehlm** [comment]
It's now working again. Thanks!
