### ISSUE TITLE
Everpad doesn't start in Fedora 18

### ISSUE THREAD

**Issue by ndias** [nvbn/everpad#289]
In Fedora 18 I can't start everpad, I have this error

Traceback (most recent call last):
  File "/usr/bin/everpad", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 2819, in <module>
    parse_requirements(**requires**), Environment()
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 588, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: regex

I tested every branch and the error is the same

**Comment by tante** [comment]
The regex python lib is not in the fedora repositories, but you can just install it from the python cheeseshop:

```
sudo easy_install regex
```

**Comment by ndias** [comment]
Thanks, but now I have this error
Traceback (most recent call last):
  File "/usr/bin/everpad", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 2819, in <module>
    parse_requirements(**requires**), Environment()
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 588, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: py-oauth2

yes, I have the latest python-oauth2 installed

**Comment by slohmaier** [comment]
I managed to get it working. Just take the python-regex and everpad rpms from: http://fedorarepo.stefanlohmaier.de/fedora-18/x86_64/
or add my repo and yum install it: sudo wget http://fedorarepo.stefanlohmaier.de/fedora-stefanlohmaier.repo -O /etc/yum.repos.d/fedora-stefanlohmaier.repo
If it still doesn't work activate testing updates. I have that.

**Comment by Ramblurr** [comment]
@StefanLohmaier  Thanks, your packages worked for me. Though I grabbed your SRPMs and built it manually after checking the sources.
