### ISSUE TITLE
Авторизация через http proxy

### ISSUE THREAD

**Issue by dkorotin** [nvbn/everpad#29]
Первый запуск свежеустановленного everpad 1.5.1 на ubuntu 12.04.1 amd64

При нажатии на кнопку Авторизация подвисает.

```
dkorotin@dill:~$ everpad
yeeee
Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.7/everpad/pad/management.py", line 77, in change_auth
    'GET')
  File "/usr/lib/python2.7/dist-packages/oauth2/__init__.py", line 682, in request
    connection_type=connection_type)
  File "/usr/lib/python2.7/dist-packages/httplib2/__init__.py", line 1444, in request
    (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections,     cachekey)
  File "/usr/lib/python2.7/dist-packages/httplib2/__init__.py", line 1196, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "/usr/lib/python2.7/dist-packages/httplib2/__init__.py", line 1170, in _conn_request
    conn.connect()
  File "/usr/lib/python2.7/dist-packages/httplib2/__init__.py", line 927, in connect
    raise socket.error, msg
socket.error: [Errno 110] Время ожидания соединения истекло
```

Возможно, дело в прокси. Или в том, что все порты, кроме 22 и 80  наружу закрыты.

**Comment by nvbn** [comment]
Evernote api требует ssl, а это 443 порт.

**Comment by fmoo** [comment]
If your proxy is configured in the environment, this should be working now.
