### ISSUE TITLE
everpad-provider segmentation fault & everpad dbus exception error

### ISSUE THREAD

**Issue by khajavi** [nvbn/everpad#294]
I have installed PySide from source on my Debian (testing) and I have installed the lastest version of everpad from github.

```
$ everpad --version
Everpad version: 2.5
API version: 6
Schema version: 5
```

I have encounter with following error:

```
$ everpad
Traceback (most recent call last):
  File "/usr/local/bin/everpad", line 9, in <module>
    load_entry_point('everpad==2.5dev', 'gui_scripts', 'everpad')()
  File "/usr/local/lib/python2.6/dist-packages/everpad-2.5dev-py2.6.egg/everpad/pad/indicator.py", line 288, in main
    app.provider = get_provider(session_bus)
  File "/usr/local/lib/python2.6/dist-packages/everpad-2.5dev-py2.6.egg/everpad/tools.py", line 39, in wrapper
    return InterfaceWrapper(partial(fnc, *args, **kwrags))
  File "/usr/local/lib/python2.6/dist-packages/everpad-2.5dev-py2.6.egg/everpad/tools.py", line 15, in __init__
    self.__load()
  File "/usr/local/lib/python2.6/dist-packages/everpad-2.5dev-py2.6.egg/everpad/tools.py", line 18, in __load
    self.__interface = self.__get()
  File "/usr/local/lib/python2.6/dist-packages/everpad-2.5dev-py2.6.egg/everpad/tools.py", line 47, in get_provider
    provider = bus.get_object("com.everpad.Provider", '/EverpadProvider')
  File "/usr/lib/python2.6/dist-packages/dbus/bus.py", line 241, in get_object
    follow_name_owner_changes=follow_name_owner_changes)
  File "/usr/lib/python2.6/dist-packages/dbus/proxies.py", line 248, in __init__
    self._named_service = conn.activate_name_owner(bus_name)
  File "/usr/lib/python2.6/dist-packages/dbus/bus.py", line 180, in activate_name_owner
    self.start_service_by_name(bus_name)
  File "/usr/lib/python2.6/dist-packages/dbus/bus.py", line 278, in start_service_by_name
    'su', (bus_name, flags)))
  File "/usr/lib/python2.6/dist-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.Spawn.ChildExited: Process /usr/bin/everpad-provider exited with status 1
```

And when I run everpad-provider:

```
$ everpad-provider 
Segmentation fault
```

**Comment by laur89** [comment]
+1 on Debian Wheezy.

**Comment by ulrikkold** [comment]
+1 on Ubunty 13.10. However, this is not the same traceback. I get this:

```
$ everpad
Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.7/everpad/pad/indicator.py", line 74, in update
    if self.app.provider.is_authenticated():
  File "/usr/lib/pymodules/python2.7/everpad/tools.py", line 32, in wrapper
    return getattr(self.__interface, name)(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/dbus/proxies.py", line 70, in __call__
    return self._proxy_method(*args, **keywords)
  File "/usr/lib/python2.7/dist-packages/dbus/proxies.py", line 145, in __call__
    **keywords)
  File "/usr/lib/python2.7/dist-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NoReply: Message did not receive a reply (timeout by message bus)
```

**Comment by luisdavim** [comment]
I have the same problem as khajavi

**Comment by Mibou** [comment]
For all the Debian-Everpad hopeless users, take a look at Nixnote which is a nice Everpad alternative until this bug gets fixed.
