### ISSUE TITLE
The name com.everpad.Provider was not provided by any .service files

### ISSUE THREAD

**Issue by hdg700** [nvbn/everpad#3]
$ everpad
Traceback (most recent call last):
  File "/usr/bin/everpad", line 9, in <module>
    load_entry_point('everpad==0.4.1dev', 'gui_scripts', 'everpad')()
  File "/usr/lib/python2.7/site-packages/everpad-0.4.1dev-py2.7.egg/everpad/pad.py", line 342, in main
    app = App(sys.argv)
  File "/usr/lib/python2.7/site-packages/everpad-0.4.1dev-py2.7.egg/everpad/pad.py", line 198, in **init**
    self.provider_obj = dbus.SessionBus().get_object("com.everpad.Provider", '/EverpadProvider')
  File "/usr/lib/python2.7/site-packages/dbus/bus.py", line 241, in get_object
    follow_name_owner_changes=follow_name_owner_changes)
  File "/usr/lib/python2.7/site-packages/dbus/proxies.py", line 248, in **init**
    self._named_service = conn.activate_name_owner(bus_name)
  File "/usr/lib/python2.7/site-packages/dbus/bus.py", line 180, in activate_name_owner
    self.start_service_by_name(bus_name)
  File "/usr/lib/python2.7/site-packages/dbus/bus.py", line 278, in start_service_by_name
    'su', (bus_name, flags)))
  File "/usr/lib/python2.7/site-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.ServiceUnknown: The name com.everpad.Provider was not provided by any .service files
QThread: Destroyed while thread is still running

**Comment by nvbn** [comment]
На текущей версии повторяется?

**Comment by e2jk** [comment]
Is this issue still happening with the current version 2.5?
