### ISSUE TITLE
Ubuntu 12.10.  Ошибка. Не запускается

### ISSUE THREAD

**Issue by NivasAlex** [nvbn/everpad#30]
Traceback (most recent call last):
  File "/usr/bin/everpad", line 9, in <module>
    load_entry_point('everpad==1.6dev', 'gui_scripts', 'everpad')()
  File "/usr/lib/pymodules/python2.7/everpad/pad/indicator.py", line 187, in main
    app.launcher = UnityLauncher('application://everpad.desktop', session_bus, '/')
  File "/usr/lib/pymodules/python2.7/everpad/pad/indicator.py", line 151, in **init**
    dbus.service.Object.**init**(self, _args, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/dbus/service.py", line 485, in **init**
    self.add_to_connection(conn, object_path)
  File "/usr/lib/python2.7/dist-packages/dbus/service.py", line 576, in add_to_connection
    self._fallback)
RuntimeError: To make asynchronous calls, receive signals or export objects, D-Bus connections must be attached to a main loop by passing mainloop=... to the constructor or calling dbus.set_default_main_loop(...)

**Comment by nvbn** [comment]
i386 или amd64?
Подключены ли какие-нибудь сторонние ppa?

**Comment by NivasAlex** [comment]
1. amd64
2. http://ppa.launchpad.net/tualatrix/ppa/ubuntu quantal
   http://ppa.launchpad.net/nvbn-rm/ppa/ubuntu quantal
   http://dl.google.com/linux/chrome/deb/ stable
