### ISSUE TITLE
Nothing works after authorization in Arch Linux

### ISSUE THREAD

**Issue by savyajha** [nvbn/everpad#300]
Hello. My DE is KDE, first of all, and I'm using the version of Everpad in Arch's AUR. After authorization (which proceeded smoothly), I run everpad-provider in one terminal, and everpad in another. I get this error:

<code>Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/everpad/pad/indicator.py", line 76, in update
    20, Note.ORDER_UPDATED_DESC, 1,
  File "/usr/lib/python2.7/site-packages/everpad/tools.py", line 32, in wrapper
    return getattr(self.**interface, name)(_args, *_kwargs)
  File "/usr/lib/python2.7/site-packages/dbus/proxies.py", line 70, in __call**
    return self._proxy_method(_args, *_keywords)
  File "/usr/lib/python2.7/site-packages/dbus/proxies.py", line 145, in __call__
    *_keywords)
  File "/usr/lib/python2.7/site-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Python.sqlalchemy.exc.InvalidRequestError: Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/dbus/service.py", line 707, in _message_cb
    retval = candidate_method(self, *args, *_keywords)
  File "/usr/lib/python2.7/site-packages/everpad/provider/service.py", line 101, in find_notes
    qs = self.sq(Note).filter(and_(
  File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 1105, in query
    return self._query_cls(entities, self, **kwargs)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 115, in __init__
    self._set_entities(entities)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 124, in _set_entities
    self._set_entity_selectables(self._entities)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 157, in _set_entity_selectables
    ent.setup_entity(*d[entity])
  File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2744, in setup_entity
    self._with_polymorphic = ext_info.with_polymorphic_mappers
  File "/usr/lib/python2.7/site-packages/sqlalchemy/util/langhelpers.py", line 582, in __get__
    obj.**dict**[self.**name**] = result = self.fget(obj)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/mapper.py", line 1425, in _with_polymorphic_mappers
    configure_mappers()
  File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/mapper.py", line 2103, in configure_mappers
    raise e
InvalidRequestError: One or more mappers failed to initialize - can't proceed with initialization of other mappers.  Original exception was: Can't determine relationship direction for relationship 'Note.conflict_parent' - foreign key columns within the join condition are present in both the parent and the child's mapped tables.  Ensure that only those columns referring to a parent column are marked as foreign, either via the foreign() annotation or via the foreign_keys argument.</code>

"everpad --create" also gives me the same error. Even "everpad-provider --verbose" gives me no error output. There is no window, nothing.

**Comment by acmzero** [comment]
Same error here

**Comment by tobias-theobald** [comment]
Same here but with Gnome 3.6

**Comment by rustikus** [comment]
Same problem here with Gnome 3.6

**Comment by jeffsharpe** [comment]
Same error here - Everpad 2.5.6-1 off the AUR as well.

**Comment by l0ckpix** [comment]
Same error here on Gentoo and KDE.

**Comment by woprandi** [comment]
Same

**Comment by bitthegeek** [comment]
same here - openbox

**Comment by l0ckpix** [comment]
i downgraded sqlalchemy to 0.7.9 (0.8.1 and 0.8.0 dont work!). Not it works for me.

**Comment by anpieber** [comment]
yep sqlalchemy is the problem. You think its possible to upgrade?

**Comment by mgaunard** [comment]
Also affects Ubuntu 13.10...

**Comment by trivoallan** [comment]
Downgrading to python-alchemy and python-alchemy-ext 0.7.9 on Ubuntu 13.10 did not fix the problem.
