### ISSUE TITLE
Can't authorise with Ubuntu 12.10 x86_64

### ISSUE THREAD

**Issue by peterg10** [nvbn/everpad#308]
I fire up the everpad application (on the command line) and when I hit the authorize button I get:

Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.7/everpad/pad/management.py", line 211, in change_auth
    url = 'http://%s/OAuth.action?oauth_token=' % HOST + urllib.quote(data['oauth_token'])
KeyError: 'oauth_token'

it looks like it doesn't have a host name defined.

UPDATE: I rebooted my laptop and it now works.

**Comment by TuxRoxSr** [comment]
This issue is also seen on 13.04 x86_64.

**Comment by gregorth** [comment]
I confirm - kubuntu 13.04x86_64
I run everpad with below command and try to authorize myself, here is what I get on console:
LIBOVERLAY_SCROLLBAR=0 everpad
"sni-qt/3110" WARN  18:13:23.236 void StatusNotifierItemFactory::connectToSnw() Invalid interface to SNW_SERVICE 
Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.7/everpad/pad/management.py", line 211, in change_auth
    url = 'http://%s/OAuth.action?oauth_token=' % HOST + urllib.quote(data['oauth_token'])
KeyError: 'oauth_token'

**Comment by fuku-bukuro** [comment]
I have the same issue Ubuntu 12.0.4
~$ everpad
Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.7/everpad/pad/management.py", line 211, in change_auth
    url = 'http://%s/OAuth.action?oauth_token=' % HOST + urllib.quote(data['oauth_token'])
KeyError: 'oauth_token'
^C
:~$ uname -a
Linux  3.5.0-27-generic #46~precise1-Ubuntu SMP Tue Mar 26 19:33:21 UTC 2013 x86_64 x86_64 x86_64 GNU/Linux

**Comment by kassick** [comment]
Same issue. data has the folowing value:
![Captura de tela de 2013-04-11 16:34:22](https://f.cloud.github.com/assets/21071/369779/db5a5a3c-a2de-11e2-8cb3-7b7d1000a0bf.png)

**Comment by kassick** [comment]
(everpad from ppa)

**Comment by BigMcLargeHuge** [comment]
Same issue here with Kubuntu AMD64 12.04.2.  The odd thing is that I have it running just fine on my laptop that has exactly the same operating system.  Seems to be looking for a trackback url.

everpad
Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.7/everpad/pad/management.py", line 67, in acceptNavigationRequest
    self.parent.auth_finished(access_token['oauth_token'])
KeyError: 'oauth_token'

**Comment by aditiapratama** [comment]
Same error here, trying to run this code `$ everpad-provider` on my linux mint kde 14 and below the error log

```
Traceback (most recent call last):
  File "/usr/bin/everpad-provider", line 9, in <module>
    load_entry_point('everpad==2.5dev', 'console_scripts', 'everpad-provider')()
  File "/usr/lib/pymodules/python2.7/everpad/provider/daemon.py", line 95, in main
    app = ProviderApp(args.verbose, sys.argv)
  File "/usr/lib/pymodules/python2.7/everpad/provider/daemon.py", line 34, in __init__
    if get_auth_token():
  File "/usr/lib/pymodules/python2.7/everpad/provider/tools.py", line 35, in get_auth_token
    return get_keyring().get_password('everpad', 'oauth_token')
  File "/usr/lib/python2.7/dist-packages/keyring/core.py", line 37, in get_password
    return _keyring_backend.get_password(service_name, username)
  File "/usr/lib/python2.7/dist-packages/keyring/backend.py", line 301, in get_password
    if wallet.keyDoesNotExist(network, 'Python', key):
AttributeError: 'NoneType' object has no attribute 'keyDoesNotExist'
```
