### ISSUE TITLE
Arch : Everpad clean install, Sqlalchemy error

### ISSUE THREAD

**Issue by utkarshsins** [nvbn/everpad#311]
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/everpad-2.5dev-py2.7.egg/everpad/pad/indicator.py", line 78, in update
    20, Note.ORDER_UPDATED_DESC, 1,
  File "/usr/lib/python2.7/site-packages/everpad-2.5dev-py2.7.egg/everpad/tools.py", line 32, in wrapper
    return getattr(self.__interface, name)(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/dbus/proxies.py", line 70, in __call__
    return self._proxy_method(*args, **keywords)
  File "/usr/lib/python2.7/site-packages/dbus/proxies.py", line 145, in __call__
    **keywords)
  File "/usr/lib/python2.7/site-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Python.sqlalchemy.exc.InvalidRequestError: Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/dbus/service.py", line 707, in _message_cb
    retval = candidate_method(self, *args, **keywords)
  File "/usr/lib/python2.7/site-packages/everpad-2.5dev-py2.7.egg/everpad/provider/service.py", line 115, in find_notes
    qs = self.sq(Note).filter(and_(
  File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 1105, in query
    return self._query_cls(entities, self, **kwargs)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 115, in __init__
    self._set_entities(entities)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 124, in _set_entities
    self._set_entity_selectables(self._entities)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 157, in _set_entity_selectables
    ent.setup_entity(*d[entity])
  File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2744, in setup_entity
    self._with_polymorphic = ext_info.with_polymorphic_mappers
  File "/usr/lib/python2.7/site-packages/sqlalchemy/util/langhelpers.py", line 582, in __get__
    obj.__dict__[self.__name__] = result = self.fget(obj)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/mapper.py", line 1425, in _with_polymorphic_mappers
    configure_mappers()
  File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/mapper.py", line 2103, in configure_mappers
    raise e
InvalidRequestError: One or more mappers failed to initialize - can't proceed with initialization of other mappers.  Original exception was: Can't determine relationship direction for relationship 'Note.conflict_parent' - foreign key columns within the join condition are present in both the parent and the child's mapped tables.  Ensure that only those columns referring to a parent column are marked as foreign, either via the foreign() annotation or via the foreign_keys argument.
```

**Comment by amites** [comment]
Looks like I have the same issue on Ubuntu 13.04
had to manually install PySide to complete installation of Everpad from repo to verify this hadn't already been fixed

this error shows when I click on the menu icon to bring up the window, it doesn't bring up window just this error each time I click on the icon

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/everpad-2.5dev-py2.7.egg/everpad/pad/indicator.py", line 78, in update
    20, Note.ORDER_UPDATED_DESC, 1,
  File "/usr/local/lib/python2.7/dist-packages/everpad-2.5dev-py2.7.egg/everpad/tools.py", line 32, in wrapper
    return getattr(self.__interface, name)(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/dbus/proxies.py", line 70, in __call__
    return self._proxy_method(*args, **keywords)
  File "/usr/lib/python2.7/dist-packages/dbus/proxies.py", line 145, in __call__
    **keywords)
  File "/usr/lib/python2.7/dist-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Python.sqlalchemy.exc.InvalidRequestError: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/dbus/service.py", line 707, in _message_cb
    retval = candidate_method(self, *args, **keywords)
  File "/usr/local/lib/python2.7/dist-packages/everpad-2.5dev-py2.7.egg/everpad/provider/service.py", line 175, in find_notes
    .order_by(order)\
  File "/usr/local/lib/python2.7/dist-packages/everpad-2.5dev-py2.7.egg/everpad/provider/service.py", line 82, in all
    return self.session.query(models.Note).filter(and_(
  File "/usr/local/lib/python2.7/dist-packages/SQLAlchemy-0.8.1-py2.7-linux-x86_64.egg/sqlalchemy/orm/session.py", line 1106, in query
    return self._query_cls(entities, self, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/SQLAlchemy-0.8.1-py2.7-linux-x86_64.egg/sqlalchemy/orm/query.py", line 115, in __init__
    self._set_entities(entities)
  File "/usr/local/lib/python2.7/dist-packages/SQLAlchemy-0.8.1-py2.7-linux-x86_64.egg/sqlalchemy/orm/query.py", line 124, in _set_entities
    self._set_entity_selectables(self._entities)
  File "/usr/local/lib/python2.7/dist-packages/SQLAlchemy-0.8.1-py2.7-linux-x86_64.egg/sqlalchemy/orm/query.py", line 157, in _set_entity_selectables
    ent.setup_entity(*d[entity])
  File "/usr/local/lib/python2.7/dist-packages/SQLAlchemy-0.8.1-py2.7-linux-x86_64.egg/sqlalchemy/orm/query.py", line 2728, in setup_entity
    self._with_polymorphic = ext_info.with_polymorphic_mappers
  File "/usr/local/lib/python2.7/dist-packages/SQLAlchemy-0.8.1-py2.7-linux-x86_64.egg/sqlalchemy/util/langhelpers.py", line 614, in __get__
    obj.__dict__[self.__name__] = result = self.fget(obj)
  File "/usr/local/lib/python2.7/dist-packages/SQLAlchemy-0.8.1-py2.7-linux-x86_64.egg/sqlalchemy/orm/mapper.py", line 1426, in _with_polymorphic_mappers
    configure_mappers()
  File "/usr/local/lib/python2.7/dist-packages/SQLAlchemy-0.8.1-py2.7-linux-x86_64.egg/sqlalchemy/orm/mapper.py", line 2118, in configure_mappers
    raise e
InvalidRequestError: One or more mappers failed to initialize - can't proceed with initialization of other mappers.  Original exception was: Can't determine relationship direction for relationship 'Note.conflict_parent' - foreign key columns within the join condition are present in both the parent and the child's mapped tables.  Ensure that only those columns referring to a parent column are marked as foreign, either via the foreign() annotation or via the foreign_keys argument.
```

**Comment by aiguofer** [comment]
I'm having the same issue on Arch.
