### ISSUE TITLE
Everpad Installation on Linux Mint

### ISSUE THREAD

**Issue by larkabc** [nvbn/everpad#312]
I have followed directions for install in the Wiki but I get following error in the last install step:

nayyar@HomeComputer ~/everpad $ python setup.py install
Traceback (most recent call last):
  File "setup.py", line 1, in <module>
    from setuptools import setup, find_packages
ImportError: No module named setuptools

What am I missing?

**Comment by overthetop95** [comment]
You need to install the python-setuptools package. You may need to make sure all of the required packages are installed by hand.

**Comment by larkabc** [comment]
I followed the bug reporting instructions and when I start everpad in 2nd terminal window and then click on the systray area, here is the error message I receive:

Error calling slot "update" 
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/everpad-2.5dev-py2.7.egg/everpad/pad/indicator.py", line 78, in update
    20, Note.ORDER_UPDATED_DESC, 1,
  File "/usr/local/lib/python2.7/dist-packages/everpad-2.5dev-py2.7.egg/everpad/tools.py", line 32, in wrapper
    return getattr(self.**interface, name)(_args, *_kwargs)
  File "/usr/lib/pymodules/python2.7/dbus/proxies.py", line 68, in __call**
    return self._proxy_method(_args, *_keywords)
  File "/usr/lib/pymodules/python2.7/dbus/proxies.py", line 140, in __call__
    *_keywords)
  File "/usr/lib/pymodules/python2.7/dbus/connection.py", line 630, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Python.sqlalchemy.exc.InvalidRequestError: Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.7/dbus/service.py", line 702, in _message_cb
    retval = candidate_method(self, *args, *_keywords)
  File "/usr/local/lib/python2.7/dist-packages/everpad-2.5dev-py2.7.egg/everpad/provider/service.py", line 107, in find_notes
    qs = self.sq(models.Note).filter(and_(
  File "/usr/local/lib/python2.7/dist-packages/SQLAlchemy-0.8.1-py2.7.egg/sqlalchemy/orm/session.py", line 1106, in query
    return self._query_cls(entities, self, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/SQLAlchemy-0.8.1-py2.7.egg/sqlalchemy/orm/query.py", line 115, in __init__
    self._set_entities(entities)
  File "/usr/local/lib/python2.7/dist-packages/SQLAlchemy-0.8.1-py2.7.egg/sqlalchemy/orm/query.py", line 124, in _set_entities
    self._set_entity_selectables(self._entities)
  File "/usr/local/lib/python2.7/dist-packages/SQLAlchemy-0.8.1-py2.7.egg/sqlalchemy/orm/query.py", line 157, in _set_entity_selectables
    ent.setup_entity(*d[entity])
  File "/usr/local/lib/python2.7/dist-packages/SQLAlchemy-0.8.1-py2.7.egg/sqlalchemy/orm/query.py", line 2728, in setup_entity
    self._with_polymorphic = ext_info.with_polymorphic_mappers
  File "/usr/local/lib/python2.7/dist-packages/SQLAlchemy-0.8.1-py2.7.egg/sqlalchemy/util/langhelpers.py", line 614, in __get__
    obj.**dict**[self.**name**] = result = self.fget(obj)
  File "/usr/local/lib/python2.7/dist-packages/SQLAlchemy-0.8.1-py2.7.egg/sqlalchemy/orm/mapper.py", line 1426, in _with_polymorphic_mappers
    configure_mappers()
  File "/usr/local/lib/python2.7/dist-packages/SQLAlchemy-0.8.1-py2.7.egg/sqlalchemy/orm/mapper.py", line 2118, in configure_mappers
    raise e
InvalidRequestError: One or more mappers failed to initialize - can't proceed with initialization of other mappers.  Original exception was: Can't determine relationship direction for relationship 'Note.conflict_parent' - foreign key columns within the join condition are present in both the parent and the child's mapped tables.  Ensure that only those columns referring to a parent column are marked as foreign, either via the foreign() annotation or via the foreign_keys argument.

**Comment by rc2dev** [comment]
You can just use the Ubuntu PPA.

**Comment by larkabc** [comment]
I have tried that .. it does not work with my version of Linux Mint.
