### ISSUE TITLE
[Ubuntu 13.04 amd64] I can't start my everpad.

### ISSUE THREAD

**Issue by kanglongba** [nvbn/everpad#314]
My os is Ubuntu 13.04 amd64.

This is my version of everpad.
unclelong@unclelong-bupt:~$ everpad --version
Everpad version: 2.5
API version: 6
Schema version: 5
unclelong@unclelong-bupt:~$ everpad-provider --version
Everpad version: 2.5
API version: 6
Schema version: 5

This is the ever message:
unclelong@unclelong-bupt:~$ everpad
Traceback (most recent call last):
  File "/usr/bin/everpad", line 9, in <module>
    load_entry_point('everpad==2.5dev', 'gui_scripts', 'everpad')()
  File "/usr/lib/pymodules/python2.7/everpad/pad/indicator.py", line 314, in main
    pad = get_pad()
  File "/usr/lib/pymodules/python2.7/everpad/tools.py", line 39, in wrapper
    return InterfaceWrapper(partial(fnc, _args, *_kwrags))
  File "/usr/lib/pymodules/python2.7/everpad/tools.py", line 15, in **init**
    self.**load()
  File "/usr/lib/pymodules/python2.7/everpad/tools.py", line 18, in __load
    self.__interface = self.__get()
  File "/usr/lib/pymodules/python2.7/everpad/tools.py", line 55, in get_pad
    pad = bus.get_object("com.everpad.App", "/EverpadService")
  File "/usr/lib/python2.7/dist-packages/dbus/bus.py", line 241, in get_object
    follow_name_owner_changes=follow_name_owner_changes)
  File "/usr/lib/python2.7/dist-packages/dbus/proxies.py", line 248, in __init**
    self._named_service = conn.activate_name_owner(bus_name)
  File "/usr/lib/python2.7/dist-packages/dbus/bus.py", line 180, in activate_name_owner
    self.start_service_by_name(bus_name)
  File "/usr/lib/python2.7/dist-packages/dbus/bus.py", line 278, in start_service_by_name
    'su', (bus_name, flags)))
  File "/usr/lib/python2.7/dist-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NoReply: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.

**Comment by kanglongba** [comment]
I reboot my computer ,then I can start my everpad.
