### ISSUE TITLE
Can't start everpad on Fedora

### ISSUE THREAD

**Issue by stephanehofman** [nvbn/everpad#318]
Hello, in Fedora 18 I can't start everpad, I have this error

$ everpad
Traceback (most recent call last):
  File "/usr/bin/everpad", line 9, in <module>
    load_entry_point('everpad==2.5dev', 'gui_scripts', 'everpad')()
  File "/usr/lib/python2.7/site-packages/everpad-2.5dev-py2.7.egg/everpad/pad/indicator.py", line 318, in main
    app.provider = get_provider(session_bus)
  File "/usr/lib/python2.7/site-packages/everpad-2.5dev-py2.7.egg/everpad/tools.py", line 39, in wrapper
    return InterfaceWrapper(partial(fnc, _args, *_kwrags))
  File "/usr/lib/python2.7/site-packages/everpad-2.5dev-py2.7.egg/everpad/tools.py", line 15, in **init**
    self.**load()
  File "/usr/lib/python2.7/site-packages/everpad-2.5dev-py2.7.egg/everpad/tools.py", line 18, in __load
    self.__interface = self.__get()
  File "/usr/lib/python2.7/site-packages/everpad-2.5dev-py2.7.egg/everpad/tools.py", line 47, in get_provider
    provider = bus.get_object("com.everpad.Provider", '/EverpadProvider')
  File "/usr/lib/python2.7/site-packages/dbus/bus.py", line 241, in get_object
    follow_name_owner_changes=follow_name_owner_changes)
  File "/usr/lib/python2.7/site-packages/dbus/proxies.py", line 248, in __init**
    self._named_service = conn.activate_name_owner(bus_name)
  File "/usr/lib/python2.7/site-packages/dbus/bus.py", line 180, in activate_name_owner
    self.start_service_by_name(bus_name)
  File "/usr/lib/python2.7/site-packages/dbus/bus.py", line 278, in start_service_by_name
    'su', (bus_name, flags)))
  File "/usr/lib/python2.7/site-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.ServiceUnknown: The name com.everpad.Provider was not provided by any .service files

Can someone help me please ?
Thanks

**Comment by Heart1010** [comment]
Looks identical like the problem I/we have in openSUSE, see https://github.com/nvbn/everpad/issues/307#issuecomment-17066939

**Comment by stephanehofman** [comment]
Maybe ... But in fedora we have dbus-python 
#yum info dbus-python
Modules complémentaires chargés : langpacks, presto, refresh-packagekit
Paquets installés
Nom                 : dbus-python
Architecture        : x86_64
Version             : 1.1.1
Révision            : 3.fc18
Taille              : 828 k
Dépôt               : installed
Depuis le dépôt     : updates
Résumé              : D-Bus Python Bindings
URL                 : http://www.freedesktop.org/software/dbus/
Licence             : MIT
Description         : D-Bus python bindings for use with python programs.

And we have also python-setuptools
#yum info python-setuptools
Modules complémentaires chargés : langpacks, presto, refresh-packagekit
Paquets installés
Nom                 : python-setuptools
Architecture        : noarch
Version             : 0.6.28
Révision            : 3.fc18
Taille              : 1.5 M
Dépôt               : installed
Depuis le dépôt     : koji-override-0
Résumé              : Easily build and distribute Python packages
URL                 : http://pypi.python.org/pypi/distribute
Licence             : Python or ZPLv2.0
Description         : Setuptools is a collection of enhancements to the Python
                    : distutils that allow you to more easily build and
                    : distribute Python packages, especially ones that have
                    : dependencies on other packages.
                    : 
                    : This package contains the runtime components of
                    : setuptools, necessary to execute the software that
                    : requires pkg_resources.py.
                    : 
                    : This package contains the distribute fork of setuptools.

**Comment by Heart1010** [comment]
in openSUSE we have also package "dbus-1-python" and it's installed here but everpad error stays....

**Comment by nvbn** [comment]
If you run everpad-provider manualy it works?

**Comment by stephanehofman** [comment]
nothing happen when I run it ...

**Comment by jalberto** [comment]
If I run everpad-provider manually, everpad mostly works but 2 problems:
- icon is invisible
- all notebooks appear, but only one note is synced

**Comment by stephanehofman** [comment]
Where can you see your notebooks ? 
Are you using Gnome 3 ?

**Comment by stephanehofman** [comment]
I've tried to use one more time everpad-provider and here's the result (very very slow ) : 
$ everpad-provider
/usr/lib64/python2.7/site-packages/sqlalchemy/sql/expression.py:1927: SAWarning: The IN-predicate on "resources.id" was invoked with an empty sequence. This results in a contradiction, which nonetheless can be expensive to evaluate.  Consider alternative strategies for improved performance.
  return self._in_impl(operators.in_op, operators.notin_op, other)

**Comment by stephanehofman** [comment]
Bump ...
Thanks for your help ...

**Comment by mattrose** [comment]
I just hit this.  If I start up everpad-provider manually, and then run everpad --all-notes, the window comes up, but none of my notes appear.

**Comment by mattrose** [comment]
Could it be related to systemd?

**Comment by stephanehofman** [comment]
Same thing like you for me : everpad --all-notes, the window comes up, but none of my notes appear.

**Comment by mattrose** [comment]
This issue can be fixed by installing with "python setup.py install --root /"  Is there interest for a fedora RPM for this?

**Comment by stephanehofman** [comment]
Of course a Fedora RPM could be a great thing !

**Comment by stephanehofman** [comment]
Hi everyone,
Same issue on Fedora 19 ....

**Comment by stephanehofman** [comment]
if I try "python setup.py install --root /"
after :  $everpad

everpad
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/everpad/pad/indicator.py", line 78, in update
    20, Note.ORDER_UPDATED_DESC, 1,
  File "/usr/lib/python2.7/site-packages/everpad/tools.py", line 32, in wrapper
    return getattr(self.**interface, name)(_args, *_kwargs)
  File "/usr/lib/python2.7/site-packages/dbus/proxies.py", line 70, in __call**
    return self._proxy_method(_args, *_keywords)
  File "/usr/lib/python2.7/site-packages/dbus/proxies.py", line 145, in __call__
    *_keywords)
  File "/usr/lib/python2.7/site-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Python.sqlalchemy.exc.InvalidRequestError: Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/dbus/service.py", line 707, in _message_cb
    retval = candidate_method(self, *args, *_keywords)
  File "/usr/lib/python2.7/site-packages/everpad/provider/service.py", line 107, in find_notes
    qs = self.sq(models.Note).filter(and_(
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/session.py", line 1106, in query
    return self._query_cls(entities, self, **kwargs)
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/query.py", line 115, in __init__
    self._set_entities(entities)
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/query.py", line 124, in _set_entities
    self._set_entity_selectables(self._entities)
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/query.py", line 157, in _set_entity_selectables
    ent.setup_entity(*d[entity])
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/query.py", line 2728, in setup_entity
    self._with_polymorphic = ext_info.with_polymorphic_mappers
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/util/langhelpers.py", line 614, in __get__
    obj.**dict**[self.**name**] = result = self.fget(obj)
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/mapper.py", line 1426, in _with_polymorphic_mappers
    configure_mappers()
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/mapper.py", line 2118, in configure_mappers
    raise e
InvalidRequestError: One or more mappers failed to initialize - can't proceed with initialization of other mappers.  Original exception was: Can't determine relationship direction for relationship 'Note.conflict_parent' - foreign key columns within the join condition are present in both the parent and the child's mapped tables.  Ensure that only those columns referring to a parent column are marked as foreign, either via the foreign() annotation or via the foreign_keys argument.
