### ISSUE TITLE
Everpad Provider - socket.error

### ISSUE THREAD

**Issue by kernelp4nic** [nvbn/everpad#328]
Hi guys, everpad-provider it's throwing an error, and I have just a few notes in everpad.
## 

Everpad installed from ppa:nvbn-rm/ppa

s@drakarys:~$ uname -a
Linux drakarys 3.8.0-19-generic #30-Ubuntu SMP Wed May 1 16:35:23 UTC 2013 x86_64 x86_64 x86_64 GNU/Linux

---

s@drakarys:~$ everpad --version
Everpad version: 2.5
API version: 6
Schema version: 5

---

s@drakarys:~$ everpad-provider --verbose
Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.7/everpad/provider/sync.py", line 458, in run
    self.perform()
  File "/usr/lib/pymodules/python2.7/everpad/provider/sync.py", line 491, in perform
    self.all_notes = list(self._iter_all_notes())
  File "/usr/lib/pymodules/python2.7/everpad/provider/sync.py", line 65, in _iter_all_notes
    ), offset, EDAM_USER_NOTES_MAX)
  File "/usr/lib/pymodules/python2.7/evernote/edam/notestore/NoteStore.py", line 3877, in findNotes
    self.send_findNotes(authenticationToken, filter, offset, maxNotes)
  File "/usr/lib/pymodules/python2.7/evernote/edam/notestore/NoteStore.py", line 3889, in send_findNotes
    self._oprot.trans.flush()
  File "/usr/lib/pymodules/python2.7/thrift/transport/THttpClient.py", line 124, in _f
    result = f(_args, *_kwargs)
  File "/usr/lib/pymodules/python2.7/thrift/transport/THttpClient.py", line 163, in flush
    self.__http.endheaders()
  File "/usr/lib/python2.7/httplib.py", line 969, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 829, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 791, in send
    self.connect()
  File "/usr/lib/pymodules/python2.7/thrift/transport/httpslib.py", line 35, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 553, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
socket.error: [Errno 2] No such file or directory

**Comment by simone-zero12** [comment]
+1
Same issue for me with 2.5.7~precise
