### ISSUE TITLE
1.8: Attached files not saved

### ISSUE THREAD

**Issue by hotice** [nvbn/everpad#33]
Everpad 1.8: attached files don't show up in the notes, it's like the files were never attached.

Here's what I get when I try to attach a file:

Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.7/everpad/pad/editor.py", line 412, in add
    self.add_attach(name)
  File "/usr/lib/pymodules/python2.7/everpad/pad/editor.py", line 431, in add_attach
    self._put(res)
  File "/usr/lib/pymodules/python2.7/everpad/pad/editor.py", line 360, in _put
    self._res_hash[res.hash] = res
AttributeError: 'Resource' object has no attribute 'hash'

Or this:

raceback (most recent call last):
  File "/usr/lib/pymodules/python2.7/everpad/pad/editor.py", line 412, in add
    self.add_attach(name)
  File "/usr/lib/pymodules/python2.7/everpad/pad/editor.py", line 431, in add_attach
    self._put(res)
  File "/usr/lib/pymodules/python2.7/everpad/pad/editor.py", line 360, in _put
    self._res_hash[res.hash] = res
AttributeError: 'Resource' object has no attribute 'hash'
ERROR:dbus.connection:Unable to set arguments ((dbus.Int32(1), u'New note', u'New note contentt', dbus.Int64(1345124803000L), dbus.Int64(1345124803000L), 1, dbus.Array([u''], signature=dbus.Signature('s')), dbus.String(u'')), dbus.Array([(0, u'OTP2BR8AB25F.pdf', u'/home/andrei/.everpad/data/1/OTP2BR8AB25F.pdf', 'application/pdf', None)], signature=dbus.Signature('(issss)'))) according to signature None: <type 'exceptions.TypeError'>: Expected a string or unicode object
Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.7/everpad/pad/editor.py", line 571, in save
    ), signature=Resource.signature),
  File "/usr/lib/python2.7/dist-packages/dbus/proxies.py", line 145, in __call__
    **keywords)
  File "/usr/lib/python2.7/dist-packages/dbus/connection.py", line 641, in call_blocking
    message.append(signature=signature, *args)
TypeError: Expected a string or unicode object

**Comment by nvbn** [comment]
Dbus api changed and you need restart provider or reboot your system after
update.
13.09.2012 14:22 пользователь "Andrew" notifications@github.com написал:

**Comment by hotice** [comment]
It still doesn't work after a reboot. The attachments are not saved...

**Comment by nvbn** [comment]
Packages with fix pushed to launchpad.

**Comment by hotice** [comment]
Thank you, I'll retest once I get the update!

**Comment by hotice** [comment]
I can confirm that this issue has been fixed in the latest PPA release (1.8.2)
