### ISSUE TITLE
Evernote menu only shows "Settings and Management" and "Exit" entries

### ISSUE THREAD

**Issue by Gerch** [nvbn/everpad#354]
- everpad-provider and everpad console do not report errors
- same issue on Linux Mint KDE 14 and Linux Mint KDE 15
- everpad icon is gray, not green
- Under "Settings and Management" - "Settings" - "Autorize" Button, after Login I can access my Evernote account when I click the "Applications" link on the bottom.
  I can i.e. click the Notices button and see all my notices
- Wenn I call everpad --create on the console the following errors are displayed
  Traceback (most recent call last):
  File "/usr/bin/everpad", line 9, in <module>
    load_entry_point('everpad==2.5dev', 'gui_scripts', 'everpad')()
  File "/usr/lib/pymodules/python2.7/everpad/pad/indicator.py", line 318, in main
    pad.create()
  File "/usr/lib/pymodules/python2.7/everpad/tools.py", line 32, in wrapper
    return getattr(self.**interface, name)(_args, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/dbus/proxies.py", line 70, in __call**
    return self._proxy_method(_args, *_keywords)
  File "/usr/lib/python2.7/dist-packages/dbus/proxies.py", line 145, in __call__
    *_keywords)
  File "/usr/lib/python2.7/dist-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
  dbus.exceptions.DBusException: org.freedesktop.DBus.Python.AttributeError: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/dbus/service.py", line 707, in _message_cb
    retval = candidate_method(self, *args, *_keywords)
  File "/usr/lib/pymodules/python2.7/everpad/provider/service.py", line 268, in create_note
    dbus_note.give_to_obj(note)
  File "/usr/lib/pymodules/python2.7/everpad/basetypes.py", line 55, in give_to_obj
    setattr(obj, field[0], val)
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/attributes.py", line 155, in **set**
    instance_dict(instance), value, None)
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/attributes.py", line 697, in set
    value = self.fire_replace_event(state, dict_, value, old, initiator)
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/attributes.py", line 717, in fire_replace_event
    value = fn(state, value, previous, initiator or self)
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/attributes.py", line 1000, in emit_backref_from_scalar_set_event
    child_state, child_dict = instance_state(child),\
  AttributeError: 'dbus.Int32' object has no attribute '_sa_instance_state'
- When I call everpad --all-notes on the console I get a window with no notes. Clicking on +Note results in the same error as above

**Comment by cgwennael** [comment]
Same symptoms on Linux Mint 15 Xfce Edition 64bit
- I can Authorise but nothing else.
- If I lauch Everpad in console : "sni-qt/4356" WARN  22:37:22.174 void StatusNotifierItemFactory::connectToSnw() Invalid interface to SNW_SERVICE
- If I execute everpad -createe : Traceback (most recent call last):
  File "/usr/bin/everpad", line 9, in <module>
    load_entry_point('everpad==2.5dev', 'gui_scripts', 'everpad')()
  File "/usr/lib/pymodules/python2.7/everpad/pad/indicator.py", line 318, in main
    pad.create()
  File "/usr/lib/pymodules/python2.7/everpad/tools.py", line 32, in wrapper
    return getattr(self.**interface, name)(_args, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/dbus/proxies.py", line 70, in __call**
    return self._proxy_method(_args, *_keywords)
  File "/usr/lib/python2.7/dist-packages/dbus/proxies.py", line 145, in __call__
    *_keywords)
  File "/usr/lib/python2.7/dist-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
  dbus.exceptions.DBusException: org.freedesktop.DBus.Python.AttributeError: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/dbus/service.py", line 707, in _message_cb
    retval = candidate_method(self, *args, *_keywords)
  File "/usr/lib/pymodules/python2.7/everpad/provider/service.py", line 268, in create_note
    dbus_note.give_to_obj(note)
  File "/usr/lib/pymodules/python2.7/everpad/basetypes.py", line 55, in give_to_obj
    setattr(obj, field[0], val)
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/attributes.py", line 155, in **set**
    instance_dict(instance), value, None)
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/attributes.py", line 697, in set
    value = self.fire_replace_event(state, dict_, value, old, initiator)
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/attributes.py", line 717, in fire_replace_event
    value = fn(state, value, previous, initiator or self)
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/attributes.py", line 1000, in emit_backref_from_scalar_set_event
    child_state, child_dict = instance_state(child),\
  AttributeError: 'dbus.Int32' object has no attribute '_sa_instance_state'

**Comment by cgwennael** [comment]
After a fresh install from source :

Traceback (most recent call last):
  File "/usr/local/bin/everpad", line 9, in <module>
    load_entry_point('everpad==2.5dev', 'gui_scripts', 'everpad')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 343, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2307, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2013, in load
    entry = **import**(self.module_name, globals(),globals(), ['**name**'])
  File "/usr/local/lib/python2.7/dist-packages/everpad-2.5dev-py2.7.egg/everpad/pad/indicator.py", line 3, in <module>
    from PySide.QtCore import Slot, QTranslator, QLocale, Signal, QSettings, QT_TRANSLATE_NOOP, QLibraryInfo
ImportError: libpyside-python2.7.so.1.2: cannot open shared object file: No such file or directory
