### ISSUE TITLE
Random Crash of Provider

### ISSUE THREAD

**Issue by FarMcKon** [nvbn/everpad#356]
"""
The crashed program seems to use third-party or local libraries:

/usr/local/lib/python2.7/dist-packages/Crypto/Cipher/_AES.so
/usr/local/lib/python2.7/dist-packages/Crypto/Util/strxor.so
/usr/local/lib/python2.7/dist-packages/Crypto/Util/_counter.so

It is highly recommended to check if the problem persists without those first.

Do you want to continue the report process anyway?
"""

From the command line (run as 'everpad-provider --verbose' ) 
"""
Note Getting Started remote
Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.7/everpad/provider/sync.py", line 458, in run
    self.perform()
  File "/usr/lib/pymodules/python2.7/everpad/provider/sync.py", line 489, in perform
    if self._need_to_update():
  File "/usr/lib/pymodules/python2.7/everpad/provider/sync.py", line 74, in _need_to_update
    update_count = self.note_store.getSyncState(self.auth_token).updateCount
  File "/usr/lib/pymodules/python2.7/evernote/edam/notestore/NoteStore.py", line 2440, in getSyncState
    return self.recv_getSyncState()
  File "/usr/lib/pymodules/python2.7/evernote/edam/notestore/NoteStore.py", line 2451, in recv_getSyncState
    (fname, mtype, rseqid) = self._iprot.readMessageBegin()
  File "/usr/lib/pymodules/python2.7/thrift/protocol/TBinaryProtocol.py", line 126, in readMessageBegin
    sz = self.readI32()
  File "/usr/lib/pymodules/python2.7/thrift/protocol/TBinaryProtocol.py", line 203, in readI32
    buff = self.trans.readAll(4)
  File "/usr/lib/pymodules/python2.7/thrift/transport/TTransport.py", line 63, in readAll
    raise EOFError()
EOFError
""""

**Comment by simone-zero12** [comment]
+1
Same issue for me.
