### ISSUE TITLE
How to install ubuntu 13.10 ?

### ISSUE THREAD

**Issue by delister** [nvbn/everpad#359]
http://ppa.launchpad.net/nvbn-rm/ppa/ubuntu/dists/saucy/main/binary-amd64/Packages  404  Not Found

http://ppa.launchpad.net/nvbn-rm/ppa/ubuntu/dists/saucy/main/binary-i386/Packages  404  Not Found

**Comment by diogomatsubara** [comment]
I have built packages for raring and saucy on my PPA: https://launchpad.net/~matsubara/+archive/everpad
It's built from a import of the trunk branch from github.

**Comment by delister** [comment]
not run everpad:
Traceback (most recent call last):
  File "/usr/bin/everpad", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2805, in <module>
    working_set.require(**requires**)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 696, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 594, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: PySide

P.S. everpad 64x

**Comment by shuhikari** [comment]
Have  you tried to compile it from the source?

**Comment by stuartlangridge** [comment]
I'm running on 13.10, upgraded from 13.04, and I'm using the normal PPA, and everpad (the raring version) doesn't work in saucy; evrpad-provider crashes and the indicator has no menu.

**Comment by diogomatsubara** [comment]
Stuart, what error do you get? Could you try the package in my PPA and see if it works?

Cheers

**Comment by diogomatsubara** [comment]
delister, do you get that error installing the package from my PPA? Could you paste the full installation log?

**Comment by raphaelsuzuki** [comment]
Diogo, I installed Everpad from your ppa and it is returning the same error delister posted.

**Comment by diogomatsubara** [comment]
Thanks for testing the package guys. I was able to reproduce the issue. One workaround is to sudo pip install pyside and everpad works again (make sure pyside_postinstally.py -install script runs successfully). I'm not sure why the ubuntu packaged version of pyside is not being found by everpad. Something to do with everpad's setuptools use, perhaps? Any ideas?

**Comment by real-cluse** [comment]
@diogomatsubara 
I installed 'python-pip' and 'cmake'. 
Then I run 'sudo pip install pyside' and came into this error. 

Python architecture is 64bit
qmake: could not find a Qt installation of ''
Failed to query the Qt version with qmake /usr/bin/qmake

Now what do I should do?

**Comment by diogomatsubara** [comment]
You'll also need the following packages installed: qt4-qmake libxml2-dev libxslt1-dev python-dev
Can you try again and let me know?

**Comment by real-cluse** [comment]
@diogomatsubara 
After I installed what you said I tried but the same error came out.
Here's the whole log. 

https://www.dropbox.com/s/47zf0t9osuousq4/pip.log

**Comment by diogomatsubara** [comment]
@real-cluse: Looks like you still need to install the package that provides qmake

**Comment by magowiz** [comment]
I tried the solution proposed using sudo pip install pyside but it fails on configure phase , here is the last part of the log : 
-- Detecting CXX compiler ABI info - done

CMake Warning at /usr/share/cmake-2.8/Modules/FindQt4.cmake:657 (message):

  /usr/bin/qmake-qt4 reported QT_INSTALL_LIBS as "/usr/lib/x86_64-linux-gnu"

  but QtCore could not be found there.  Qt is NOT installed correctly for the

  target build environment.

Call Stack (most recent call first):

  CMakeLists.txt:9 (find_package)

-- Looking for Q_WS_X11

-- Looking for Q_WS_X11 - not found

-- Looking for Q_WS_WIN

-- Looking for Q_WS_WIN - not found

-- Looking for Q_WS_QWS

-- Looking for Q_WS_QWS - not found

-- Looking for Q_WS_MAC

-- Looking for Q_WS_MAC - not found

CMake Error at /usr/share/cmake-2.8/Modules/FindQt4.cmake:1032 (set_property):

  set_property could not find TARGET Qt4::QtCore.  Perhaps it has not yet

  been created.

Call Stack (most recent call first):

  CMakeLists.txt:9 (find_package)

CMake Error at /usr/share/cmake-2.8/Modules/FindQt4.cmake:1037 (set_property):

  set_property could not find TARGET Qt4::QtCore.  Perhaps it has not yet

  been created.

Call Stack (most recent call first):

  CMakeLists.txt:9 (find_package)

CMake Error at /usr/share/cmake-2.8/Modules/FindQt4.cmake:1040 (set_property):

  set_property could not find TARGET Qt4::QtCore.  Perhaps it has not yet

  been created.

Call Stack (most recent call first):

  CMakeLists.txt:9 (find_package)

-- Could NOT find Qt4 (missing:  QT_MOC_EXECUTABLE QT_RCC_EXECUTABLE QT_UIC_EXECUTABLE QT_INCLUDE_DIR QT_LIBRARY_DIR QT_QTCORE_LIBRARY) (found suitable version "4.8.4", minimum required is "4.5.0")

-- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython2.7.so (found suitable version "2.7.5+", minimum required is "2.6")

-- Found LibXml2: /usr/lib/x86_64-linux-gnu/libxml2.so (found suitable version "2.9.1", minimum required is "2.6.32")

-- Found LibXslt: /usr/lib/x86_64-linux-gnu/libxslt.so (found suitable version "1.1.28", minimum required is "1.1.19")

Qt QTGUI library not found.

Qt QTXML library not found.

Qt QTCORE library not found.

-- sphinx-build - not found! doc target disabled

CMake Warning at CMakeLists.txt:127 (message):

  Some dependencies were not found, shiboken generator compilation disabled!

-- Configuring incomplete, errors occurred!

error: Error configuring shiboken

---

Cleaning up...
Command /usr/bin/python -c "import setuptools;**file**='/tmp/pip_build_root/pyside/setup.py';exec(compile(open(**file**).read().replace('\r\n', '\n'), **file**, 'exec'))" install --record /tmp/pip-GekO3J-record/install-record.txt --single-version-externally-managed failed with error code 1 in /tmp/pip_build_root/pyside
Storing complete log in /home/magowiz/.pip/pip.log

**Comment by delister** [comment]
Sorry did not have time to look here. Thanks to all the previous problem was solved. Now when you run here this error:
max@max:~$ everpad
Traceback (most recent call last):
  File "/usr/bin/everpad", line 9, in <module>
    load_entry_point('everpad==2.5dev', 'gui_scripts', 'everpad')()
  File "/usr/lib/pymodules/python2.7/everpad/pad/indicator.py", line 357, in main
    pad = get_pad()
  File "/usr/lib/pymodules/python2.7/everpad/tools.py", line 39, in wrapper
    return InterfaceWrapper(partial(fnc, _args, *_kwrags))
  File "/usr/lib/pymodules/python2.7/everpad/tools.py", line 15, in **init**
    self.**load()
  File "/usr/lib/pymodules/python2.7/everpad/tools.py", line 18, in __load
    self.__interface = self.__get()
  File "/usr/lib/pymodules/python2.7/everpad/tools.py", line 55, in get_pad
    pad = bus.get_object("com.everpad.App", "/EverpadService")
  File "/usr/lib/python2.7/dist-packages/dbus/bus.py", line 241, in get_object
    follow_name_owner_changes=follow_name_owner_changes)
  File "/usr/lib/python2.7/dist-packages/dbus/proxies.py", line 248, in __init**
    self._named_service = conn.activate_name_owner(bus_name)
  File "/usr/lib/python2.7/dist-packages/dbus/bus.py", line 180, in activate_name_owner
    self.start_service_by_name(bus_name)
  File "/usr/lib/python2.7/dist-packages/dbus/bus.py", line 278, in start_service_by_name
    'su', (bus_name, flags)))
  File "/usr/lib/python2.7/dist-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NoReply: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.

**Comment by tklinge** [comment]
You need to install build-essential and qt4-default.

**Comment by HendrikPetertje** [comment]
The current error in ppa is the fact that every ppa lists diffrent ubuntu version distro's While Everpad has ubuntu 13.04 listed and an installer included that requires ubuntu 13.04, the developer hasn't yet made an installer / version compatible with ubuntu 13.10. Compiling from source sounds good, but Ubuntu changed how the launcher handles applications and application searches. The errors when compiling from source could be there because Everpad had a search applet-function in the deprecated Ubuntu 13.04 launcher...

**Comment by brunodahora** [comment]
@delister didi you solve your problem?
I'm stuck in the same step as yours.
Does anybody know what to do now?

**Comment by luisdavim** [comment]
there is now a version of everpd that works on 13.10 on the official PPA ppa:nvbn-rm/ppa

**Comment by stuartlangridge** [comment]
I've just upgraded, and tried starting the new everpad. I get a system menu (indicator): cilcking it shows this in the terminal:

Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.7/everpad/pad/indicator.py", line 78, in update
    20, Note.ORDER_UPDATED_DESC, 1,
  File "/usr/lib/pymodules/python2.7/everpad/tools.py", line 32, in wrapper
    return getattr(self.**interface, name)(_args, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/dbus/proxies.py", line 70, in __call**
    return self._proxy_method(_args, *_keywords)
  File "/usr/lib/python2.7/dist-packages/dbus/proxies.py", line 145, in __call__
    *_keywords)
  File "/usr/lib/python2.7/dist-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Python.sqlalchemy.exc.InvalidRequestError: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/dbus/service.py", line 707, in _message_cb
    retval = candidate_method(self, *args, *_keywords)
  File "/usr/lib/pymodules/python2.7/everpad/provider/service.py", line 101, in find_notes
    qs = self.sq(Note).filter(and_(
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 1107, in query
    return self._query_cls(entities, self, **kwargs)
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 115, in __init__
    self._set_entities(entities)
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 124, in _set_entities
    self._set_entity_selectables(self._entities)
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 157, in _set_entity_selectables
    ent.setup_entity(*d[entity])
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2861, in setup_entity
    self._with_polymorphic = ext_info.with_polymorphic_mappers
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/util/langhelpers.py", line 612, in __get__
    obj.**dict**[self.**name**] = result = self.fget(obj)
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/mapper.py", line 1458, in _with_polymorphic_mappers
    configure_mappers()
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/mapper.py", line 2150, in configure_mappers
    raise e
InvalidRequestError: One or more mappers failed to initialize - can't proceed with initialization of other mappers.  Original exception was: Can't determine relationship direction for relationship 'Note.conflict_parent' - foreign key columns within the join condition are present in both the parent and the child's mapped tables.  Ensure that only those columns referring to a parent column are marked as foreign, either via the foreign() annotation or via the foreign_keys argument.
