### ISSUE TITLE
Everpad not working in Ubuntu 13.10

### ISSUE THREAD

**Issue by alexandrev** [nvbn/everpad#369]
Everpad is not working in my Ubuntu 13.10 installation. When I start everpad-provider nothing happend. I also tried everpad-provider --verbose but no log traces shows up.

Anyone has tested this application in the new Ubuntu 13.10 version? How can i get more information about the error I am facing?

Thank you very much for your support.

**Comment by int0x191f2** [comment]
I'm assuming that you compiled Everpad from source because I don't see a deb in the PPA. After you run everpad-provider, try to run "ps -e | grep ever" and see if the process is running.

**Comment by alexandrev** [comment]
The process was running. After I removed the .everpad folder of my home, when I running everpad-provider --verbose I can see this:

everpad-provider --verbose
Traceback (most recent call last):
  File "/usr/bin/everpad-provider", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2805, in <module>
    working_set.require(**requires**)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 696, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 594, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: PySide

I'm using the compiled version of the raring repository.

I hope all that new info can help to solve the problem.

**Comment by int0x191f2** [comment]
It looks like pyside is missing. Try a "sudo pip install pyside"

**Comment by bluesky8318** [comment]
ppa is not aviable

**Comment by metalbrick** [comment]
Same Issue here, and I got the debug information as follow:

Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.7/everpad/provider/daemon.py", line 54, in on_remove_authenticated
    session.query(models.Note).delete(
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 1107, in query
    return self._query_cls(entities, self, **kwargs)
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 115, in __init__
    self._set_entities(entities)
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 124, in _set_entities
    self._set_entity_selectables(self._entities)
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 157, in _set_entity_selectables
    ent.setup_entity(*d[entity])
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2861, in setup_entity
    self._with_polymorphic = ext_info.with_polymorphic_mappers
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/util/langhelpers.py", line 612, in __get__
    obj.**dict**[self.**name**] = result = self.fget(obj)
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/mapper.py", line 1458, in _with_polymorphic_mappers
    configure_mappers()
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/mapper.py", line 2153, in configure_mappers
    mapper._post_configure_properties()
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/mapper.py", line 1275, in _post_configure_properties
    prop.init()
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/interfaces.py", line 231, in init
    self.do_init()
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/properties.py", line 1028, in do_init
    self._setup_join_conditions()
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/properties.py", line 1102, in _setup_join_conditions
    can_be_synced_fn=self._columns_are_mapped
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/relationships.py", line 122, in __init__
    self._determine_direction()
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/relationships.py", line 686, in _determine_direction
    "via the foreign_keys argument." % self.prop)
sqlalchemy.exc.ArgumentError: Can't determine relationship direction for relationship 'Note.conflict_parent' - foreign key columns within the join condition are present in both the parent and the child's mapped tables.  Ensure that only those columns referring to a parent column are marked as foreign, either via the foreign() annotation or via the foreign_keys argument.

**Comment by trivoallan** [comment]
This is similar to #300

**Comment by arpagon** [comment]
the provider runs Ok (for me), 

I have problem whit everpad-lens

non-root$ everpad-lens 
Traceback (most recent call last):
  File "/usr/bin/everpad-lens", line 9, in <module>
    load_entry_point('everpad==2.5dev', 'console_scripts', 'everpad-lens')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 343, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2309, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2015, in load
    entry = **import**(self.module_name, globals(),globals(), ['**name**'])
  File "/usr/lib/pymodules/python2.7/everpad/specific/unity/lens.py", line 3, in <module>
    from singlet.lens import SingleScopeLens, ListViewCategory
  File "/usr/lib/python2.7/dist-packages/singlet/lens/**init**.py", line 1, in <module>
    from singlet.lens.base import (
  File "/usr/lib/python2.7/dist-packages/singlet/lens/base.py", line 140, in <module>
    class SingleScopeLens(Lens):
  File "/usr/lib/python2.7/dist-packages/singlet/lens/base.py", line 57, in **new**
    if isinstance(a, Unity.Scope):
  File "/usr/lib/python2.7/dist-packages/gi/module.py", line 313, in **getattr**
    return getattr(self._introspection_module, name)
  File "/usr/lib/python2.7/dist-packages/gi/module.py", line 134, in __getattr__
    self.**name**, name))
AttributeError: 'gi.repository.Unity' object has no attribute 'Scope'

**Comment by metalbrick** [comment]
@arpagon Are you using Ubuntu 13.10 ? Do you install by package or compile yourself ?

**Comment by Cybolic** [comment]
@metalbrick I get the same output as arpagon and I'm running it from the raring packages in the PPA.

**Comment by khurshid-alam** [comment]
Same error as alexandrev. I compiled it from source (after cloning from github repo.) https://launchpad.net/~khurshid-alam/+archive/experimental-build/+files/everpad_2.5.6ubuntu1_i386.deb. 

I even tried to install python-pyside. But that didn't help. Downgrading python-sqlalchemy to 0.7.9 did not help either. Please fix it as soon as possible. 

Here is the error:

```
Traceback (most recent call last):
  File "/usr/bin/everpad", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2805, in <module>
    working_set.require(__requires__)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 696, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 594, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: PySide
```

**Comment by nvbn** [comment]
Package for saucy pushed to ppa.

**Comment by trivoallan** [comment]
I still get the error : 

```
Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.7/everpad/pad/indicator.py", line 76, in update
    20, Note.ORDER_UPDATED_DESC, 1,
  File "/usr/lib/pymodules/python2.7/everpad/tools.py", line 32, in wrapper
    return getattr(self.__interface, name)(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/dbus/proxies.py", line 70, in __call__
    return self._proxy_method(*args, **keywords)
  File "/usr/lib/python2.7/dist-packages/dbus/proxies.py", line 145, in __call__
    **keywords)
  File "/usr/lib/python2.7/dist-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Python.sqlalchemy.exc.InvalidRequestError: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/dbus/service.py", line 707, in _message_cb
    retval = candidate_method(self, *args, **keywords)
  File "/usr/lib/pymodules/python2.7/everpad/provider/service.py", line 101, in find_notes
    qs = self.sq(Note).filter(and_(
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 1107, in query
    return self._query_cls(entities, self, **kwargs)
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 115, in __init__
    self._set_entities(entities)
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 124, in _set_entities
    self._set_entity_selectables(self._entities)
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 157, in _set_entity_selectables
    ent.setup_entity(*d[entity])
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2861, in setup_entity
    self._with_polymorphic = ext_info.with_polymorphic_mappers
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/util/langhelpers.py", line 612, in __get__
    obj.__dict__[self.__name__] = result = self.fget(obj)
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/mapper.py", line 1458, in _with_polymorphic_mappers
    configure_mappers()
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/mapper.py", line 2150, in configure_mappers
    raise e
InvalidRequestError: One or more mappers failed to initialize - can't proceed with initialization of other mappers.  Original exception was: Can't determine relationship direction for relationship 'Note.conflict_parent' - foreign key columns within the join condition are present in both the parent and the child's mapped tables.  Ensure that only those columns referring to a parent column are marked as foreign, either via the foreign() annotation or via the foreign_keys argument.
```

```
$ aptitude show everpad | grep Version
Version : 2.5.6-0~saucy
```

**Comment by Cybolic** [comment]
I can confirm trivoallan's output; I'm getting the exact same error with that package (amd64).

**Comment by BlackDex** [comment]
Same error here, confirmed. Freshly installed Ubuntu 13.10 x64 in a VM.

**Comment by luisdavim** [comment]
I have the same error as  trivoallan and I'm on amd64

**Comment by metalbrick** [comment]
I delete all the obsolete package files of everpad and PySide, and install directly from the ppa, still not get it work.

The everpad-provider gave no output at all, the debug information of everpad as follows:

Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.7/everpad/pad/indicator.py", line 76, in update
    20, Note.ORDER_UPDATED_DESC, 1,
  File "/usr/lib/pymodules/python2.7/everpad/tools.py", line 32, in wrapper
    return getattr(self.**interface, name)(_args, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/dbus/proxies.py", line 70, in __call**
    return self._proxy_method(_args, *_keywords)
  File "/usr/lib/python2.7/dist-packages/dbus/proxies.py", line 145, in __call__
    *_keywords)
  File "/usr/lib/python2.7/dist-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Python.sqlalchemy.exc.InvalidRequestError: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/dbus/service.py", line 707, in _message_cb
    retval = candidate_method(self, *args, *_keywords)
  File "/usr/lib/pymodules/python2.7/everpad/provider/service.py", line 101, in find_notes
    qs = self.sq(Note).filter(and_(
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 1107, in query
    return self._query_cls(entities, self, **kwargs)
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 115, in __init__
    self._set_entities(entities)
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 124, in _set_entities
    self._set_entity_selectables(self._entities)
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 157, in _set_entity_selectables
    ent.setup_entity(*d[entity])
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2861, in setup_entity
    self._with_polymorphic = ext_info.with_polymorphic_mappers
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/util/langhelpers.py", line 612, in __get__
    obj.**dict**[self.**name**] = result = self.fget(obj)
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/mapper.py", line 1458, in _with_polymorphic_mappers
    configure_mappers()
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/mapper.py", line 2150, in configure_mappers
    raise e
InvalidRequestError: One or more mappers failed to initialize - can't proceed with initialization of other mappers.  Original exception was: Can't determine relationship direction for relationship 'Note.conflict_parent' - foreign key columns within the join condition are present in both the parent and the child's mapped tables.  Ensure that only those columns referring to a parent column are marked as foreign, either via the foreign() annotation or via the foreign_keys argument.

**Comment by iGhost** [comment]
The same error. Version: 2.5.6-0~saucy. Ubuntu 13.10 x64

**Comment by ferencsarai** [comment]
From syslog (starting  everpad-provider) :

[  396.414164] everpad-provide[3008]: segfault at 8 ip 00007fc069a65b34 sp 00007fff9e474860 error 4 in libdbus-1.so.3.7.4[7fc069a40000+44000]

[  424.070214] everpad-provide[3030]: segfault at 2929000 ip 00007f867365116c sp 00007fff81fe4378 error 4 in libc-2.17.so[7f8673502000+1bd000]

**Comment by Levan7** [comment]
Just installed everpad from a ppa and this is what I got 

```
Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.7/everpad/pad/indicator.py", line 76, in update
    20, Note.ORDER_UPDATED_DESC, 1,
  File "/usr/lib/pymodules/python2.7/everpad/tools.py", line 32, in wrapper
    return getattr(self.__interface, name)(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/dbus/proxies.py", line 70, in __call__
    return self._proxy_method(*args, **keywords)
  File "/usr/lib/python2.7/dist-packages/dbus/proxies.py", line 145, in __call__
    **keywords)
  File "/usr/lib/python2.7/dist-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Python.sqlalchemy.exc.InvalidRequestError: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/dbus/service.py", line 707, in _message_cb
    retval = candidate_method(self, *args, **keywords)
  File "/usr/lib/pymodules/python2.7/everpad/provider/service.py", line 101, in find_notes
    qs = self.sq(Note).filter(and_(
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 1107, in query
    return self._query_cls(entities, self, **kwargs)
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 115, in __init__
    self._set_entities(entities)
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 124, in _set_entities
    self._set_entity_selectables(self._entities)
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 157, in _set_entity_selectables
    ent.setup_entity(*d[entity])
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2861, in setup_entity
    self._with_polymorphic = ext_info.with_polymorphic_mappers
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/util/langhelpers.py", line 612, in __get__
    obj.__dict__[self.__name__] = result = self.fget(obj)
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/mapper.py", line 1458, in _with_polymorphic_mappers
    configure_mappers()
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/mapper.py", line 2150, in configure_mappers
    raise e
InvalidRequestError: One or more mappers failed to initialize - can't proceed with initialization of other mappers.  Original exception was: Can't determine relationship direction for relationship 'Note.conflict_parent' - foreign key columns within the join condition are present in both the parent and the child's mapped tables.  Ensure that only those columns referring to a parent column are marked as foreign, either via the foreign() annotation or via the foreign_keys argument.
```

full terminal output 
http://slexy.org/view/s20nwCR9QK

strace if you need it
http://slexy.org/view/s21jhZPS4j

**Comment by khurshid-alam** [comment]
I have installed python.pyside from repo `(sudo apt-get install python-pyside)` from repo AND manually installed [python-sqlalchemy0.7.9](https://launchpad.net/ubuntu/raring/i386/python-sqlalchemy/0.7.9-1). Now after installing from ppa it works in saucy. It can authorize & sync note from server. But everpad-lens doesn't work. 

When I run everpad-lens in terminal I get following error:

```
Traceback (most recent call last):
  File "/usr/bin/everpad-lens", line 9, in <module>
    load_entry_point('everpad==2.5dev', 'console_scripts', 'everpad-lens')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 343, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2309, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2015, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/usr/lib/pymodules/python2.7/everpad/specific/unity/lens.py", line 3, in <module>
    from singlet.lens import SingleScopeLens, ListViewCategory
  File "/usr/lib/python2.7/dist-packages/singlet/lens/__init__.py", line 1, in <module>
    from singlet.lens.base import (
  File "/usr/lib/python2.7/dist-packages/singlet/lens/base.py", line 140, in <module>
    class SingleScopeLens(Lens):
  File "/usr/lib/python2.7/dist-packages/singlet/lens/base.py", line 57, in __new__
    if isinstance(a, Unity.Scope):
  File "/usr/lib/python2.7/dist-packages/gi/module.py", line 313, in __getattr__
    return getattr(self._introspection_module, name)
  File "/usr/lib/python2.7/dist-packages/gi/module.py", line 134, in __getattr__
    self.__name__, name))
AttributeError: 'gi.repository.Unity' object has no attribute 'Scope'
```

**Comment by BlackDex** [comment]
I installed the everpad 2.5.6 version, and downgrade python-sqlalchemy and python-sqlalchemy-ext to 0.7.9 and it seems to work now.

**Comment by trivoallan** [comment]
That did not do the trick for me : 

```
trivoallan@trivoallan-Latitude-E6430:~/tmp$ aptitude show everpad python-sqlalchemy python-sqlalchemy-ext | grep Version
Version : 2.5.6-0~saucy
Version : 0.7.9-1
Version : 0.7.9-1
trivoallan@trivoallan-Latitude-E6430:~/tmp$ everpad
Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.7/everpad/pad/indicator.py", line 76, in update
    20, Note.ORDER_UPDATED_DESC, 1,
  File "/usr/lib/pymodules/python2.7/everpad/tools.py", line 32, in wrapper
    return getattr(self.__interface, name)(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/dbus/proxies.py", line 70, in __call__
    return self._proxy_method(*args, **keywords)
  File "/usr/lib/python2.7/dist-packages/dbus/proxies.py", line 145, in __call__
    **keywords)
  File "/usr/lib/python2.7/dist-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Python.sqlalchemy.exc.InvalidRequestError: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/dbus/service.py", line 707, in _message_cb
    retval = candidate_method(self, *args, **keywords)
  File "/usr/lib/pymodules/python2.7/everpad/provider/service.py", line 101, in find_notes
    qs = self.sq(Note).filter(and_(
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 1107, in query
    of objects which involve existing database queries,
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 115, in __init__
    entity_wrapper(self, ent)
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 124, in _set_entities
    self._mapper_adapter_map = d = self._mapper_adapter_map.copy()
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 157, in _set_entity_selectables
    for m in m2.iterate_to_root():
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2861, in setup_entity
    for_update = {'read': 'read',
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/util/langhelpers.py", line 612, in __get__
    [self._il_addtl])
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/mapper.py", line 1458, in _with_polymorphic_mappers
    return result
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/mapper.py", line 2150, in configure_mappers
InvalidRequestError: One or more mappers failed to initialize - can't proceed with initialization of other mappers.  Original exception was: Can't determine relationship direction for relationship 'Note.conflict_parent' - foreign key columns within the join condition are present in both the parent and the child's mapped tables.  Ensure that only those columns referring to a parent column are marked as foreign, either via the foreign() annotation or via the foreign_keys argument.
```

**Comment by mgaunard** [comment]
How can I downgrade sqlalchemy to the appropriate version?

**Comment by khurshid-alam** [comment]
@mgaunard Download the deb from here https://launchpad.net/ubuntu/raring/i386/python-sqlalchemy/0.7.9-1

**Comment by Cybolic** [comment]
khurshid-alam's advice worked, even without installing pyside. Lens still doesn't work, as described.

**Comment by gperr1** [comment]
khurshid-alam's advice did the trick for me also.

**Comment by metalbrick** [comment]
@khurshid-alam your workaround did the trick for me, thanks.

Then it seems the issue of everpad is to do with either the conflict between sqlalchemy and everpad or the latest sqlalchmey itself.
Wonder if there anyone can figure out what cause the problem with everpad-lens.

**Comment by iGhost** [comment]
There is seems a more strict foreign key standards in sqlalchemy 0.8.\* and that is a problem

**Comment by mgaunard** [comment]
The problem is that everpad doesn't specify the relationships between its keys correctly. Apparently the everpad devs do not want to fix that so all we can do is rollback to an old version of sqlachemy that was more tolerant.

**Comment by brunodahora** [comment]
@khurshid-alam did you get your everpad-lens problem fixed?
I was able to load everpad, but not the lens.

**Comment by khurshid-alam** [comment]
@brunodahora No. Everpad-lens is still NOT working for me. 

As python-library for unity-scope (python-unity-singlet) hasn't been changed since quantal , I think the problem is in everpad-side. Someone, with advance knowledge in python, can help here.

**Comment by aapthorp** [comment]
I'm not sure if I have the same issue as this. After upgrade of Ubuntu and everpad, everpad doesn't seem to respond.

If I try running from the command line with --verbose I get no output at all and the everpad client doesn't launch, just hangs having entered the command.

**Comment by nvbn** [comment]
I pushed version works with sqlalchemy 0.8.x in ppa. Lens still not working because https://bugs.launchpad.net/singlet/+bug/1248050

**Comment by Levan7** [comment]
Thank you @nvbn now it works for me :)

**Comment by luisdavim** [comment]
Thank you @nvbn now it's working :+1:

**Comment by iGhost** [comment]
Thank you Vladimir, you are great! Nice work!

**Comment by alexandrev** [comment]
Nothing is working for me. I'm trying reinstalling with the last version of the PPA, and now the error is not the same. Now, I've got the following stacktrace:

Traceback (most recent call last):
  File "/usr/local/bin/everpad", line 9, in <module>
    load_entry_point('everpad==2.5dev', 'gui_scripts', 'everpad')()
  File "/usr/local/lib/python2.7/dist-packages/everpad-2.5dev-py2.7.egg/everpad/pad/indicator.py", line 357, in main
    pad = get_pad()
  File "/usr/local/lib/python2.7/dist-packages/everpad-2.5dev-py2.7.egg/everpad/tools.py", line 39, in wrapper
    return InterfaceWrapper(partial(fnc, _args, *_kwrags))
  File "/usr/local/lib/python2.7/dist-packages/everpad-2.5dev-py2.7.egg/everpad/tools.py", line 15, in **init**
    self.**load()
  File "/usr/local/lib/python2.7/dist-packages/everpad-2.5dev-py2.7.egg/everpad/tools.py", line 18, in __load
    self.__interface = self.__get()
  File "/usr/local/lib/python2.7/dist-packages/everpad-2.5dev-py2.7.egg/everpad/tools.py", line 55, in get_pad
    pad = bus.get_object("com.everpad.App", "/EverpadService")
  File "/usr/lib/python2.7/dist-packages/dbus/bus.py", line 241, in get_object
    follow_name_owner_changes=follow_name_owner_changes)
  File "/usr/lib/python2.7/dist-packages/dbus/proxies.py", line 248, in __init**
    self._named_service = conn.activate_name_owner(bus_name)
  File "/usr/lib/python2.7/dist-packages/dbus/bus.py", line 180, in activate_name_owner
    self.start_service_by_name(bus_name)
  File "/usr/lib/python2.7/dist-packages/dbus/bus.py", line 278, in start_service_by_name
    'su', (bus_name, flags)))
  File "/usr/lib/python2.7/dist-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NoReply: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.

Any help? 

Thanks in advance

**Comment by carlba** [comment]
I also have the same issue with the lens. It would be great if it could be fixed since it is the only way to search your existing notes.

**Comment by mgaunard** [comment]
I'm still having the issue with sqlalchemy as of latest ppa.

InvalidRequestError: One or more mappers failed to initialize - can't proceed with initialization of other mappers.  Original exception was: Can't determine relationship direction for relationship 'Note.conflict_parent' - foreign key columns within the join condition are present in both the parent and the child's mapped tables.  Ensure that only those columns referring to a parent column are marked as foreign, either via the foreign() annotation or via the foreign_keys argument.

**Comment by domguinard** [comment]
Any news on this? Did anyone get the lenses working?

**Comment by eugenegordeiev** [comment]
Still waiting for a solution :(

**Comment by facusrod** [comment]
https://github.com/nvbn/everpad/issues/416 see this!
