### ISSUE TITLE
App-indicator frozen or crippled in Ubuntu 13.10. Everpad not working.

### ISSUE THREAD

**Issue by O-Gopal** [nvbn/everpad#371]
I had Everpad working in 12.04. Then I did a clean install to 13.10 (but preserving my data). I then installed Everpad from the Launchpad PPA. 

Now:

The app-indicator shows up, but is frozen. Clicking on it highlights it, but nothing more. Or sometimes (I'm not sure when -- after killing the app and restarting it?) either right-clicking or left-clicking (the result is the same) will show the "settings and management" window, but nothing further happens. 

Running from the command line, I tried "everpad --all-notes." This resulted in the following error message:

"sni-qt/3675" WARN  11:58:17.366 void StatusNotifierItemFactory::connectToSnw() Invalid interface to SNW_SERVICE 

Then, after some minutes, the "all-notes" window showed up (with no notes in it) but with no functionality. Full message:

"sni-qt/3675" WARN  11:58:17.366 void StatusNotifierItemFactory::connectToSnw() Invalid interface to SNW_SERVICE 
ERROR:dbus.proxies:Introspect error on :1.2:/EverpadProvider: dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NoReply: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.
ERROR:dbus.proxies:Introspect error on :1.2:/EverpadProvider: dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NoReply: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.
Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.7/everpad/pad/list.py", line 98, in showEvent
    self._reload_data()
  File "/usr/lib/pymodules/python2.7/everpad/pad/list.py", line 368, in _reload_data
    self._reload_notebooks_list(self._current_notebook)
  File "/usr/lib/pymodules/python2.7/everpad/pad/list.py", line 380, in _reload_notebooks_list
    for notebook_struct in self.app.provider.list_notebooks():
  File "/usr/lib/pymodules/python2.7/everpad/tools.py", line 32, in wrapper
    return getattr(self.__interface, name)(_args, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/dbus/proxies.py", line 70, in __call__
    return self._proxy_method(_args, *_keywords)
  File "/usr/lib/python2.7/dist-packages/dbus/proxies.py", line 145, in __call__
    *_keywords)
  File "/usr/lib/python2.7/dist-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Python.sqlalchemy.exc.InvalidRequestError: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/dbus/service.py", line 707, in _message_cb
    retval = candidate_method(self, *args, *_keywords)
  File "/usr/lib/pymodules/python2.7/everpad/provider/service.py", line 120, in list_notebooks
    self.sq(Notebook).filter(Notebook.action != ACTION_DELETE).order_by(Notebook.name))
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 1107, in query
    return self._query_cls(entities, self, **kwargs)
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 115, in __init__
    self._set_entities(entities)
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 124, in _set_entities
    self._set_entity_selectables(self._entities)
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 157, in _set_entity_selectables
    ent.setup_entity(*d[entity])
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2861, in setup_entity
    self._with_polymorphic = ext_info.with_polymorphic_mappers
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/util/langhelpers.py", line 612, in __get__
    obj.**dict**[self.**name**] = result = self.fget(obj)
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/mapper.py", line 1458, in _with_polymorphic_mappers
    configure_mappers()
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/mapper.py", line 2150, in configure_mappers
    raise e
InvalidRequestError: One or more mappers failed to initialize - can't proceed with initialization of other mappers.  Original exception was: Can't determine relationship direction for relationship 'Note.conflict_parent' - foreign key columns within the join condition are present in both the parent and the child's mapped tables.  Ensure that only those columns referring to a parent column are marked as foreign, either via the foreign() annotation or via the foreign_keys argument.

**Comment by deckerweb** [comment]
Same here on my desktop maschine that is running 13.10 already...
I cannot update my notebook to 13.10 because of that, I need Everpad working on my daily driver.
Any update or solution would be nice...

**Comment by O-Gopal** [comment]
Now all seems to work for me.
