### ISSUE TITLE
Crash trying to authorise on Ubuntu 12.04 amd64

### ISSUE THREAD

**Issue by esyrett** [nvbn/everpad#372]
Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.7/everpad/pad/management.py", line 254, in change_auth
    'GET')
  File "/usr/lib/python2.7/dist-packages/oauth2/**init**.py", line 682, in request
    connection_type=connection_type)
  File "/usr/lib/python2.7/dist-packages/httplib2/**init**.py", line 1444, in request
    (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
  File "/usr/lib/python2.7/dist-packages/httplib2/__init__.py", line 1196, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "/usr/lib/python2.7/dist-packages/httplib2/__init__.py", line 1132, in _conn_request
    conn.connect()
  File "/usr/lib/python2.7/dist-packages/httplib2/__init__.py", line 889, in connect
    sock.connect((self.host, self.port))
  File "/usr/lib/python2.7/dist-packages/httplib2/socks.py", line 403, in connect
    raise GeneralProxyError((5, _generalerrors[5]))
httplib2.socks.GeneralProxyError: (5, 'bad input')

**Comment by jgomo3** [comment]
@esyrett repeated the issue here: #377
This issue should be closed as #377 has more details from the same author.

**So, follow issue #377!**
