### ISSUE TITLE
Use ppa to install, Got DistributionNotFound: py-oauth2 problem

### ISSUE THREAD

**Issue by skyline75489** [nvbn/everpad#375]
Output is like this:

Traceback (most recent call last):
  File "/usr/local/bin/everpad", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2815, in <module>
    working_set.require(**requires**)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 690, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 588, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: py-oauth2

**Comment by skyline75489** [comment]
After I installed py-oauth2, I got this;
Traceback (most recent call last):
  File "/usr/local/bin/everpad", line 9, in <module>
    load_entry_point('everpad==2.5dev', 'gui_scripts', 'everpad')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 337, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2311, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2017, in load
    entry = **import**(self.module_name, globals(),globals(), ['**name**'])
  File "/usr/local/lib/python2.7/dist-packages/everpad-2.5dev-py2.7.egg/everpad/pad/indicator.py", line 3, in <module>
    from PySide.QtCore import Slot, QTranslator, QLocale, Signal, QSettings, QT_TRANSLATE_NOOP, QLibraryInfo
ImportError: libpyside-python2.7.so.1.2: cannot open shared object file: No such file or directory
