### ISSUE TITLE
Everpad fails to authorise on Ubuntu 12.04 LTS

### ISSUE THREAD

**Issue by esyrett** [nvbn/everpad#377]
Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.7/everpad/pad/management.py", line 254, in change_auth
    'GET')
  File "/usr/lib/python2.7/dist-packages/oauth2/**init**.py", line 682, in request
    connection_type=connection_type)
  File "/usr/lib/python2.7/dist-packages/httplib2/**init**.py", line 1444, in request
    (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
  File "/usr/lib/python2.7/dist-packages/httplib2/__init__.py", line 1196, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "/usr/lib/python2.7/dist-packages/httplib2/__init__.py", line 1132, in _conn_request
    conn.connect()
  File "/usr/lib/python2.7/dist-packages/httplib2/__init__.py", line 889, in connect
    sock.connect((self.host, self.port))
  File "/usr/lib/python2.7/dist-packages/httplib2/socks.py", line 403, in connect
    raise GeneralProxyError((5, _generalerrors[5]))
httplib2.socks.GeneralProxyError: (5, 'bad input')

**Comment by esyrett** [comment]
The line in management.py looks like this:

```
 resp, content = client.request(
            'https://%s/oauth?oauth_callback=' % HOST + urllib.quote('http://everpad/'),
        'GET')
```

The actual URL generated I guess looks like this:

```
https://www.evernote.com/oauth?oauth_callback=http%3A%2F%2Feverpad%2F
```

But when I copy this url into a browser Evernote just throws an error.

I had a look at the developer pages on Evernote, and it says that the first call to authorise should look like this -

```
https://sandbox.evernote.com/oauth?oauth_consumer_key=en_oauth_test&oauth_signature=1ca0956605acc4f2%26&oauth_signature_method=PLAINTEXT&oauth_timestamp=1288364369&oauth_nonce=d3d9446802a44259&oauth_callback=https%3A%2F%2Ffoo.com%2Fsettings%2Findex.php%3Faction%3DoauthCallback
```

So what is the fix?  I don't know enough about the Evernote OAuth process to guess what's going on here.  However, I'd love to be using Everpad, so please could somebody figure this one out.....
