### ISSUE TITLE
[Ubuntu 13.04] Everpad starts with crash, can't create new note, cant' synch

### ISSUE THREAD

**Issue by bosschebol** [nvbn/everpad#378]
When I start Everpad (having installed it today), I get some crash report, however it is starting. But I neither can I create a new note (new stack and notebook work however) nor synch. 

Versions:
everpad --version
Everpad version: 2.5
API version: 6
Schema version: 5

everpad-provider --version
Everpad version: 2.5
API version: 6
Schema version: 5

Crash report when starting everpad-provider (after having killed all running everpad processes):
everpad-provider --verbose
Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.7/everpad/provider/sync.py", line 454, in run
    self.init_network()
  File "/usr/lib/pymodules/python2.7/everpad/provider/sync.py", line 470, in init_network
    self.note_store = get_note_store(self.auth_token)
  File "/usr/lib/pymodules/python2.7/everpad/provider/tools.py", line 65, in get_note_store
    note_store_url = user_store.getNoteStoreUrl(auth_token)
  File "/usr/lib/pymodules/python2.7/evernote/edam/userstore/UserStore.py", line 614, in getNoteStoreUrl
    return self.recv_getNoteStoreUrl()
  File "/usr/lib/pymodules/python2.7/evernote/edam/userstore/UserStore.py", line 637, in recv_getNoteStoreUrl
    raise result.userException
evernote.edam.error.ttypes.EDAMUserException: EDAMUserException(errorCode=9, parameter='password')

Crash report when trying to create new note:
everpad
Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.7/everpad/pad/indicator.py", line 164, in create
    self.app.provider.create_note(note_struct),
  File "/usr/lib/pymodules/python2.7/everpad/tools.py", line 32, in wrapper
    return getattr(self.**interface, name)(_args, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/dbus/proxies.py", line 70, in __call**
    return self._proxy_method(_args, *_keywords)
  File "/usr/lib/python2.7/dist-packages/dbus/proxies.py", line 145, in __call__
    *_keywords)
  File "/usr/lib/python2.7/dist-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Python.AttributeError: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/dbus/service.py", line 707, in _message_cb
    retval = candidate_method(self, *args, *_keywords)
  File "/usr/lib/pymodules/python2.7/everpad/provider/service.py", line 268, in 
create_note
    dbus_note.give_to_obj(note)
  File "/usr/lib/pymodules/python2.7/everpad/basetypes.py", line 55, in give_to_obj
    setattr(obj, field[0], val)
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/attributes.py", line 155, in **set**
    instance_dict(instance), value, None)
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/attributes.py", line 697, in set
    value = self.fire_replace_event(state, dict_, value, old, initiator)
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/attributes.py", line 717, in fire_replace_event
    value = fn(state, value, previous, initiator or self)
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/attributes.py", line 1000, in emit_backref_from_scalar_set_event
    child_state, child_dict = instance_state(child),\
AttributeError: 'dbus.Int32' object has no attribute '_sa_instance_state'

**Comment by bosschebol** [comment]
Okay, I fixed the issue:
For some reasons, it got some account information without asking me (maybe from a previous installation?).
Now I changed it and everything works as a charm...

**Comment by bosschebol** [comment]
Closed.
