### ISSUE TITLE
Cannot launch everpad on a clean Ubuntu 13.10 x64 desktop install

### ISSUE THREAD

**Issue by ChrisMagnuson** [nvbn/everpad#384]
I have just done an Ubuntu 13.10 x64 desktop install and the Everpad app says API version mismatch.

I installed everpad using the following commands:

http://askubuntu.com/questions/362342/install-everpad-on-ubuntu-13-10

sudo add-apt-repository ppa:nvbn-rm/ppa
sudo apt-get update
sudo apt-get install everpad

I have restarted 3 times based on others recommendations and have the following debug output when running the following:

killall everpad everpad-provider everpad-lens

chris@chris-Virtual-Machine:~$ everpad-provider --verbose
ERROR:dbus.proxies:Introspect error on :1.29:/org/freedesktop/secrets/aliases/default: dbus.exceptions.DBusException: org.freedesktop.Secret.Error.NoSuchObject: The '/org/freedesktop/secrets/aliases/default' object does not exist
Traceback (most recent call last):
  File "/usr/bin/everpad-provider", line 9, in <module>
    load_entry_point('everpad==2.5dev', 'console_scripts', 'everpad-provider')()
  File "/usr/lib/pymodules/python2.7/everpad/provider/daemon.py", line 95, in main
    app = ProviderApp(args.verbose, sys.argv)
  File "/usr/lib/pymodules/python2.7/everpad/provider/daemon.py", line 34, in **init**
    if get_auth_token():
  File "/usr/lib/pymodules/python2.7/everpad/provider/tools.py", line 35, in get_auth_token
    return get_keyring().get_password('everpad', 'oauth_token')
  File "/usr/lib/pymodules/python2.7/everpad/specific/**init**.py", line 54, in get_keyring
    import keyring
  File "/usr/lib/python2.7/dist-packages/keyring/**init**.py", line 9, in <module>
    from core import (set_keyring, get_keyring, set_password, get_password,
  File "/usr/lib/python2.7/dist-packages/keyring/core.py", line 166, in <module>
    init_backend()
  File "/usr/lib/python2.7/dist-packages/keyring/core.py", line 65, in init_backend
    keyrings.sort(key = lambda x: -x.supported())
  File "/usr/lib/python2.7/dist-packages/keyring/core.py", line 65, in <lambda>
    keyrings.sort(key = lambda x: -x.supported())
  File "/usr/lib/python2.7/dist-packages/keyring/backends/SecretService.py", line 23, in supported
    secretstorage.Collection(bus)
  File "/usr/lib/python2.7/dist-packages/secretstorage/collection.py", line 43, in **init**
    self.collection_props_iface.Get(COLLECTION_IFACE, 'Label')
  File "/usr/lib/python2.7/dist-packages/secretstorage/util.py", line 27, in function_out
    raise ItemNotFoundException(e.get_dbus_message())
secretstorage.exceptions.ItemNotFoundException: The '/org/freedesktop/secrets/aliases/default' object does not exist

I only installed Ubuntu 13.10 to test everpad and I haven't installed anything else before performing the everpad install.

**Comment by logart** [comment]
Hi,
I'm not expert in everpad but I should ask few questions.
1. Do you use unity on your ubuntu 13.10?
2. Did you see keyring unlock dialog while starting everpad?
2.1 If yes what did you do with it.

Thanks for answers, sorry if I will not help you.

**Comment by ChrisMagnuson** [comment]
I use a complete default Ubuntu 13.10 so I assume I am using unity.
I didn't see a keyring dialouge

**Comment by danisilver** [comment]
Hello i've the same issue and i get it:
"sni-qt/6057" WARN  14:49:40.223 void StatusNotifierItemFactory::connectToSnw() Invalid interface to SNW_SERVICE 
i have Linux Mint 16 x64 and i followed the same commands to install it

unlike @ChrisMagnuson i run two times and the Gui opens however i can create notes, console out:

Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.7/everpad/pad/list.py", line 313, in new_note
    self.app.indicator.create(notebook_id=notebook_id)
  File "/usr/lib/pymodules/python2.7/everpad/pad/indicator.py", line 164, in create
    self.app.provider.create_note(note_struct),
  File "/usr/lib/pymodules/python2.7/everpad/tools.py", line 32, in wrapper
    return getattr(self.**interface, name)(_args, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/dbus/proxies.py", line 70, in __call**
    return self._proxy_method(_args, *_keywords)
  File "/usr/lib/python2.7/dist-packages/dbus/proxies.py", line 145, in __call__
    *_keywords)
  File "/usr/lib/python2.7/dist-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Python.AttributeError: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/dbus/service.py", line 707, in _message_cb
    retval = candidate_method(self, *args, *_keywords)
  File "/usr/lib/pymodules/python2.7/everpad/provider/service.py", line 268, in create_note
    dbus_note.give_to_obj(note)
  File "/usr/lib/pymodules/python2.7/everpad/basetypes.py", line 55, in give_to_obj
    setattr(obj, field[0], val)
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/attributes.py", line 303, in **set**
    instance_dict(instance), value, None)
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/attributes.py", line 804, in set
    value = self.fire_replace_event(state, dict_, value, old, initiator)
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/attributes.py", line 824, in fire_replace_event
    value = fn(state, value, previous, initiator or self)
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/attributes.py", line 1120, in emit_backref_from_scalar_set_event
    child_state, child_dict = instance_state(child),\
AttributeError: 'dbus.Int32' object has no attribute '_sa_instance_state'

**Comment by davidsabate** [comment]
I read somewhere that it was related to a bug in python-secretstorage so I just removed this package (keeping mate-secretstorage) and it worked for me.
