### ISSUE TITLE
Can't start everpad since updated to 2.7.0 via ubuntu PPA

### ISSUE THREAD

**Issue by magowiz** [nvbn/everpad#401]
I was using previous version of everpad 2.5.6 without any big issues but since I updated it to last available from ubuntu ppa (I'm using 13.10 x64) I cannot even start the program , I get the following error :
 everpad
Traceback (most recent call last):
  File "/usr/bin/everpad", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2805, in <module>
    working_set.require(**requires**)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 696, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 594, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: PySide

I also tried to install python-pyside meta package (the error comes with python-2,x distribution, so I didn't choose python3-pyside) but the same error is still there.

**Comment by magowiz** [comment]
I wrote wrong version number : everpad's last release is 2.6.0 , not 2.7.0 , I meant 2.6.0

**Comment by lambdacalculator** [comment]
Same set-up (13.10 x64), same problem. My `sys.path` includes `/usr/lib/python2.7/dist-packages`, and this directory contains a directory `PySide`. Not sure what else to check.

**Comment by smiley0455** [comment]
The same problem here with the same set-up (13.10 x64).

**Comment by diogomatsubara** [comment]
I think I found the issue. The packaged version of PySide doesn't provide the egg info in /usr/lib/python2.7/dist-packages which make the load_entry_point call from pkg_resources fail. If you install PySide using pip (which you'll end up with /usr/local/lib/python2.7/dist-packages/PySide and /usr/local/lib/python2.7/dist-packages/PySide-1.2.1.egg-info), everpad should work again. If you then start getting py-oauth2 error, then you'd need to install that via pip as well.
Hope this helps.

**Comment by ladios** [comment]
My workaround:
- Find out the installed version of `PySide` in `/usr/lib/python2.7/dist-packages/PySide/__init__.py`
- Mine is `1.1.0`, so create a text file `/usr/lib/python2.7/dist-packages/PySide-1.1.0-py2.7.egg-info` with the following content:

```
Metadata-Version: 1.0
Name: PySide
Version: 1.1.0
Summary: UNKNOWN
Home-page: UNKNOWN
Author: UNKNOWN
Author-email: UNKNOWN
License: UNKNOWN
Description: UNKNOWN
Platform: UNKNOWN
```

In my case it then asked for `py-oauth2`, so

```
sudo easy_install py-oauth2
```

Then it can starts without error.

**Comment by lambdacalculator** [comment]
Thanks, this workaround worked. More generally, though, I'm interested to
know what changes to official packages would have to be made so that
Everpad installed on 13.10 as advertised. Not knowing much about python
package management or the OAuth2 libraries, I wonder:
- Is the missing egg-info file for PySide an oversight of the PySide
  developers, the Ubuntu packager of those libraries, or the Everpad
  distribution? That is, who should be contacted to fix this?
- My system already had the package python-oauth2 installed, but I guess
  this is different from py-oauth2, which I couldn't find in the usual
  repositories. Again, I'm wondering who should be informed of this to get it
  fixed for others installing the package as advertised.

**Comment by ladios** [comment]
After the ppa 2.6.1-0 update (b4f94df7f4aacb4a2df30ad236971cfbc7df560b?) py-oath2 is not required anymore, but the .egg-info is still needed to be in place.
I think the .egg-info should come with the `python-pyside.qtcore` package, but it doesn't. If you want to  contact the maintainers, run `dpkg -s python-pyside.qtcore | grep -i maintainer` to find out who they are.
On the order hand, Let's find out what if `PySide`'s also removed from the `requirements` list in `setup.py`.

**Comment by heiner865** [comment]
The workaround does not work for me:

wd@saustall2:~$ everpad
Traceback (most recent call last):
  File "/usr/bin/everpad", line 9, in <module>
    load_entry_point('everpad==2.6.1dev', 'gui_scripts', 'everpad')()
  File "/usr/lib/pymodules/python2.7/everpad/pad/indicator.py", line 357, in main
    pad = get_pad()
  File "/usr/lib/pymodules/python2.7/everpad/tools.py", line 39, in wrapper
    return InterfaceWrapper(partial(fnc, _args, *_kwrags))
  File "/usr/lib/pymodules/python2.7/everpad/tools.py", line 15, in **init**
    self.**load()
  File "/usr/lib/pymodules/python2.7/everpad/tools.py", line 18, in __load
    self.__interface = self.__get()
  File "/usr/lib/pymodules/python2.7/everpad/tools.py", line 55, in get_pad
    pad = bus.get_object("com.everpad.App", "/EverpadService")
  File "/usr/lib/python2.7/dist-packages/dbus/bus.py", line 241, in get_object
    follow_name_owner_changes=follow_name_owner_changes)
  File "/usr/lib/python2.7/dist-packages/dbus/proxies.py", line 248, in __init**
    self._named_service = conn.activate_name_owner(bus_name)
  File "/usr/lib/python2.7/dist-packages/dbus/bus.py", line 180, in activate_name_owner
    self.start_service_by_name(bus_name)
  File "/usr/lib/python2.7/dist-packages/dbus/bus.py", line 278, in start_service_by_name
    'su', (bus_name, flags)))
  File "/usr/lib/python2.7/dist-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NoReply: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.

**Comment by WebShapedBiz** [comment]
Thanx for the workaround but it does not work for me, got the same error message as heiner865 have.

**Comment by ladios** [comment]
I have not dived into the code, but I guess the `EverpadService` shown in the traceback is run by `everpad-provider`. `everpad` is not the only component to check. Try follow the instructions here: https://github.com/nvbn/everpad/wiki/Receiving-debug-information

**Comment by WebShapedBiz** [comment]
Apparently I needed a system restart. This workaround seems to be working fine now.

**Comment by heiner865** [comment]
The same here, thank you!

**Comment by CTilley147** [comment]
Is anyone else getting the below after installing PySide from any installation method (pip, apt, easy_install)?

everpad
Traceback (most recent call last):
  File "/usr/bin/everpad", line 9, in <module>
    load_entry_point('everpad==2.6.1dev', 'gui_scripts', 'everpad')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 343, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2309, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2015, in load
    entry = **import**(self.module_name, globals(),globals(), ['**name**'])
  File "/usr/lib/pymodules/python2.7/everpad/pad/indicator.py", line 8, in <module>
    from everpad.pad.editor import Editor
  File "/usr/lib/pymodules/python2.7/everpad/pad/editor/**init**.py", line 6, in <module>
    from everpad.interface.editor import Ui_Editor
  File "/usr/lib/pymodules/python2.7/everpad/interface/editor.py", line 125, in <module>
    from PySide import QtWebKit
ImportError: cannot import name QtWebKit

I've checked inside the PySide module and there can't see QtWebKit? I can only assume my PySide module is not building/installing correctly?

**Comment by ghostkadost** [comment]
I created the egginfo as suggested but it does not work even after restart. I get the same dbus error message mention above.

**Comment by jferna57** [comment]
With the workaround provided by @ladios I can start everpad correctly.

**Comment by SteveOhh** [comment]
@CTilley147, I'm having the same issue. Let me know if you figured it out!

edit: solved the problem. I installed NixNote, which took 30 seconds, compared to spending 3 hours on Everpad and not getting anywhere.
