### ISSUE TITLE
Running Everpad on Elementary OS

### ISSUE THREAD

**Issue by makalove** [nvbn/everpad#402]
Running Elementary OS Luna here. Everpad appeared to install perfectly, but when I try to run it from its icon in the menu, nothing seems to happen. If I run "everpad" from Terminal, I get the following:

~$ everpad
Traceback (most recent call last):
  File "/usr/bin/everpad", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2707, in <module>
    working_set.require(**requires**)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 686, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 584, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: PySide

**Comment by pazz7ven** [comment]
+1

**Comment by WebShapedBiz** [comment]
+1, same OS, same error message. Never had any issues until 2.6.0 update and 2.6.1. update did not fix it.

BTW, thanx for this app.

**Comment by lambdacalculator** [comment]
See issue #401.
