### ISSUE TITLE
Everpad provider crash

### ISSUE THREAD

**Issue by pehlm** [nvbn/everpad#403]
Running Ubuntu 12.04 Everpad 2.6.1 (new version). Eventually everpad-provider crashes, the traceback is:

Traceback (most recent call last):
   File "/usr/lib/pymodules/python2.7/everpad/provider/sync/agent.py", line 66, in run
     self.perform()
   File "/usr/lib/pymodules/python2.7/everpad/provider/sync/agent.py", line 126, in perform
     need_to_update = self._need_to_update()
   File "/usr/lib/pymodules/python2.7/everpad/provider/sync/agent.py", line 91, in _need_to_update
     self.auth_token).updateCount
   File "/usr/lib/pymodules/python2.7/evernote/edam/notestore/NoteStore.py", line 2439, in getSyncState
     self.send_getSyncState(authenticationToken)
   File "/usr/lib/pymodules/python2.7/evernote/edam/notestore/NoteStore.py", line 2448, in send_getSyncState
     self._oprot.trans.flush()
   File "/usr/lib/pymodules/python2.7/thrift/transport/THttpClient.py", line 124, in _f
     result = f(_args, *_kwargs)
   File "/usr/lib/pymodules/python2.7/thrift/transport/THttpClient.py", line 131, in flush
     self.close()
   File "/usr/lib/pymodules/python2.7/thrift/transport/THttpClient.py", line 96, in close
     self.__http.close()
   File "/usr/lib/python2.7/httplib.py", line 1126, in close
     self._conn.close()
   File "/usr/lib/python2.7/httplib.py", line 764, in close
     if self.sock:
 AttributeError: HTTPSConnection instance has no attribute 'sock'

Running Everpad with the workaround suggesting adding a "PySide-1.1.0-py2.7.egg-info"-file to /usr/lib/python2.7/dist-packages/, not doing that i'm unable to start Everpad at all. Can't give more information, Ubuntu 12.04 runs as a stock unity-system.

Regards

**Comment by simone-zero12** [comment]
Same config (12.04.4 + everpad 2.6.1), same issue

**Comment by Blackhawke** [comment]
Same issue, same version of Ubuntu (12.04.x).  Mine is intermittent though, and this last time managed to crash the entire Unity desktop. When I restarted it, Everpad didn't restart.

**Comment by antonkulaga** [comment]
It also crashes very often with Ubuntu 14.04

**Comment by zoomphys** [comment]
It crashes very often on my Trusty too

**Comment by Buggrit** [comment]
Unbuntu 14.04 - Everpad crashes with sigsegv message every time I boot. 

This from the end of my dmesg...

543.047314] everpad-provide[4281]: segfault at 4 ip (XX redacted by me XX) sp (XX redacted by me XX) error 6 in libdbus-1.so.3.7.6[(XX redacted by me XX)]
[  543.662042] everpad-provide[4287]: segfault at ffffffffffffffff ip ffffffffffffffff sp (XX redacted by me XX) error 15
[  544.139156] everpad-provide[4294]: segfault at 4 ip (XX redacted by me XX) sp (XX redacted by me XX) error 6 in libdbus-1.so.3.7.6[7fc345318000+44000]
