### ISSUE TITLE
Everpad stuck on "Sync in progress"

### ISSUE THREAD

**Issue by darrell24015** [nvbn/everpad#409]
System: Ubuntu 12.04 LTS, 32-bit
Everpad: 2.15.8-0~precise

After several minutes and other successful sync events, Everpad will eventually get stuck in "Sync in progress" - exit and restart Everpad does not help.  WiFi connection does need to be renewed after a period of time, so this seems to be happening at same time.  Resolves on reboot of system.

Traceback:
Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.7/everpad/provider/sync.py", line 458, in run
    self.perform()
  File "/usr/lib/pymodules/python2.7/everpad/provider/sync.py", line 489, in perform
    if self._need_to_update():
  File "/usr/lib/pymodules/python2.7/everpad/provider/sync.py", line 74, in _need_to_update
    update_count = self.note_store.getSyncState(self.auth_token).updateCount
  File "/usr/lib/pymodules/python2.7/evernote/edam/notestore/NoteStore.py", line 2439, in getSyncState
    self.send_getSyncState(authenticationToken)
  File "/usr/lib/pymodules/python2.7/evernote/edam/notestore/NoteStore.py", line 2448, in send_getSyncState
    self._oprot.trans.flush()
  File "/usr/lib/pymodules/python2.7/thrift/transport/THttpClient.py", line 124, in _f
    result = f(_args, *_kwargs)
  File "/usr/lib/pymodules/python2.7/thrift/transport/THttpClient.py", line 163, in flush
    self.__http.endheaders()
  File "/usr/lib/python2.7/httplib.py", line 954, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 814, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 776, in send
    self.connect()
  File "/usr/lib/pymodules/python2.7/thrift/transport/httpslib.py", line 35, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 571, in create_connection
    raise err
socket.error: [Errno 110] Connection timed out

**Comment by rmongia** [comment]
I face the same problem. The only workaround I found is by killing the background provider services as well and then start everpad again. 

```
$ pkill everpad
```

And then start Everpad.

**Comment by axfelix** [comment]
Yup, that's the only good workaround I've found.

**Comment by axfelix** [comment]
This issue actually seems to have gone away since Gnome updated from 3.14 to 3.16 last week (I'm on Arch Linux), though that doesn't make sense...
