### ISSUE TITLE
Can't open a note from indicator list

### ISSUE THREAD

**Issue by brabadu** [nvbn/everpad#41]
Started everpad in console, it's indicator appeared in the upper right corner. After syncing it shows a list of recent notes. When clicking on one of if I get 

```
brabadu@brabadu:~$ everpad
Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.7/everpad/pad/indicator.py", line 63, in open
    editor = Editor(self.app, note)
  File "/usr/lib/pymodules/python2.7/everpad/pad/editor.py", line 447, in __init__
    self.init_controls()
  File "/usr/lib/pymodules/python2.7/everpad/pad/editor.py", line 479, in init_controls
    self.ui.resourceArea, self.mark_touched,
  File "/usr/lib/pymodules/python2.7/everpad/pad/editor.py", line 333, in __init__
    self.mime = magic.open(magic.MIME_TYPE)
AttributeError: 'module' object has no attribute 'open'
```

Installed via PPA ppa:nvbn-rm/ppa

**Comment by nvbn** [comment]
You have python-magic installed from repository?

**Comment by brabadu** [comment]
Yes

```
$ apt-cache showpkg python-magic
Package: python-magic
Versions: 
5.09-2 (/var/lib/apt/lists/ua.archive.ubuntu.com_ubuntu_dists_precise_main_binary-i386_Packages) (/var/lib/dpkg/status)
 Description Language: 
                 File: /var/lib/apt/lists/ua.archive.ubuntu.com_ubuntu_dists_precise_main_binary-i386_Packages
                  MD5: 37a8fb9ea793ad19a0727c04e12d8d60
 Description Language: en
                 File: /var/lib/apt/lists/ua.archive.ubuntu.com_ubuntu_dists_precise_main_i18n_Translation-en
                  MD5: 37a8fb9ea793ad19a0727c04e12d8d60


Reverse Depends: 
  everpad,python-magic
  devscripts,python-magic
  syslog-summary,python-magic
  dff,python-magic
  python-magic-dbg,python-magic 5.09-2
  devscripts,python-magic
Dependencies: 
5.09-2 - python2.7 (0 (null)) python (2 2.7.1-0ubuntu2) python (3 2.8) libmagic1 (5 5.09-2) python-magic-dbg (0 (null)) 
Provides: 
5.09-2 - python2.7-magic 
Reverse Provides: 
```

**Comment by nvbn** [comment]
What output of python -c 'import magic; print magic.MIME' ?

**Comment by brabadu** [comment]
$ python -c 'import magic; print magic.MIME'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: 'module' object has no attribute 'MIME'

**Comment by nvbn** [comment]
Maybe you have python-magic installed from other source?

**Comment by hdave** [comment]
FWIW - I have the exact same python-magic package installed on Ubuntu 12.04 x64, but I get a different result on mime:

```
$ python -c 'import magic; print magic.MIME' 
1040
```

...and I have not encountered the OP's issue.  Wierd.  Certainly seems like the python installation is messed up.

**Comment by brabadu** [comment]
I've tried to reinstall python-magic from repo and from pypi. Can't say the exact way, but now it's working. 

Thanks!
