### ISSUE TITLE
Everpad not syncing, lens not working, ubuntu 14.04

### ISSUE THREAD

**Issue by Bishopst** [nvbn/everpad#410]
one of the reasons why I finally could get rid of windows and switch to ubuntu was that I could continue working with my evernote notes that contain all my life and work. 

First, problem now is that Everpad sync what I have uploaded from my phone (android) or from my browser, but the notes that I take from my ubuntu desktop stay as local notes and never appear in the evernote account. 

Second, the lens is not working in the ubuntu dash. It did work in the beginning when I installed 12.10, but when i upgraded to 14.04 it stopped working.

What can be done to remedy these problems. I tried to run killall everpad-provider and same for everpad-lens, restart, re-authorize the account, etc but it does not make it work. 

Help me please make it work!

**Comment by Bishopst** [comment]
This is what I get from running everpad-lens --verbose:

bashir@bashir-ThinkPad:~$ everpad-lens --verbose
Traceback (most recent call last):
  File "/usr/bin/everpad-lens", line 9, in <module>
    load_entry_point('everpad==2.5dev', 'console_scripts', 'everpad-lens')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 351, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2363, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2088, in load
    entry = **import**(self.module_name, globals(),globals(), ['**name**'])
  File "/usr/lib/pymodules/python2.7/everpad/specific/unity/lens.py", line 3, in <module>
    from singlet.lens import SingleScopeLens, ListViewCategory
  File "/usr/lib/python2.7/dist-packages/singlet/lens/**init**.py", line 1, in <module>
    from singlet.lens.base import (
  File "/usr/lib/python2.7/dist-packages/singlet/lens/base.py", line 140, in <module>
    class SingleScopeLens(Lens):
  File "/usr/lib/python2.7/dist-packages/singlet/lens/base.py", line 57, in **new**
    if isinstance(a, Unity.Scope):
  File "/usr/lib/python2.7/dist-packages/gi/module.py", line 320, in **getattr**
    return getattr(self._introspection_module, name)
  File "/usr/lib/python2.7/dist-packages/gi/module.py", line 139, in __getattr__
    self.**name**, name))
AttributeError: 'gi.repository.Unity' object has no attribute 'Scope'

**Comment by Bishopst** [comment]
This is what I get from running everpad-provider --verbose:

bashir@bashir-ThinkPad:~$ killall everpad-provider
bashir@bashir-ThinkPad:~$ everpad-provider --verbose
Segmentation fault (core dumped)

**Comment by pistolero** [comment]
I have exactly the same problem. Anybody knows how to solve this?

**Comment by MikeyG** [comment]
Have you tried to get it from here and run setup.py?

**Comment by Bishopst** [comment]
Can you tell us what are the command lines to unzip the folder downloaded (in which folder to install it) and how to run setup.py?

**Comment by RubyWanKenobi** [comment]
Everpad is running fine for me under 14.04 LTS. I had to use https://github.com/SlavikZ/unity-scope-everpad as a workaround for the everpad-lens/search functionality.

**Comment by karloscodes** [comment]
How do I start everpad built from source, I clone this repo and ran python setup.py install, everything went ok, but when i start everpad i get: dbus.exceptions.DBusException: org.freedesktop.DBus.Error.ServiceUnknown: The name com.everpad.App was not provided by any .service files, 
What is happening?

**Comment by Mahmoudz** [comment]
any solutions?!

**Comment by SlavikZ** [comment]
@ccverak - please check that both **data/everpad-app.service** and **data/everpad-provider.service** files are in the **/usr/share/dbus-1/services** directory. Please also check path to the everpad binaries in these files. If everything is OK than try to reboot your PC.

**Comment by SlavikZ** [comment]
@Mahmoudz - solution for what?

**Comment by Mahmoudz** [comment]
lens not working! 
I cannot search for notes (I don't see the everpad icon in the unity search place)
I'm on Ubuntu 14.04

**Comment by SlavikZ** [comment]
My previous comment was for @ccverak erorr. 
Solution for lens is use my unity scope instead (link to my scope repository is 6 comments above this comment).

**Comment by Mahmoudz** [comment]
Thanks @SlavikZ I saw this solution, but I'm not sure if I should implement it!
I prefer if its official, why don't you add this fix to the main repo!

**Comment by SlavikZ** [comment]
I don't push my scope to the main repo as a pull request for the several reasons:
1. The scope is valid only for ubuntu version 13.10+. In order to join it with main everpad repo addintional coding is required.
2. It is more easily for me to support it as a separate project.

In general, I don't think it is a problem to make and install my package if you want everpad scope in your ubuntu.

**Comment by karloscodes** [comment]
@SlavikZ I recreated the environment on a clean ubuntu 14.04 x64 box, I built everpad from source but i have nothing inside /usr/share/dbus-1/services/
What can i do?

```
$ everpad

everpad                                                           
/usr/lib/python2.7/dist-packages/pkg_resources.py:1031: UserWarning: /home/ccvera/.python-eggs is writable by group/others and vulnerable to attack when used with get_resource_filename. Consider a more secure location (set with .set_extraction_path or the PYTHON_EGG_CACHE environment variable).
  warnings.warn(msg, UserWarning)
Traceback (most recent call last):
  File "/usr/local/bin/everpad", line 9, in <module>
    load_entry_point('everpad==2.5dev', 'gui_scripts', 'everpad')()
  File "build/bdist.linux-x86_64/egg/everpad/pad/indicator.py", line 331, in main
  File "build/bdist.linux-x86_64/egg/everpad/tools.py", line 39, in wrapper
  File "build/bdist.linux-x86_64/egg/everpad/tools.py", line 15, in __init__
  File "build/bdist.linux-x86_64/egg/everpad/tools.py", line 18, in __load
  File "build/bdist.linux-x86_64/egg/everpad/tools.py", line 47, in get_provider
  File "/usr/lib/python2.7/dist-packages/dbus/bus.py", line 241, in get_object
    follow_name_owner_changes=follow_name_owner_changes)
  File "/usr/lib/python2.7/dist-packages/dbus/proxies.py", line 248, in __init__
    self._named_service = conn.activate_name_owner(bus_name)
  File "/usr/lib/python2.7/dist-packages/dbus/bus.py", line 180, in activate_name_owner
    self.start_service_by_name(bus_name)
  File "/usr/lib/python2.7/dist-packages/dbus/bus.py", line 278, in start_service_by_name
    'su', (bus_name, flags)))
  File "/usr/lib/python2.7/dist-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.ServiceUnknown: The name com.everpad.Provider was not provided by any .service files
```

**Comment by davidmashburn** [comment]
I'm on 64-bit 14.04, latest ppa version. I got the 1st sync to work (all my notes pulled down), but after making a new note in everpad, it just hung on 2nd sync.
I tried restarting everpad, but it was still stuck "syncing" no matter how many times I killed it.
I tried killing the everpad-provider and restarting; after that it began e-p began segfault-ing like Bishopst was finding.

I decided to wipe my data and start over:
I deleted ~/.everpad and ~/.config/everpad
I also did a killall everpad everpad-provider everpad-lens
I restarted on the terminal with:
everpad-provider --verbose & everpad

After this, everpad still remembered my account info (anybody know where that gets stored???) and opened up empty again.
After that, I re-synced everything (successfully), but with these error messages:
[3] 5956
Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.7/everpad/pad/indicator.py", line 86, in update
    len(notes) + len(pin_notes) or self.app.provider.is_first_synced()
  File "/usr/lib/pymodules/python2.7/everpad/tools.py", line 32, in wrapper
    return getattr(self.**interface, name)(_args, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/dbus/proxies.py", line 70, in __call**
    return self._proxy_method(_args, *_keywords)
  File "/usr/lib/python2.7/dist-packages/dbus/proxies.py", line 145, in __call__
    *_keywords)
  File "/usr/lib/python2.7/dist-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NoReply: Message did not receive a reply (timeout by message bus)
Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.7/everpad/pad/indicator.py", line 74, in update
    if self.app.provider.is_authenticated():
  File "/usr/lib/pymodules/python2.7/everpad/tools.py", line 32, in wrapper
    return getattr(self.__interface, name)(_args, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/dbus/proxies.py", line 70, in **call**
    return self._proxy_method(_args, *_keywords)
  File "/usr/lib/python2.7/dist-packages/dbus/proxies.py", line 145, in **call**
    *_keywords)
  File "/usr/lib/python2.7/dist-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NoReply: Message did not receive a reply (timeout by message bus)

That did take a little while (~10 minutes)...
After that, I tried making a new note...
I saved it to my main username notebook (NOT "My Notebook")

After 20 minutes, this 2nd sync is still "going", the note is not on the web, everpad&everpad-provider are still running, and no error messages show up...

So... what gives???

I'd really like this to work (and am even willing to help a little), but it is clearly broken and I have no idea where to start.

**Comment by davidmashburn** [comment]
Update: it looks like the 2nd sync hangs even if nothing has changed.

**Comment by eguzki** [comment]
exactly same behavior as @Bishopst 

Installed yesterday (13Oct 2014) using official way:

$ sudo add-apt-repository ppa:nvbn-rm/ppa
$ sudo apt-get update
$ sudo apt-get install everpad

lens not working. Looking forward to having it working

**Comment by xdaudaudau** [comment]
apt-get install libcanberra-gtk-module

**Comment by tchakravarty** [comment]
Has there been any update on this? Everpad sync not working (stuck perennially in sync on Ubuntu 14.10, kernel: 3.16.0-34-generic). Everpad works fine on 15.04 on a different machine. 

Tried a clean install of Everpad from the ppa, after an uninstall, and that did not help. Tried to build from scratch, and that got stuck in all kinds of dependency hell (cmake, PySide, qmake, ...). Not sure if there is a simple way to fix this.

**Comment by mlosilla** [comment]
I agree, latest Everpad (I installed yesterday) it's not syncing on Ubuntu 14.04 after the first sync. 
I can run the lens within a note, and it will highlight all matches, but the prev/next arrows don't highlight a word. 

I don't care about the lens too much, but without sync capabilities it just doesn't work for me
