### ISSUE TITLE
everpad release for Ubuntu 14.04 LTS

### ISSUE THREAD

**Issue by RubyWanKenobi** [nvbn/everpad#414]
Can't wait to see all features of everpad are working under Ubuntu 14.04 LTS :-). So far I can't use the search functionality but all other everpad features are working fine on my system:

everpad-lens --verbose
Traceback (most recent call last):
  File "/usr/bin/everpad-lens", line 9, in <module>
    load_entry_point('everpad==2.5dev', 'console_scripts', 'everpad-lens')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 351, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2363, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2088, in load
    entry = **import**(self.module_name, globals(),globals(), ['**name**'])
  File "/usr/lib/pymodules/python2.7/everpad/specific/unity/lens.py", line 3, in <module>
    from singlet.lens import SingleScopeLens, ListViewCategory
  File "/usr/lib/python2.7/dist-packages/singlet/lens/**init**.py", line 1, in <module>
    from singlet.lens.base import (
  File "/usr/lib/python2.7/dist-packages/singlet/lens/base.py", line 140, in <module>
    class SingleScopeLens(Lens):
  File "/usr/lib/python2.7/dist-packages/singlet/lens/base.py", line 57, in **new**
    if isinstance(a, Unity.Scope):
  File "/usr/lib/python2.7/dist-packages/gi/module.py", line 320, in **getattr**
    return getattr(self._introspection_module, name)
  File "/usr/lib/python2.7/dist-packages/gi/module.py", line 139, in __getattr__
    self.**name**, name))
AttributeError: 'gi.repository.Unity' object has no attribute 'Scope'

You guys have developed such a great software. I really use it everyday for managing work and private stuff. Keep up the good work guys ! I hope a new release will available soon that is running so smoothly as it did  for me under Ubuntu 12.04 LTS.

**Comment by RubyWanKenobi** [comment]
Hmm smart guys out there :-)

https://github.com/SlavikZ/unity-scope-everpad

did it for me. I'm fine here.. Everything works.
