### ISSUE TITLE
everpad starts slow, cannot create note

### ISSUE THREAD

**Issue by Ysmael** [nvbn/everpad#434]
Hello,
My everpad setup starts slow. After starting, cannot create note. 
Everpad was tested, confirmed working since April 2014, but now cannot create note June 21, 2014
Everyday testing Everpad at work, for almost months. 
Today at home, it cannot create & impossible to create a note.
Installed Ever Pad to Ubuntu 14.04, 14.04, same issue cannot create note.

Affixed debug information.
## Thank you

Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.7/everpad/pad/indicator.py", line 74, in update
    if self.app.provider.is_authenticated():
  File "/usr/lib/pymodules/python2.7/everpad/tools.py", line 32, in wrapper
    return getattr(self.**interface, name)(_args, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/dbus/proxies.py", line 70, in __call**
    return self._proxy_method(_args, *_keywords)
  File "/usr/lib/python2.7/dist-packages/dbus/proxies.py", line 145, in __call__
    *_keywords)
  File "/usr/lib/python2.7/dist-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NoReply: Message did not receive a reply (timeout by message bus)
Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.7/everpad/pad/indicator.py", line 74, in update
    if self.app.provider.is_authenticated():
  File "/usr/lib/pymodules/python2.7/everpad/tools.py", line 32, in wrapper
    return getattr(self.__interface, name)(_args, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/dbus/proxies.py", line 70, in **call**
    return self._proxy_method(_args, *_keywords)
  File "/usr/lib/python2.7/dist-packages/dbus/proxies.py", line 145, in **call**
    *_keywords)
  File "/usr/lib/python2.7/dist-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NoReply: Message did not receive a reply (timeout by message bus)

**Comment by jaarribere** [comment]
any resolution for this? I believe I'm having the same issue.

**Comment by blinkums** [comment]
same issue here
