### ISSUE TITLE
Everpad won't sync

### ISSUE THREAD

**Issue by project9501** [nvbn/everpad#441]
I made the change described in https://github.com/nvbn/everpad/issues/416 because Everpad wouldn't sync at all.  Before it would just segfault, now I'm getting this:

Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.7/everpad/provider/sync.py", line 454, in run
    self.init_network()
  File "/usr/lib/pymodules/python2.7/everpad/provider/sync.py", line 470, in init_network
    self.note_store = get_note_store(self.auth_token)
  File "/usr/lib/pymodules/python2.7/everpad/provider/tools.py", line 65, in get_note_store
    note_store_url = user_store.getNoteStoreUrl(auth_token)
  File "/usr/lib/pymodules/python2.7/evernote/edam/userstore/UserStore.py", line 614, in getNoteStoreUrl
    return self.recv_getNoteStoreUrl()
  File "/usr/lib/pymodules/python2.7/evernote/edam/userstore/UserStore.py", line 637, in recv_getNoteStoreUrl
    raise result.userException
evernote.edam.error.ttypes.EDAMUserException: EDAMUserException(errorCode=9, parameter='authenticationToken')

I'd try to de-authorise and re-authorise my account but there are quite a few notes now that haven't been backed up, and as Everpad doesn't seem to have an import/export I'm not quite sure how to save them and in any event I'm not sure that would solve the problem.

Suggestions?

**Comment by networkthinking-support** [comment]
I have same issue.  Any suggestions?
