### ISSUE TITLE
Unable to sync nor create note

### ISSUE THREAD

**Issue by JonathanHarford** [nvbn/everpad#444]
everpad-provider gives the error:

```
Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.7/everpad/provider/sync.py", line 454, in run
    self.init_network()
  File "/usr/lib/pymodules/python2.7/everpad/provider/sync.py", line 470, in init_network
    self.note_store = get_note_store(self.auth_token)
  File "/usr/lib/pymodules/python2.7/everpad/provider/tools.py", line 64, in get_note_store
    user_store = get_user_store(auth_token)
  File "/usr/lib/pymodules/python2.7/everpad/provider/tools.py", line 56, in get_user_store
    http_proxy=get_proxy_config(urlparse(user_store_uri).scheme))
TypeError: __init__() got an unexpected keyword argument 'http_proxy'
```

...but continues to run. everpad starts with:

```
"sni-qt/3671" WARN  09:13:39.013 void StatusNotifierItemFactory::connectToSnw() Invalid interface to SNW_SERVICE 
```

And when I try to "Please perform first sync" nothing happens. When I click "Create Note", everpad errors:

```
Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.7/everpad/pad/indicator.py", line 164, in create
    self.app.provider.create_note(note_struct),
  File "/usr/lib/pymodules/python2.7/everpad/tools.py", line 32, in wrapper
    return getattr(self.__interface, name)(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/dbus/proxies.py", line 70, in __call__
    return self._proxy_method(*args, **keywords)
  File "/usr/lib/python2.7/dist-packages/dbus/proxies.py", line 145, in __call__
    **keywords)
  File "/usr/lib/python2.7/dist-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Python.AttributeError: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/dbus/service.py", line 707, in _message_cb
    retval = candidate_method(self, *args, **keywords)
  File "/usr/lib/pymodules/python2.7/everpad/provider/service.py", line 268, in create_note
    dbus_note.give_to_obj(note)
  File "/usr/lib/pymodules/python2.7/everpad/basetypes.py", line 55, in give_to_obj
    setattr(obj, field[0], val)
  File "/usr/local/lib/python2.7/dist-packages/SQLAlchemy-0.9.7-py2.7-linux-x86_64.egg/sqlalchemy/orm/attributes.py", line 226, in __set__
    instance_dict(instance), value, None)
  File "/usr/local/lib/python2.7/dist-packages/SQLAlchemy-0.9.7-py2.7-linux-x86_64.egg/sqlalchemy/orm/attributes.py", line 812, in set
    value = self.fire_replace_event(state, dict_, value, old, initiator)
  File "/usr/local/lib/python2.7/dist-packages/SQLAlchemy-0.9.7-py2.7-linux-x86_64.egg/sqlalchemy/orm/attributes.py", line 832, in fire_replace_event
    state, value, previous, initiator or self._replace_token)
  File "/usr/local/lib/python2.7/dist-packages/SQLAlchemy-0.9.7-py2.7-linux-x86_64.egg/sqlalchemy/orm/attributes.py", line 1135, in emit_backref_from_scalar_set_event
    child_state, child_dict = instance_state(child),\
AttributeError: 'dbus.Int32' object has no attribute '_sa_instance_state'
```

**Comment by philsf** [comment]
@JonathanHarford , this looks like a duplicate of #394 . If you have the package `python-thrift` installed, removing it  will make everpad-provider work.
