### ISSUE TITLE
Installation on fedora 21 works with some manual steps (setup.py install seems broken?)

### ISSUE THREAD

**Issue by swobspace** [nvbn/everpad#454]
Here are my steps for installing everpad on fedora 21. `setup.py install` did not complete (see below), so there are some manual steps to get everpad running.

``` shell
yum install python-pyside-devel python-pyside python-BeautifulSoup \
  python-keyring python-sqlalchemy python-oauth2 python-magic \
  python-html2text python-regex python-setuptools gtk2-engines-devel \
  gtk2-engines qt-devel dbus-python-devel dbus-python qt-devel
```

`qt-devel` provides qmake-qt4 but Everpad is searching for qmake. Therefore, I
created a symlink:

``` shell
ln -s /usr/bin/qmake-qt4 /usr/bin/qmake
```

Installation procedure:

``` shell
git clone https://github.com/nvbn/everpad.git
cd everpad
python setup.py install
```

The installation breaks at this point:

```
...
Installing everpad script to /usr/bin

Installed /usr/lib/python2.7/site-packages/everpad-2.5dev-py2.7.egg
Processing dependencies for everpad==2.5dev
Traceback (most recent call last):
  File "setup.py", line 114, in <module>
    'everpad/specific/kde/everpad_runner.py',
  File "/usr/lib64/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib64/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib64/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/lib/python2.7/site-packages/setuptools/command/install.py", line 73, in run
    self.do_egg_install()
  File "/usr/lib/python2.7/site-packages/setuptools/command/install.py", line 101, in do_egg_install
    cmd.run()
  File "/usr/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 358, in run
    self.easy_install(spec, not self.no_deps)
  File "/usr/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 574, in easy_install
    return self.install_item(None, spec, tmpdir, deps, True)
  File "/usr/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 625, in install_item
    self.process_distribution(spec, dist, deps)
  File "/usr/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 671, in process_distribution
    [requirement], self.local_index, self.easy_install
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 572, in resolve
    requirements.extend(dist.requires(req.extras)[::-1])
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 2240, in requires
    dm = self._dep_map
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 2225, in _dep_map
    for extra,reqs in split_sections(self._get_metadata(name)):
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 2666, in split_sections
    for line in yield_lines(s):
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 1926, in yield_lines
    for ss in strs:
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 2254, in _get_metadata
    for line in self.get_metadata_lines(name):
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 1316, in get_metadata_lines
    return yield_lines(self.get_metadata(name))
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 1308, in get_metadata
    return self._get(self._fn(self.egg_info,name))
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 1372, in _get
    return self.loader.get_data(path)
zipimport.ZipImportError: bad local file header in /usr/lib/python2.7/site-packages/everpad-2.5dev-py2.7.egg
```

Manual steps:

``` shell
cp /data/everpad-app.service /data/everpad-provider.service /usr/share/dbus-1/services/.
```

Now you must restart dbus-daemon. Best to reboot yet, killing dbus-daemon manually kicks you off your
gnome desktop session.

At last copy the neccessary icons to their destination:

``` shell
cp data/everpad-black.png data/everpad-mono.png /usr/share/icons/hicolor/24x24/apps/
cp data/everpad-file.png /usr/share/icons/hicolor/48x48/actions/.
cp data/everpad-file.png /usr/share/icons/hicolor/64x64/apps/
cp data/everpad.png data/everpad-lens.png /usr/share/icons/hicolor/128x128/apps/
cp data/everpad*.png /usr/share/pixmaps/.
cp data/editor-icons/* /usr/share/icons/hicolor/24x24/actions/.

cp data/everpad.desktop /usr/share/applications/.
```

Using [topicons](https://extensions.gnome.org/extension/495/topicons/) on Fedora with Gnome is really, really recommended.

Remaining problems:
- One missing package is `gtk2-engines-pixbuf`, i can't find any alternative, so
  Everpad did not show pictures within notes.
- The synchronisation stops at the first note which contains pictures. The systray dialog show "always syncing", everpad-provider.log shows

```
2015-01-01 15:57:20,118 - everpad-provider - DEBUG - expected a character buffer object
```

**Comment by swobspace** [comment]
I don't use everpad any longer. Closing ...
