### ISSUE TITLE
Not working for different local locale

### ISSUE THREAD

**Issue by sadaf2605** [nvbn/everpad#464]
When I clicked on top menu it shows: 
sadaf2605@sadaf-pc:~$ everpad

Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.7/everpad/pad/indicator.py", line 98, in update
    print datetime.strptime("12:50", "%H:%M")
  File "/usr/lib/python2.7/_strptime.py", line 270, in <module>
    _TimeRE_cache = TimeRE()
  File "/usr/lib/python2.7/_strptime.py", line 188, in __init__
    self.locale_time = LocaleTime()
  File "/usr/lib/python2.7/_strptime.py", line 70, in __init__
    self.lang = _getlang()
  File "/usr/lib/python2.7/_strptime.py", line 29, in _getlang
    return locale.getlocale(locale.LC_TIME)
  File "/usr/lib/python2.7/locale.py", line 562, in getlocale
    return _parse_localename(localename)
  File "/usr/lib/python2.7/locale.py", line 475, in _parse_localename
    raise ValueError, 'unknown locale: %s' % localename
ValueError: unknown locale: bn_BD

**Comment by sadaf2605** [comment]
one way to bypass this is to run "export LC_ALL=en_US.UTF-8 && export LANG=en_US.UTF-8 && everpad %U" at start up from start up application.
