### ISSUE TITLE
Cannot create new note

### ISSUE THREAD

**Issue by davinellulinvega** [nvbn/everpad#468]
Hello everyone,

I just installed the latest available version for everpad on Lubuntu (15.04). Furthermore, I gave everpad the authorization to access my evernote account. However, I cannot create any note, whether through the command line or the nice interface.
Here are a few information that might be helpful to you:
- everpad --version:

```
Everpad version: 2.5
API version: 6
Schema version: 5
```

+everpad-provider --version:

```
Everpad version: 2.5
API version: 6
Schema version: 5
```
- everpad --create:

```
Traceback (most recent call last):
  File "/usr/bin/everpad", line 9, in <module>
    load_entry_point('everpad===2.5dev-r0', 'gui_scripts', 'everpad')()
  File "/usr/lib/pymodules/python2.7/everpad/pad/indicator.py", line 325, in main
    pad.create()
  File "/usr/lib/pymodules/python2.7/everpad/tools.py", line 32, in wrapper
    return getattr(self.__interface, name)(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/dbus/proxies.py", line 70, in __call__
    return self._proxy_method(*args, **keywords)
  File "/usr/lib/python2.7/dist-packages/dbus/proxies.py", line 145, in __call__
    **keywords)
  File "/usr/lib/python2.7/dist-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Python.AttributeError: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/dbus/service.py", line 707, in _message_cb
    retval = candidate_method(self, *args, **keywords)
  File "/usr/lib/pymodules/python2.7/everpad/provider/service.py", line 268, in create_note
    dbus_note.give_to_obj(note)
  File "/usr/lib/pymodules/python2.7/everpad/basetypes.py", line 55, in give_to_obj
    setattr(obj, field[0], val)
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/attributes.py", line 226, in __set__
    instance_dict(instance), value, None)
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/attributes.py", line 812, in set
    value = self.fire_replace_event(state, dict_, value, old, initiator)
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/attributes.py", line 832, in fire_replace_event
    state, value, previous, initiator or self._replace_token)
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/attributes.py", line 1135, in emit_backref_from_scalar_set_event
    child_state, child_dict = instance_state(child),\
AttributeError: 'dbus.Int32' object has no attribute '_sa_instance_state'
```

Thank you very much for your help.

**Comment by junhuawa** [comment]
The everpad's setting is located in the right up side of the screen, we need to authorize first, then we can create new note.

**Comment by davinellulinvega** [comment]
Hello,

Thank you very much for the answer. However, my problem is that this error appears after authorizing everpad to access my evernote account. Is there a problem when storing the authorization key on my computer?

Sincerely.

**Comment by junhuawa** [comment]
If that, I don't know why. Sorry. I just begin to use  it. I found it can't sync my notes from the evernote repo.

**Comment by rwijtvliet** [comment]
Getting the exact same error on Ubuntu (unity) 15.04. I'm using the same everpad and everpad-provider versions. 

App installs well, seems to work, authorisation is granted and saved (checked by opening up evernote web interface), but no notes can be created and 'please perform first sync' does not do anything. Seems the app has difficulties accessing the evernote API?

Any ideas on how to solve? Any logs I could provide?

**Comment by sandeepraju** [comment]
+1 same issue here.

```
$lsb_release -d
Description:    Ubuntu 14.04.3 LTS

$everpad --version
Everpad version: 2.5
API version: 6
Schema version: 5
```

**Comment by AshishGupta001** [comment]
Tried installing Everpad as the instructions above (on Ubuntu 14.04 Unity) and completed the Authorization.

I am able to add new NoteBook but clicking on New Note just does nothing. Tried creating from command line but get following error. Is there a bug already logged for it?

```
/var/www/html/L5>$ everpad --create note
Traceback (most recent call last):
File "/usr/bin/everpad", line 9, in
load_entry_point('everpad==2.5dev', 'gui_scripts', 'everpad')()
File "/usr/lib/pymodules/python2.7/everpad/pad/indicator.py", line 325, in main
pad.create()
File "/usr/lib/pymodules/python2.7/everpad/tools.py", line 32, in wrapper
return getattr(self.__interface, name)(*args, **kwargs)
File "/usr/lib/python2.7/dist-packages/dbus/proxies.py", line 70, in __call__
return self._proxy_method(*args, **keywords)
File "/usr/lib/python2.7/dist-packages/dbus/proxies.py", line 145, in __call__
**keywords)
File "/usr/lib/python2.7/dist-packages/dbus/connection.py", line 651, in call_blocking
message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Python.AttributeError: Traceback (most recent call last):
File "/usr/lib/python2.7/dist-packages/dbus/service.py", line 707, in _message_cb
retval = candidate_method(self, *args, **keywords)
File "/usr/lib/pymodules/python2.7/everpad/provider/service.py", line 268, in create_note
dbus_note.give_to_obj(note)
File "/usr/lib/pymodules/python2.7/everpad/basetypes.py", line 55, in give_to_obj
setattr(obj, field[0], val)
File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/attributes.py", line 303, in __set__
instance_dict(instance), value, None)
File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/attributes.py", line 804, in set
value = self.fire_replace_event(state, dict_, value, old, initiator)
File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/attributes.py", line 824, in fire_replace_event
value = fn(state, value, previous, initiator or self)
File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/attributes.py", line 1120, in emit_backref_from_scalar_set_event
child_state, child_dict = instance_state(child),\
AttributeError: 'dbus.Int32' object has no attribute '_sa_instance_state'
```

**Comment by bhawna2909** [comment]
Faced same issue. After authorisation click on "Perform first sync". After that I was able to create notes.
