### ISSUE TITLE
Can't find everpad in the repository and can't build | install | launch after "git clone" on Raspberry Pi 2 with Raspbian Wheezy

### ISSUE THREAD

**Issue by Romain-Revel** [nvbn/everpad#469]
Hi,

I'm trying to install Everpad on a Raspberry Pi 2 with Raspbian Wheezy but without success.
I had a look at https://github.com/nvbn/everpad/wiki/how-to-install but many paquets are not available on Raspbian.
I also tried installing through the ppa, but everpad isn't available.
So could you please build a package for Raspberry Pi and have it available on whatever ppa and / or write a correct procedure to build it on a Raspberry ?

Thanks

**Comment by Romain-Revel** [comment]
Some more details:

# I downloaded everpad on my desktop:

```
pi@PI2SEB ~/Desktop $ git clone https://github.com/nvbn/everpad
```

# I installed cmake this way (VERY long)

```
wget http://www.cmake.org/files/v3.2/cmake-3.2.2.tar.gz
tar xzvf cmake-3.2.2.tar.gz
cd cmake-3.2.2
sudo ./bootstrap
sudo make
sudo make install
```

# I installed qmake this way

```
sudo apt-get install qt4-qmake
```

# I installed all python dependances

```
sudo apt-get install python-pyside.qtcore python-pyside.qtgui python-dbus python-beautifulsoup python-pysqlite2 python-keyring python-support python-sqlalchemy python-oauth2 python-magic python-pyside.qtwebkit python-html2text gtk2-engines-pixbuf python-regex python-setuptools
```

# I tried installing this without success (because not available on the repos)

```
sudo apt-get install sni-qt python-unity-singlet
```

# I installed these 2 packages:

```
sudo apt-get install libqt4-dev python-dev
```

# Then I installed everpad (EXTREMELY long, took the whole night)

```
sudo python setup.py install
```

# Here is the error that I get when launching everpad, but I can't solve it (I am no python expert)

pi@PI2SEB ~/Desktop/everpad $ everpad
Traceback (most recent call last):
  File "/usr/local/bin/everpad", line 9, in <module>
    load_entry_point('everpad===2.5dev-r0', 'gui_scripts', 'everpad')()
  File "build/bdist.linux-armv7l/egg/pkg_resources/**init**.py", line 552, in load_entry_point
  File "build/bdist.linux-armv7l/egg/pkg_resources/**init**.py", line 2672, in load_entry_point
  File "build/bdist.linux-armv7l/egg/pkg_resources/**init**.py", line 2345, in load
  File "build/bdist.linux-armv7l/egg/pkg_resources/**init**.py", line 2351, in resolve
  File "build/bdist.linux-armv7l/egg/everpad/pad/indicator.py", line 3, in <module>
ImportError: libpyside-python2.7.so.1.2: cannot open shared object file: No such file or directory

# Here is the content of /usr/local/bin/everpad if it might help

pi@PI2SEB ~/Desktop/everpad $ cat /usr/local/bin/everpad
#!/usr/bin/python
#EASY-INSTALL-ENTRY-SCRIPT: 'everpad===2.5dev-r0','gui_scripts','everpad'
**requires** = 'everpad===2.5dev-r0'
import sys
from pkg_resources import load_entry_point

if **name** == '**main**':
    sys.exit(
        load_entry_point('everpad===2.5dev-r0', 'gui_scripts', 'everpad')()
    )
