### ISSUE TITLE
cant launch everpad on fedora23

### ISSUE THREAD

**Issue by bavodaniels** [nvbn/everpad#487]
i get an error with launchng everpad from command line

Traceback (most recent call last):
  File "/usr/bin/everpad", line 9, in <module>
    load_entry_point('everpad===2.5dev-r0', 'gui_scripts', 'everpad')()
  File "/usr/lib/python2.7/site-packages/pkg_resources/**init**.py", line 558, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/site-packages/pkg_resources/**init**.py", line 2682, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/site-packages/pkg_resources/**init**.py", line 2355, in load
    return self.resolve()
  File "/usr/lib/python2.7/site-packages/pkg_resources/**init**.py", line 2361, in resolve
    module = **import**(self.module_name, fromlist=['**name**'], level=0)
  File "/usr/lib/python2.7/site-packages/everpad/pad/indicator.py", line 8, in <module>
    from everpad.pad.editor import Editor
  File "/usr/lib/python2.7/site-packages/everpad/pad/editor/**init**.py", line 6, in <module>
    from everpad.interface.editor import Ui_Editor
  File "/usr/lib/python2.7/site-packages/everpad/interface/editor.py", line 125, in <module>
    from PySide import QtWebKit
ImportError: cannot import name QtWebKit

any ideas?

**Comment by mwilck** [comment]
I had the same problem in F22. I got around it by installing qtwebkit with dnf, then running "pip install PySide". I think that the qtwebkit module of PySide is only built if qtwebkit is found at installation time.
