### ISSUE TITLE
installation problem on debian 9 "Configuring incomplete, errors occurred" "No CMAKE_CXX_COMPILER"

### ISSUE THREAD

**Issue by childeofentropy** [nvbn/everpad#498]
After installing all the python dependencies mentioned in the wiki section, I do
`git clone https://github.com/nvbn/everpad.git
cd everpad
python setup.py install`

and after that this is what I get:

`running install`
.....
.....
`Installed /usr/local/lib/python2.7/dist-packages/everpad-2.5.dev0-py2.7.egg`
`Processing dependencies for everpad==2.5.dev0`
`Searching for PySide`
`Reading https://pypi.python.org/simple/PySide/`
`Downloading https://pypi.python.org/packages/36/ac/ca31db6f2225844d37a41b10615c3d371587677efd074db29855e7035de6/PySide-1.2.4.tar.gz#md5=3cb7174c13bd45e3e8f77638926cb8c0`
`Best match: PySide 1.2.4`
`Processing PySide-1.2.4.tar.gz`
`Writing /tmp/easy_install-WkXZYl/PySide-1.2.4/setup.cfg`
`Running PySide-1.2.4/setup.py -q bdist_egg --dist-dir /tmp/easy_install-WkXZYl/PySide-1.2.4/egg-dist-tmp-IwtZW7`
`Removing /tmp/easy_install-WkXZYl/PySide-1.2.4/pyside_package`
`-- The C compiler identification is GNU 6.3.0`
`-- The CXX compiler identification is unknown`
`-- Check for working C compiler: /usr/bin/cc`
`-- Check for working C compiler: /usr/bin/cc -- works`
`-- Detecting C compiler ABI info`
`-- Detecting C compiler ABI info - done`
`-- Detecting C compile features`
`-- Detecting C compile features - done`
`CMake Error at CMakeLists.txt:2 (project):`
`  No CMAKE_CXX_COMPILER could be found.`

`  Tell CMake where to find the compiler by setting either the environment
  variable "CXX" or the CMake cache entry CMAKE_CXX_COMPILER to the full path
  to the compiler, or to the compiler name if it is in the PATH.`

`-- Configuring incomplete, errors occurred!`
`See also "/tmp/easy_install-WkXZYl/PySide-1.2.4/pyside_build/py2.7-qt4.8.7-64bit-release/shiboken/CMakeFiles/CMakeOutput.log".`
`See also "/tmp/easy_install-WkXZYl/PySide-1.2.4/pyside_build/py2.7-qt4.8.7-64bit-release/shiboken/CMakeFiles/CMakeError.log".`
`error: Setup script exited with error: Error configuring shiboken`

I guess the problem is in the last part were it says "configuring incomplete" about "No CMAKE_CXX_COMPILER could be found.", but I do not understand what should I do.

--
Thank you for your time.

**Comment by Sari-Vari** [comment]
I have the same problem! While installing on debian 9 I have done all the steps needed, even the optional, but after 
$ python setup.py install

I get the following error:

`CMake Error at CMakeLists.txt:2 (project):
  No CMAKE_CXX_COMPILER could be found.

  Tell CMake where to find the compiler by setting either the environment
  variable "CXX" or the CMake cache entry CMAKE_CXX_COMPILER to the full path
  to the compiler, or to the compiler name if it is in the PATH.


-- Configuring incomplete, errors occurred!
See also "/tmp/easy_install-ZNfhmT/PySide-1.2.4/pyside_build/py2.7-qt4.8.7-64bit-release/shiboken/CMakeFiles/CMakeOutput.log".
See also "/tmp/easy_install-ZNfhmT/PySide-1.2.4/pyside_build/py2.7-qt4.8.7-64bit-release/shiboken/CMakeFiles/CMakeError.log".
error: Setup script exited with error: Error configuring shiboken`

If anyone could please have a look and tell us what's wrong because I cannot figure this out on my own (linux newb here :/)

Thank you in advance! Peace.

**Comment by childeofentropy** [comment]
update: While installing on debian 9 I have done all the steps needed, even the optional, but after 
$ python setup.py install
I get the same error:

`CMake Error at CMakeLists.txt:2 (project):
  No CMAKE_CXX_COMPILER could be found.`

`  Tell CMake where to find the compiler by setting either the environment
  variable "CXX" or the CMake cache entry CMAKE_CXX_COMPILER to the full path
  to the compiler, or to the compiler name if it is in the PATH.`


`-- Configuring incomplete, errors occurred!`
`See also "/tmp/easy_install-ZNfhmT/PySide-1.2.4/pyside_build/py2.7-qt4.8.7-64bit-release/shiboken/CMakeFiles/CMakeOutput.log".`
`See also "/tmp/easy_install-ZNfhmT/PySide-1.2.4/pyside_build/py2.7-qt4.8.7-64bit-release/shiboken/CMakeFiles/CMakeError.log".`
`error: Setup script exited with error: Error configuring shiboken`

**Comment by nidsche** [comment]
sudo apt-get update && sudo apt-get install build-essential
should fix your issue

**Comment by childeofentropy** [comment]
# apt-get install build-essential
Reading package lists... Done
Building dependency tree       
Reading state information... Done
build-essential is already the newest version (12.3).
build-essential set to manually installed.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

**Comment by Sari-Vari** [comment]
it did install, and it took more than 5 minutes...wow
now it won't launch. i type 'everpad' and there is nothing there, on the start menu there is only the option 'run everpad' which leads to nothing, at least i know installation was ok
launching 'everpad' while on root terminal gives some code sequence i didn't keep track.
tried to uninstall, don't know how, just deleted the files and now running 'everpad' on terminal will give this:
-------------
Traceback (most recent call last):
  File "/usr/local/bin/everpad", line 11, in <module>
    load_entry_point('everpad==2.5.dev0', 'gui_scripts', 'everpad')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 561, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2631, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2291, in load
    return self.resolve()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2297, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "build/bdist.linux-x86_64/egg/everpad/pad/indicator.py", line 8, in <module>
  File "build/bdist.linux-x86_64/egg/everpad/pad/editor/__init__.py", line 6, in <module>
  File "build/bdist.linux-x86_64/egg/everpad/interface/editor.py", line 125, in <module>
ImportError: cannot import name QtWebKit
-------------
Thank you for your time. I just want to uninstall now..

**Comment by childeofentropy** [comment]
it did install, and it took more than 5 minutes...wow
now it won't launch. i type 'everpad' and there is nothing there, on the start menu there is only the option 'run everpad' which leads to nothing, at least i know installation was ok
launching 'everpad' while on root terminal gives some code sequence i didn't keep track.
tried to uninstall, don't know how, just deleted the files and now running 'everpad' on terminal will give this:
Traceback (most recent call last):
File "/usr/local/bin/everpad", line 11, in
load_entry_point('everpad==2.5.dev0', 'gui_scripts', 'everpad')()
File "/usr/lib/python2.7/dist-packages/pkg_resources/init.py", line 561, in load_entry_point
return get_distribution(dist).load_entry_point(group, name)
File "/usr/lib/python2.7/dist-packages/pkg_resources/init.py", line 2631, in load_entry_point
return ep.load()
File "/usr/lib/python2.7/dist-packages/pkg_resources/init.py", line 2291, in load
return self.resolve()
File "/usr/lib/python2.7/dist-packages/pkg_resources/init.py", line 2297, in resolve
module = import(self.module_name, fromlist=['name'], level=0)
File "build/bdist.linux-x86_64/egg/everpad/pad/indicator.py", line 8, in
File "build/bdist.linux-x86_64/egg/everpad/pad/editor/init.py", line 6, in
File "build/bdist.linux-x86_64/egg/everpad/interface/editor.py", line 125, in
ImportError: cannot import name QtWebKit

Thank you for your time. I just want to uninstall now..
