### ISSUE TITLE
Everpad-provider crash at startup

### ISSUE THREAD

**Issue by AlexFalappa** [nvbn/everpad#52]
After loggin in (I have checked the "Start with system" setting in the preferences) I got an apport crash report. I chose to relaunch the provider from the crash report dialog.

The python stack-trace is extracted below:

```
PythonArgs: ['/usr/bin/everpad-provider']
Traceback:
 Traceback (most recent call last):
   File "/usr/lib/pymodules/python2.7/everpad/provider/sync.py", line 63, in run
     self.note_store = get_note_store(self.auth_token)
   File "/usr/lib/pymodules/python2.7/everpad/provider/tools.py", line 42, in get_note_store
     note_store_url = user_store.getNoteStoreUrl(auth_token)
   File "/usr/lib/pymodules/python2.7/evernote/edam/userstore/UserStore.py", line 613, in getNoteStoreUrl
     self.send_getNoteStoreUrl(authenticationToken)
   File "/usr/lib/pymodules/python2.7/evernote/edam/userstore/UserStore.py", line 622, in send_getNoteStoreUrl
     self._oprot.trans.flush()
   File "/usr/lib/pymodules/python2.7/thrift/transport/THttpClient.py", line 96, in _f
     result = f(*args, **kwargs)
   File "/usr/lib/pymodules/python2.7/thrift/transport/THttpClient.py", line 117, in flush
     self.__http.endheaders()
   File "/usr/lib/python2.7/httplib.py", line 954, in endheaders
     self._send_output(message_body)
   File "/usr/lib/python2.7/httplib.py", line 814, in _send_output
     self.send(msg)
   File "/usr/lib/python2.7/httplib.py", line 776, in send
     self.connect()
   File "/usr/lib/pymodules/python2.7/thrift/transport/httpslib.py", line 35, in connect
     self.timeout, self.source_address)
   File "/usr/lib/python2.7/socket.py", line 553, in create_connection
     for res in getaddrinfo(host, port, 0, SOCK_STREAM):
 gaierror: [Errno -2] Nome o servizio sconosciuto
```

The error message in the last line is italian for "Unknown service or name".

I think this exception should be trapped, reported somewhere in a log and not stop the provider. 

It would also be great if connection to the evernote services was retried a couple of times in case of unreliable network.

**Comment by hdave** [comment]
This may be relevant, but I have found that evernote-provider often crashes at startup for me on my laptop when I log in without an internet connection.  Come to think of it, it may be just trigger an appport crash report and not crash/terminating.

**Comment by darkk** [comment]
Seems, the bug is still here. Same symptoms, latest version, another backtrace:

```
PythonArgs: ['/usr/bin/everpad-provider']
Traceback:
 Traceback (most recent call last):
   File "/usr/lib/pymodules/python2.7/everpad/provider/sync.py", line 365, in run
     self.perform()
   File "/usr/lib/pymodules/python2.7/everpad/provider/sync.py", line 396, in perform
     if self._need_to_update():
   File "/usr/lib/pymodules/python2.7/everpad/provider/sync.py", line 60, in _need_to_update
     update_count = self.note_store.getSyncState(self.auth_token).updateCount
   File "/usr/lib/pymodules/python2.7/evernote/edam/notestore/NoteStore.py", line 2439, in getSyncState
     self.send_getSyncState(authenticationToken)
   File "/usr/lib/pymodules/python2.7/evernote/edam/notestore/NoteStore.py", line 2448, in send_getSyncState
     self._oprot.trans.flush()
   File "/usr/lib/pymodules/python2.7/thrift/transport/THttpClient.py", line 124, in _f
     result = f(*args, **kwargs)
   File "/usr/lib/pymodules/python2.7/thrift/transport/THttpClient.py", line 163, in flush
     self.__http.endheaders()
   File "/usr/lib/python2.7/httplib.py", line 958, in endheaders
     self._send_output(message_body)
   File "/usr/lib/python2.7/httplib.py", line 818, in _send_output
     self.send(msg)
   File "/usr/lib/python2.7/httplib.py", line 780, in send
     self.connect()
   File "/usr/lib/pymodules/python2.7/thrift/transport/httpslib.py", line 35, in connect
     self.timeout, self.source_address)
   File "/usr/lib/python2.7/socket.py", line 553, in create_connection
     for res in getaddrinfo(host, port, 0, SOCK_STREAM):
 gaierror: [Errno -2] Name or service not known
…
Package: everpad 2.4-0~quantal [origin: LP-PPA-nvbn-rm]
```
