### ISSUE TITLE
DBus Exception : Failed to execute program everpad-provider

### ISSUE THREAD

**Issue by utkarshsins** [nvbn/everpad#59]
This error is coming up on a Gnome system, when trying to start Everpad.

<pre>
Traceback (most recent call last):
  File "/usr/local/bin/everpad", line 9, in <module>
    load_entry_point('everpad==1.8dev', 'gui_scripts', 'everpad')()
  File "/usr/local/lib/python2.7/dist-packages/everpad-1.8dev-py2.7.egg/everpad/pad/indicator.py", line 185, in main
    app.provider = get_provider(session_bus) 
  File "/usr/local/lib/python2.7/dist-packages/everpad-1.8dev-py2.7.egg/everpad/tools.py", line 6, in get_provider
    provider = bus.get_object("com.everpad.Provider", '/EverpadProvider')
  File "/usr/lib/python2.7/dist-packages/dbus/bus.py", line 241, in get_object
    follow_name_owner_changes=follow_name_owner_changes)
  File "/usr/lib/python2.7/dist-packages/dbus/proxies.py", line 248, in __init__
    self._named_service = conn.activate_name_owner(bus_name)
  File "/usr/lib/python2.7/dist-packages/dbus/bus.py", line 180, in activate_name_owner
    self.start_service_by_name(bus_name)
  File "/usr/lib/python2.7/dist-packages/dbus/bus.py", line 278, in start_service_by_name
    'su', (bus_name, flags)))
  File "/usr/lib/python2.7/dist-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.Spawn.ExecFailed: Failed to execute program /usr/bin/everpad-provider: Success
</pre>

**Comment by nvbn** [comment]
What output of everpad-provider?
And what os version you use?

**Comment by utkarshsins** [comment]
I am trying to get this thing running on a Gnome based Debian Wheezy (in form of a gnome notification area applet).

Simply running everpad-provider gives me the following output :

<pre>
ERROR:dbus.connection:Unable to set arguments ([], dbus.ObjectPath('/org/freedesktop/secrets/session/s4')) according to signature None: <type 'exceptions.ValueError'>: Unable to guess signature from an empty list
Traceback (most recent call last):
  File "/usr/local/bin/everpad-provider", line 9, in <module>
    load_entry_point('everpad==1.8dev', 'console_scripts', 'everpad-provider')()
  File "/usr/local/lib/python2.7/dist-packages/everpad-1.8dev-py2.7.egg/everpad/provider/daemon.py", line 72, in main
    app = ProviderApp(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/everpad-1.8dev-py2.7.egg/everpad/provider/daemon.py", line 28, in __init__
    if get_auth_token():
  File "/usr/local/lib/python2.7/dist-packages/everpad-1.8dev-py2.7.egg/everpad/tools.py", line 20, in get_auth_token
    return keyring.get_password('everpad', 'oauth_token')
  File "/usr/lib/python2.7/dist-packages/keyring/core.py", line 37, in get_password
    return _keyring_backend.get_password(service_name, username)
  File "/usr/lib/python2.7/dist-packages/keyring/backend.py", line 199, in get_password
    secrets = service_iface.GetSecrets(unlocked + locked, session)
  File "/usr/lib/python2.7/dist-packages/dbus/proxies.py", line 145, in __call__
    **keywords)
  File "/usr/lib/python2.7/dist-packages/dbus/connection.py", line 641, in call_blocking
    message.append(signature=signature, *args)
ValueError: Unable to guess signature from an empty list
</pre>

**Comment by nvbn** [comment]
gnome-keyring is runnig?

**Comment by utkarshsins** [comment]
I am sorry, the "gnome-keyring-daemon" was up and running, but python-gnomekeyring was not installed. It is working now.

**Comment by nvbn** [comment]
Ok =)
