### ISSUE TITLE
Dash lens crashing

### ISSUE THREAD

**Issue by hdave** [nvbn/everpad#6]
Running 12.04 64 bit desktop with all updates.  For whatever reason, the application indicator works for me, but I keep getting crash reports from Ubuntu regarding the lens.  I have not been able to see the lens work yet.

**Comment by nvbn** [comment]
Can you try kill lens and run in terminal via:
killall everpad-lens; everpad-lens
?
And write output here.

**Comment by Soundistor** [comment]
killall everpad-lens; everpad-lens
everpad-lens: no process found
Traceback (most recent call last):
  File "/usr/bin/everpad-lens", line 9, in <module>
    load_entry_point('everpad==1.2dev', 'console_scripts', 'everpad-lens')()
  File "/usr/local/lib/python2.7/dist-packages/distribute-0.6.24-py2.7.egg/pkg_resources.py", line 337, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python2.7/dist-packages/distribute-0.6.24-py2.7.egg/pkg_resources.py", line 2279, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python2.7/dist-packages/distribute-0.6.24-py2.7.egg/pkg_resources.py", line 1989, in load
    entry = **import**(self.module_name, globals(),globals(), ['**name**'])
  File "/usr/lib/pymodules/python2.7/everpad/lens.py", line 10, in <module>
    provider = get_provider()
  File "/usr/lib/pymodules/python2.7/everpad/tools.py", line 6, in get_provider
    provider = bus.get_object("com.everpad.Provider", '/EverpadProvider')
  File "/usr/lib/python2.7/dist-packages/dbus/bus.py", line 241, in get_object
    follow_name_owner_changes=follow_name_owner_changes)
  File "/usr/lib/python2.7/dist-packages/dbus/proxies.py", line 248, in **init**
    self._named_service = conn.activate_name_owner(bus_name)
  File "/usr/lib/python2.7/dist-packages/dbus/bus.py", line 180, in activate_name_owner
    self.start_service_by_name(bus_name)
  File "/usr/lib/python2.7/dist-packages/dbus/bus.py", line 278, in start_service_by_name
    'su', (bus_name, flags)))
  File "/usr/lib/python2.7/dist-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.Spawn.ChildExited: Process /usr/bin/everpad-provider exited with status 1

**Comment by nvbn** [comment]
And what output when you run everpad-provider?

**Comment by Soundistor** [comment]
@ubuntu:~$ everpad-provider
Traceback (most recent call last):
  File "/usr/bin/everpad-provider", line 9, in <module>
    load_entry_point('everpad==1.2dev', 'console_scripts', 'everpad-provider')()
  File "/usr/lib/pymodules/python2.7/everpad/provider/daemon.py", line 43, in main
    fcntl.lockf(fp, fcntl.LOCK_EX | fcntl.LOCK_NB)
IOError: [Errno 11] Resource temporarily unavailable

**Comment by nvbn** [comment]
Try killall everpad-provider; everpad-provider

**Comment by Soundistor** [comment]
killall everpad-provider; everpad-provider
everpad-provider: no process found
Traceback (most recent call last):
  File "/usr/bin/everpad-provider", line 9, in <module>
    load_entry_point('everpad==1.2dev', 'console_scripts', 'everpad-provider')()
  File "/usr/lib/pymodules/python2.7/everpad/provider/daemon.py", line 45, in main
    app = ProviderApp(sys.argv)
  File "/usr/lib/pymodules/python2.7/everpad/provider/daemon.py", line 21, in **init**
    if get_auth_token():
  File "/usr/lib/pymodules/python2.7/everpad/provider/tools.py", line 23, in get_auth_token
    return keyring.get_password('everpad', 'oauth_token')
  File "/usr/lib/python2.7/dist-packages/keyring/core.py", line 34, in get_password
    return _keyring_backend.get_password(service_name, username)
  File "/usr/lib/python2.7/dist-packages/keyring/backend.py", line 154, in get_password
    items = gnomekeyring.find_network_password_sync(username, service)
gnomekeyring.IOError

**Comment by nvbn** [comment]
What version of ubuntu you use?
What DE you use?
gnome-keyring-daemon is running?

**Comment by Soundistor** [comment]
12.04/Unity
gnome-keyring-daemon is ruuning

@ubuntu:~$ ps -ela | grep keyring
F S   UID   PID  PPID  C PRI  NI ADDR SZ WCHAN  TTY          TIME CMD
5 S  1000  1803     1  0  80   0 - 94013 poll_s ?        00:00:00 gnome-keyring-d

**Comment by Soundistor** [comment]
I'm try to 

@ubuntu:~$ killall gnome-keyring-daemon; gnome-keyring-daemon
GNOME_KEYRING_CONTROL=/tmp/keyring-iMDwhf
SSH_AUTH_SOCK=/tmp/keyring-iMDwhf/ssh
GPG_AGENT_INFO=/tmp/keyring-iMDwhf/gpg:0:1
GNOME_KEYRING_PID=4937

then
@ubuntu:~$ killall everpad-provider; everpad-provider
Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.7/everpad/provider/sync.py", line 47, in run
    self.perform()
  File "/usr/lib/pymodules/python2.7/everpad/provider/sync.py", line 68, in perform
    self.remote_changes()
  File "/usr/lib/pymodules/python2.7/everpad/provider/sync.py", line 81, in remote_changes
    self.notes_remote()
  File "/usr/lib/pymodules/python2.7/everpad/provider/sync.py", line 237, in notes_remote
    self.note_resources_remote(note, nt)
  File "/usr/lib/pymodules/python2.7/everpad/provider/sync.py", line 259, in note_resources_remote
    rs.from_api(resource)
  File "/usr/lib/pymodules/python2.7/everpad/provider/models.py", line 145, in from_api
    self.file_name = resource.attributes.fileName.decode('utf8')
AttributeError: 'NoneType' object has no attribute 'decode'

and seems it works

**Comment by nvbn** [comment]
Yes, but now you have sync error. Update to 1.5.1 and restart everpad-provider, everpad-lens and everpad for fix it.

**Comment by hdave** [comment]
I can confirm that this issue is gone in the new version (once I deleted ~/.everpad).
