### ISSUE TITLE
Wishlist: Add Http proxy support.

### ISSUE THREAD

**Issue by atuljangra** [nvbn/everpad#65]
I can only access Internet through my college's http proxy server. When I try to run Everpad, I get the following message:

<pre>
Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.7/everpad/provider/sync.py", line 63, in run
    self.init_network()
  File "/usr/lib/pymodules/python2.7/everpad/provider/sync.py", line 79, in init_network
    self.note_store = get_note_store(self.auth_token)
  File "/usr/lib/pymodules/python2.7/everpad/provider/tools.py", line 43, in get_note_store
    note_store_url = user_store.getNoteStoreUrl(auth_token)
  File "/usr/lib/pymodules/python2.7/evernote/edam/userstore/UserStore.py", line 613, in getNoteStoreUrl
    self.send_getNoteStoreUrl(authenticationToken)
  File "/usr/lib/pymodules/python2.7/evernote/edam/userstore/UserStore.py", line 622, in send_getNoteStoreUrl
    self._oprot.trans.flush()
  File "/usr/lib/pymodules/python2.7/thrift/transport/THttpClient.py", line 96, in _f
    result = f(*args, **kwargs)
  File "/usr/lib/pymodules/python2.7/thrift/transport/THttpClient.py", line 117, in flush
    self.__http.endheaders()
  File "/usr/lib/python2.7/httplib.py", line 954, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 814, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 776, in send
    self.connect()
  File "/usr/lib/pymodules/python2.7/thrift/transport/httpslib.py", line 35, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 571, in create_connection
    raise err
socket.error: [Errno 111] Connection refused

</pre>

Please add support for Http proxies.

**Comment by utkarshsins** [comment]
Though not needed always, I would prefer this feature too, maybe using gsettings, or in-app manual configuration.

**Comment by hdave** [comment]
It's a known issue with the underlying SDK:

https://github.com/evernote/evernote-sdk-python/issues/2

**Comment by fmoo** [comment]
@atuljangra - have you tried the latest version?  It should be working with Ubuntu at least.  It relies on the http/s_proxy variables being set in the environment, which is at least what Ubuntu's default network config manager thing does.

**Comment by fmoo** [comment]
feel free to reopen if you're still having issues.
