### ISSUE TITLE
Ubuntu 12.04 64bit crash on startup

### ISSUE THREAD

**Issue by stelio** [nvbn/everpad#68]
This happened after a fresh install using ppa:nvbn-rm/ppa

Traceback (most recent call last):
  File "/usr/bin/everpad", line 9, in <module>
    load_entry_point('everpad==1.10dev', 'gui_scripts', 'everpad')()
  File "/usr/lib/pymodules/python2.7/everpad/pad/indicator.py", line 186, in main
    app.provider = get_provider(session_bus) 
  File "/usr/lib/pymodules/python2.7/everpad/tools.py", line 31, in wrapper
    return InterfaceWrapper(partial(fnc, _args, *_kwrags))
  File "/usr/lib/pymodules/python2.7/everpad/tools.py", line 8, in **init**
    self.**load()
  File "/usr/lib/pymodules/python2.7/everpad/tools.py", line 11, in __load
    self.__interface = self.__get()
  File "/usr/lib/pymodules/python2.7/everpad/tools.py", line 38, in get_provider
    provider = bus.get_object("com.everpad.Provider", '/EverpadProvider')
  File "/usr/lib/python2.7/dist-packages/dbus/bus.py", line 241, in get_object
    follow_name_owner_changes=follow_name_owner_changes)
  File "/usr/lib/python2.7/dist-packages/dbus/proxies.py", line 248, in __init**
    self._named_service = conn.activate_name_owner(bus_name)
  File "/usr/lib/python2.7/dist-packages/dbus/bus.py", line 180, in activate_name_owner
    self.start_service_by_name(bus_name)
  File "/usr/lib/python2.7/dist-packages/dbus/bus.py", line 278, in start_service_by_name
    'su', (bus_name, flags)))
  File "/usr/lib/python2.7/dist-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.Spawn.ChildExited: Process /usr/bin/everpad-provider exited with status 1

**Comment by nvbn** [comment]
What output of `everpad-provider --verbose`?

**Comment by stelio** [comment]
Traceback (most recent call last):
  File "/usr/bin/everpad-provider", line 9, in <module>
    load_entry_point('everpad==1.10dev', 'console_scripts', 'everpad-provider')()
  File "/usr/local/lib/python2.7/dist-packages/distribute-0.6.27-py2.7.egg/pkg_resources.py", line 337, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python2.7/dist-packages/distribute-0.6.27-py2.7.egg/pkg_resources.py", line 2307, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python2.7/dist-packages/distribute-0.6.27-py2.7.egg/pkg_resources.py", line 2017, in load
    entry = **import**(self.module_name, globals(),globals(), ['**name**'])
  File "/usr/lib/pymodules/python2.7/everpad/provider/daemon.py", line 3, in <module>
    from everpad.provider.service import ProviderService
  File "/usr/lib/pymodules/python2.7/everpad/provider/service.py", line 3, in <module>
    from everpad.provider.models import (
  File "/usr/lib/pymodules/python2.7/everpad/provider/models.py", line 2, in <module>
    from sqlalchemy.orm import relationship, backref
ImportError: cannot import name relationship

**Comment by nvbn** [comment]
sqlalchemy installed from repository or other source?

**Comment by hdave** [comment]
Is this still an issue? Should it be closed due to inactivity?

**Comment by RobFisher** [comment]
I just saw this on 13.04 64bit, fwiw. 1. Install. 2. Initial sync. 3. Log out and back in because lense was not working. 4. Run everpad from terminal when I notice it is not starting. Same output as above. EDIT: 5. Reboot; all seems to be working now.
