### ISSUE TITLE
KDE support

### ISSUE THREAD

**Issue by oroszgy** [nvbn/everpad#71]
It would be also nice, if it could work on KDE / Kubuntu.

Now it starts, then clicking on "Settings and Management" it crashes:

```
ERROR:dbus.proxies:Introspect error on :1.131:/EverpadProvider: dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NoReply: Message did not receive a reply (timeout by message bus)
ERROR:dbus.proxies:Introspect error on :1.133:/EverpadProvider: dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NoReply: Message did not receive a reply (timeout by message bus)
Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.7/everpad/pad/indicator.py", line 90, in show_management
    self.management = Management(self.app)
  File "/usr/lib/pymodules/python2.7/everpad/pad/management.py", line 46, in __init__
    self.app.provider.get_sync_delay(),
  File "/usr/lib/pymodules/python2.7/everpad/tools.py", line 25, in wrapper
    return getattr(self.__interface, name)(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/dbus/proxies.py", line 70, in __call__
    return self._proxy_method(*args, **keywords)
  File "/usr/lib/python2.7/dist-packages/dbus/proxies.py", line 145, in __call__
    **keywords)
  File "/usr/lib/python2.7/dist-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.ServiceUnknown: The name :1.133 was not provided by any .service files
```

**Comment by ccamara** [comment]
+1

**Comment by m-dye** [comment]
UGH yes. It's so infuriating that this doesn't work. It would be an amazing addition to Kubuntu.

**Comment by fmoo** [comment]
Do you happen to have any links to docs on how to provide kde-compliant service implementations?  I googled around a little bit but couldn't find anything.

**Comment by nvbn** [comment]
everpad-provider is running?

**Comment by oroszgy** [comment]
When trying to run it says:

```
everpad-provider 
QWidget: Cannot create a QWidget when no GUI is being used
```

**Comment by nvbn** [comment]
What kubuntu version you use? What pyside version?

**Comment by lotusk** [comment]
我也是这样，，，根本无法打开
