### ISSUE TITLE
Everpad crashes when creating new note

### ISSUE THREAD

**Issue by JerryPreissler** [nvbn/everpad#74]
New Evernote account, new Everpad install on Ubuntu Quetzal Beta 2 from ppa, Everpad crashes with the following Traceback when clicking on "create note":

jerry@nostromo:~$ LIBOVERLAY_SCROLLBAR=0 everpad
Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.7/everpad/pad/indicator.py", line 83, in create
    self.app.provider.create_note(note_struct),
  File "/usr/lib/pymodules/python2.7/everpad/tools.py", line 25, in wrapper
    return getattr(self.**interface, name)(_args, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/dbus/proxies.py", line 70, in __call**
    return self._proxy_method(_args, *_keywords)
  File "/usr/lib/python2.7/dist-packages/dbus/proxies.py", line 145, in __call__
    *_keywords)
  File "/usr/lib/python2.7/dist-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Python.sqlalchemy.orm.exc.NoResultFound: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/dbus/service.py", line 707, in _message_cb
    retval = candidate_method(self, *args, *_keywords)
  File "/usr/lib/pymodules/python2.7/everpad/provider/service.py", line 181, in create_note
    btype.Note.from_tuple(data).give_to_obj(note)
  File "/usr/lib/pymodules/python2.7/everpad/basetypes.py", line 53, in give_to_obj
    setattr(obj, field[0] + '_dbus', val)
  File "/usr/lib/pymodules/python2.7/everpad/provider/models.py", line 79, in notebook_dbus
    Notebook.default == True,
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2190, in one
    raise orm_exc.NoResultFound("No row was found for one()")
NoResultFound: No row was found for one()

**Comment by nvbn** [comment]
It's after first sync finished?

**Comment by JerryPreissler** [comment]
As far as I can tell yes. I had a timestamp next to "Last Sync" and it displayed the welcome notes that were automatically created by evernote. Strange thing is that it works now - I'm afraid I can´t replicate the problem :-(
