### ISSUE TITLE
gnome-keyring error when clicking evernote icon

### ISSUE THREAD

**Issue by fmoo** [nvbn/everpad#82]
I randomly got this error after stopping/restarting the indicator.py when clicking the icon in the task tray:

```
Gkr-Message: received an invalid, unencryptable, or non-utf8 secret
Gkr-Message: call to daemon returned an invalid response: (null).(null)()
Traceback (most recent call last):
  File "./indicator.py", line 36, in update
    if get_auth_token():
  File "../../everpad/tools.py", line 53, in get_auth_token
    return keyring.get_password('everpad', 'oauth_token')
  File "/usr/lib/python2.7/dist-packages/keyring/core.py", line 34, in get_password
    return _keyring_backend.get_password(service_name, username)
  File "/usr/lib/python2.7/dist-packages/keyring/backend.py", line 154, in get_password
    items = gnomekeyring.find_network_password_sync(username, service)
gnomekeyring.IOError
```

It went away after another restart, but this should probably be handled more gracefully.

**Comment by dementedhedgehog** [comment]
From here https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=659036
Bug in gnome-keyring (posting here for posterity a long time after the inital post )

I had the same problem in Jan 2012 and the workaround is to comment out
"module: gnome-keyring-pkcs11.so"
in /etc/pkcs11/modules/gnome-keyring-module
